#include "pch.h"

// module.g.cpp (generated by cppwinrt.exe) defines these with internal C++ linkage but does not
// export the DLL's actual COM/WinRT entry points - that bridging file is normally scaffolded by
// the Visual Studio "Windows Runtime Component (C++/WinRT)" project wizard, which this
// hand-authored project didn't go through. Declarations must match module.g.cpp's signatures
// exactly (including noexcept) since C++ linkage means the mangled name has to match.
extern std::int32_t __stdcall WINRT_CanUnloadNow() noexcept;
extern std::int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept;

// combaseapi.h already declares both of these (as plain, non-exported prototypes) - defining them
// here with a matching plain signature and exporting via a .def file (dllmain.def) instead of
// __declspec(dllexport) avoids a linkage-mismatch redeclaration error against that header.
extern "C" HRESULT __stdcall DllGetActivationFactory(void* classId, void** factory)
{
    return static_cast<HRESULT>(WINRT_GetActivationFactory(classId, factory));
}

extern "C" HRESULT __stdcall DllCanUnloadNow()
{
    return static_cast<HRESULT>(WINRT_CanUnloadNow());
}
