#!/usr/bin/env python3
"""The macOS app's brand assets, generated from the brand sources.

    python3 brand/generate-macos-icon.py

Writes, and nothing in either should be edited by hand (change a source here and rerun this):

  - src/Ripcord.Mac/RipcordApp/Ripcord.icon, an Icon Composer bundle that Xcode compiles into the app's
    icon (the target's ASSETCATALOG_COMPILER_APPICON_NAME), and the same bundle in RipcordMobile/ for the
    iPhone and iPad app. Two copies of generated output, one source;
  - src/Ripcord.Mac/RipcordMobile/TV.xcassets, Apple TV's App Icon & Top Shelf Image collection, which Icon
    Composer does not produce: two-layer image stacks (the ground behind, the mark in front, for the focus
    parallax) and the Top Shelf banners, as PNGs composed by compose-png.swift. Checked by compiling with
    actool for appletvos and looking at the layers (2026-09-27);
  - src/Ripcord.Mac/Shared/Brand.xcassets/MenuBarMark.imageset, ripcord-mono.svg as a template image for
    the menu bar extra and the Control, which the system tints (DESIGN.md, "Present across the Mac").

Standard library only, plus `xcrun swift` for the Apple TV PNGs.

What goes in follows "The tile is layers" in brand/README.md. macOS 26 draws its own rounded square, its
own margin and its own glass edge, so the bundle carries the ground and the mark and nothing else:

  - the ground is the bundle's fill, a linear gradient of ripcord-ground.svg's two stops;
  - the wedge is one group, and the three dashes another, so the system's glass treats the wedge and the
    trail as two objects, which is what they are;
  - each layer is the mark's own geometry from ripcord-mark-ondark.svg, unmodified, in its 64-unit viewBox
    drawn at the 1024-point canvas. Scaling the whole 64-unit box to the canvas keeps the mark's
    proportion to the tile the same as on Windows, and puts it inside the ø58 safe circle.

How that was checked, 2026-09-26, rather than taken from a recalled grid: the bundle was compiled with
actool (Xcode 27) and the result looked at. The system's shape and margin were applied to the full-canvas
art, and the mark sat inside them. No per-size artwork is supplied, so ripcord-mark-small.svg is not used:
Icon Composer renders small sizes from the same layers. Whether that holds up at 16 px in a Finder list is
[X], looked at once and not measured.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "http://www.w3.org/2000/svg"
BRAND = Path(__file__).resolve().parent
OUT = BRAND.parent / "src" / "Ripcord.Mac" / "RipcordApp" / "Ripcord.icon"
MOBILE = BRAND.parent / "src" / "Ripcord.Mac" / "RipcordMobile" / "Ripcord.icon"
TV = BRAND.parent / "src" / "Ripcord.Mac" / "RipcordMobile" / "TV.xcassets"
MENU_BAR = BRAND.parent / "src" / "Ripcord.Mac" / "Shared" / "Brand.xcassets" / "MenuBarMark.imageset"
CANVAS = 1024


def srgb(hex_colour: str) -> str:
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return f"srgb:{r:.5f},{g:.5f},{b:.5f},1.00000"


def ground_stops() -> list[str]:
    root = ET.parse(BRAND / "ripcord-ground.svg").getroot()
    stops = root.findall(f".//{{{SVG}}}stop")
    return [srgb(s.get("stop-color")) for s in stops]


def mark_elements() -> tuple[ET.Element, list[ET.Element]]:
    root = ET.parse(BRAND / "ripcord-mark-ondark.svg").getroot()
    wedge = root.find(f"{{{SVG}}}path")
    dashes = root.findall(f"{{{SVG}}}rect")
    assert wedge is not None and len(dashes) == 3, "ripcord-mark-ondark.svg is no longer a wedge and three dashes"
    return wedge, dashes


def layer_svg(elements: list[ET.Element]) -> str:
    ET.register_namespace("", SVG)
    svg = ET.Element(f"{{{SVG}}}svg", {"viewBox": "0 0 64 64", "width": str(CANVAS), "height": str(CANVAS)})
    for e in elements:
        e.tail = None
        svg.append(e)
    body = ET.tostring(svg, encoding="unicode")
    return "<!-- Generated by brand/generate-macos-icon.py from ripcord-mark-ondark.svg. Do not edit. -->\n" + body + "\n"


def main() -> None:
    wedge, dashes = mark_elements()
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "Assets").mkdir(parents=True)

    (OUT / "Assets" / "wedge.svg").write_text(layer_svg([wedge]))
    names = ["dash-green", "dash-blue", "dash-red"]
    for name, dash in zip(names, dashes):
        (OUT / "Assets" / f"{name}.svg").write_text(layer_svg([dash]))

    icon = {
        "fill": {"linear-gradient": ground_stops()},
        "groups": [
            {"name": "wedge", "layers": [{"image-name": "wedge.svg", "name": "wedge"}]},
            {"name": "trail", "layers": [{"image-name": f"{n}.svg", "name": n} for n in names]},
        ],
        # iOS as well: compiled with actool for iphoneos and looked at, 2026-09-27.
        "supported-platforms": {"squares": ["iOS", "macOS"]},
    }
    (OUT / "icon.json").write_text(json.dumps(icon, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(BRAND.parent)}")
    if MOBILE.exists():
        shutil.rmtree(MOBILE)
    shutil.copytree(OUT, MOBILE)
    print(f"wrote {MOBILE.relative_to(BRAND.parent)}")
    write_menu_bar_mark()
    write_tv_brand_assets()


def compose(out: Path, width: int, height: int, *parts: str) -> None:
    subprocess.run(["xcrun", "swift", str(BRAND / "compose-png.swift"), str(out), str(width), str(height), *parts],
                   check=True)


def write_tv_brand_assets() -> None:
    """Apple TV's app icon and Top Shelf. The icon is an image stack whose back layer must fill it exactly and
    whose front layer carries the mark, so the focus parallax moves the mark over the ground. The mark sits at
    62% of the height to leave the parallax room to crop."""
    info = {"info": {"author": "xcode", "version": 1}}
    if TV.exists():
        shutil.rmtree(TV)
    brand = TV / "App Icon & Top Shelf Image.brandassets"
    brand.mkdir(parents=True)
    (TV / "Contents.json").write_text(json.dumps(info, indent=2) + "\n")
    mark = f"svg={BRAND / 'ripcord-mark-ondark.svg'}"
    lockup = f"svg={BRAND / 'ripcord-lockup-ondark.svg'}"

    def image_set(folder: Path, name: str, sizes: list[tuple[int, int, str]], *parts: str) -> None:
        folder.mkdir(parents=True)
        images = []
        for width, height, scale in sizes:
            filename = f"{name}@{scale}.png"
            compose(folder / filename, width, height, *parts)
            images.append({"filename": filename, "idiom": "tv", "scale": scale})
        (folder / "Contents.json").write_text(json.dumps({"images": images, **info}, indent=2) + "\n")

    assets = []
    for stack_name, (w, h), scales in [("App Icon - App Store", (1280, 768), ["1x"]), ("App Icon", (400, 240), ["1x", "2x"])]:
        stack = brand / f"{stack_name}.imagestack"
        stack.mkdir()
        (stack / "Contents.json").write_text(json.dumps(
            {"layers": [{"filename": "Front.imagestacklayer"}, {"filename": "Back.imagestacklayer"}], **info}, indent=2) + "\n")
        sizes = [(w * int(s[0]), h * int(s[0]), s) for s in scales]
        for layer, parts in [("Front", (mark, "height=0.62")), ("Back", ("ground",))]:
            folder = stack / f"{layer}.imagestacklayer"
            folder.mkdir()
            (folder / "Contents.json").write_text(json.dumps(info, indent=2) + "\n")
            image_set(folder / "Content.imageset", layer.lower(), sizes, *parts)
        assets.append({"filename": f"{stack_name}.imagestack", "idiom": "tv", "role": "primary-app-icon", "size": f"{w}x{h}"})
    for shelf_name, role, (w, h) in [("Top Shelf Image Wide", "top-shelf-image-wide", (2320, 720)),
                                     ("Top Shelf Image", "top-shelf-image", (1920, 720))]:
        image_set(brand / f"{shelf_name}.imageset", "shelf", [(w, h, "1x"), (w * 2, h * 2, "2x")], "ground", lockup, "height=0.28")
        assets.append({"filename": f"{shelf_name}.imageset", "idiom": "tv", "role": role, "size": f"{w}x{h}"})
    (brand / "Contents.json").write_text(json.dumps({"assets": assets, **info}, indent=2) + "\n")
    print(f"wrote {TV.relative_to(BRAND.parent)}")


def write_menu_bar_mark() -> None:
    """ripcord-mono.svg with currentColor made black: a template image is read for its alpha alone, and an
    asset catalog does not resolve currentColor."""
    catalog = MENU_BAR.parent
    if MENU_BAR.exists():
        shutil.rmtree(MENU_BAR)
    MENU_BAR.mkdir(parents=True)
    (catalog / "Contents.json").write_text(json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
    svg = (BRAND / "ripcord-mono.svg").read_text()
    svg = svg[svg.index("<svg"):].replace("currentColor", "#000000")
    (MENU_BAR / "menubar-mark.svg").write_text(
        "<!-- Generated by brand/generate-macos-icon.py from ripcord-mono.svg. Do not edit. -->\n" + svg)
    contents = {
        "images": [{"filename": "menubar-mark.svg", "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
        "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"},
    }
    (MENU_BAR / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")
    print(f"wrote {MENU_BAR.relative_to(BRAND.parent)}")


if __name__ == "__main__":
    main()
