#!/usr/bin/env python3
"""The macOS app's brand assets, generated from the brand sources.

    python3 brand/generate-macos-icon.py

Writes, and nothing in either should be edited by hand (change a source here and rerun this):

  - src/Ripcord.Mac/RipcordApp/Ripcord.icon, an Icon Composer bundle that Xcode compiles into the app's
    icon (the target's ASSETCATALOG_COMPILER_APPICON_NAME);
  - src/Ripcord.Mac/Shared/Brand.xcassets/MenuBarMark.imageset, ripcord-mono.svg as a template image for
    the menu bar extra and the Control, which the system tints (DESIGN.md, "Present across the Mac").

Standard library only.

What goes in follows "The tile is layers" in brand/README.md. macOS 26 draws its own rounded square, its
own margin and its own glass edge, so the bundle carries the ground and the mark and nothing else:

  - the ground is the bundle's fill, a linear gradient of ripcord-ground.svg's two stops;
  - the wedge is one group, and the three dashes another, so the system's glass treats the wedge and the
    trail as two objects, which is what they are;
  - each layer is the mark's own geometry from ripcord-mark-ondark.svg, unmodified, in its 64-unit viewBox
    drawn at the 1024-point canvas. Scaling the whole 64-unit box to the canvas keeps the mark's
    proportion to the tile the same as on Windows, and puts it inside the ø58 safe circle.

How that was checked, 2026-09-26, rather than taken from a recalled grid: the bundle was compiled with
actool (Xcode 27) and the result looked at. The system's shape and margin were applied to the full-canvas
art, and the mark sat inside them. No per-size artwork is supplied, so ripcord-mark-small.svg is not used:
Icon Composer renders small sizes from the same layers. Whether that holds up at 16 px in a Finder list is
[X], looked at once and not measured.
"""

from __future__ import annotations

import json
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "http://www.w3.org/2000/svg"
BRAND = Path(__file__).resolve().parent
OUT = BRAND.parent / "src" / "Ripcord.Mac" / "RipcordApp" / "Ripcord.icon"
MENU_BAR = BRAND.parent / "src" / "Ripcord.Mac" / "Shared" / "Brand.xcassets" / "MenuBarMark.imageset"
CANVAS = 1024


def srgb(hex_colour: str) -> str:
    h = hex_colour.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return f"srgb:{r:.5f},{g:.5f},{b:.5f},1.00000"


def ground_stops() -> list[str]:
    root = ET.parse(BRAND / "ripcord-ground.svg").getroot()
    stops = root.findall(f".//{{{SVG}}}stop")
    return [srgb(s.get("stop-color")) for s in stops]


def mark_elements() -> tuple[ET.Element, list[ET.Element]]:
    root = ET.parse(BRAND / "ripcord-mark-ondark.svg").getroot()
    wedge = root.find(f"{{{SVG}}}path")
    dashes = root.findall(f"{{{SVG}}}rect")
    assert wedge is not None and len(dashes) == 3, "ripcord-mark-ondark.svg is no longer a wedge and three dashes"
    return wedge, dashes


def layer_svg(elements: list[ET.Element]) -> str:
    ET.register_namespace("", SVG)
    svg = ET.Element(f"{{{SVG}}}svg", {"viewBox": "0 0 64 64", "width": str(CANVAS), "height": str(CANVAS)})
    for e in elements:
        e.tail = None
        svg.append(e)
    body = ET.tostring(svg, encoding="unicode")
    return "<!-- Generated by brand/generate-macos-icon.py from ripcord-mark-ondark.svg. Do not edit. -->\n" + body + "\n"


def main() -> None:
    wedge, dashes = mark_elements()
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "Assets").mkdir(parents=True)

    (OUT / "Assets" / "wedge.svg").write_text(layer_svg([wedge]))
    names = ["dash-green", "dash-blue", "dash-red"]
    for name, dash in zip(names, dashes):
        (OUT / "Assets" / f"{name}.svg").write_text(layer_svg([dash]))

    icon = {
        "fill": {"linear-gradient": ground_stops()},
        "groups": [
            {"name": "wedge", "layers": [{"image-name": "wedge.svg", "name": "wedge"}]},
            {"name": "trail", "layers": [{"image-name": f"{n}.svg", "name": n} for n in names]},
        ],
        "supported-platforms": {"squares": ["macOS"]},
    }
    (OUT / "icon.json").write_text(json.dumps(icon, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(BRAND.parent)}")
    write_menu_bar_mark()


def write_menu_bar_mark() -> None:
    """ripcord-mono.svg with currentColor made black: a template image is read for its alpha alone, and an
    asset catalog does not resolve currentColor."""
    catalog = MENU_BAR.parent
    if MENU_BAR.exists():
        shutil.rmtree(MENU_BAR)
    MENU_BAR.mkdir(parents=True)
    (catalog / "Contents.json").write_text(json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
    svg = (BRAND / "ripcord-mono.svg").read_text()
    svg = svg[svg.index("<svg"):].replace("currentColor", "#000000")
    (MENU_BAR / "menubar-mark.svg").write_text(
        "<!-- Generated by brand/generate-macos-icon.py from ripcord-mono.svg. Do not edit. -->\n" + svg)
    contents = {
        "images": [{"filename": "menubar-mark.svg", "idiom": "universal"}],
        "info": {"author": "xcode", "version": 1},
        "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"},
    }
    (MENU_BAR / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")
    print(f"wrote {MENU_BAR.relative_to(BRAND.parent)}")


if __name__ == "__main__":
    main()
