//! Generates the v1 interoperability constants from the one committed bundle,
//! `src/Ripcord.Protocol.Halyard/Data/halyard-v1-constants.json`, into `OUT_DIR`. The same rule as
//! `libripcord/tools/gen_constants.py`, for the same reason: NOTICE argues for that file, once. A second
//! committed copy of the bytes would be a second bundle with no argument behind it, so no copy is kept
//! here, and a corrected bundle reaches this engine on its next build.
//!
//! The checks are the generator's: every table has its exact length, the control set and the
//! registration set are each complete, and the bundle's top-level `contextKey` equals
//! `contextKeys.selectorOne` (registration reads the latter, so a drift would corrupt the first 16 bytes
//! of the encrypted field). A build that fails any of them does not produce an engine.

use std::fmt::Write as _;
use std::path::PathBuf;

const BUNDLE: &str = "../../src/Ripcord.Protocol.Halyard/Data/halyard-v1-constants.json";

/// Where the .NET reference implementation keeps `Client-Type`: the 32-byte value the console parses by content,
/// generic to the application (CLAUDE.md, "Bounded exception 1"). The engine reads it from here at build
/// time rather than holding a third committed copy.
const CLIENT_TYPE_SOURCE: &str =
    "../../src/Ripcord.Protocol.Halyard.Common/Crypto/HalyardRegistrationMessage.cs";

/// The value of `public const string ClientTypeHex = "...";` in the .NET reference, checked for shape.
fn client_type(manifest: &std::path::Path) -> String {
    let path = manifest.join(CLIENT_TYPE_SOURCE);
    println!("cargo:rerun-if-changed={}", path.display());
    let source = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("the reference's Client-Type source {} could not be read: {e}", path.display())
    });
    let marker = "const string ClientTypeHex = \"";
    let start =
        source.find(marker).unwrap_or_else(|| panic!("no ClientTypeHex definition in {}", path.display()))
            + marker.len();
    let value = &source[start..start + source[start..].find('"').expect("an unterminated ClientTypeHex")];
    assert!(
        value.len() == 64 && value.bytes().all(|b| b.is_ascii_hexdigit()),
        "ClientTypeHex in {} is not 64 hex digits; it was reshaped, and the registration field would be wrong",
        path.display()
    );
    value.to_owned()
}

fn unhex(name: &str, value: &serde_json::Value, len: usize) -> Option<Vec<u8>> {
    let text = value.as_str()?;
    let bytes: Vec<u8> = (0..text.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(text.get(i..i + 2).unwrap_or_else(|| panic!("{name}: odd-length hex")), 16)
        })
        .collect::<Result<_, _>>()
        .unwrap_or_else(|_| panic!("{name}: not valid hex"));
    assert_eq!(bytes.len(), len, "{name}: expected {len} bytes");
    Some(bytes)
}

fn literal(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for b in bytes {
        write!(s, "{b},").unwrap();
    }
    s.push(']');
    s
}

fn emit_optional(out: &mut String, name: &str, bytes: Option<&[u8]>, len: usize) {
    let value = bytes.map_or_else(|| "None".to_owned(), |b| format!("Some({})", literal(b)));
    writeln!(out, "pub(crate) const {name}: Option<[u8; {len}]> = {value};").unwrap();
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let mut out = String::from(
        "// GENERATED by ripcord-proto/build.rs from the committed interop constants bundle. Not committed.\n\
         // Generic v1 constants, identical for every console and account (NOTICE). Nothing personal.\n",
    );
    // Without the `interop-constants` feature the bundle is not read, every table is `None`, and the
    // derivations report the family as absent: the engine's counterpart of .NET's
    // -p:BundleInteropConstants=false. Client-Type is not part of the bundle and is emitted either way.
    if std::env::var_os("CARGO_FEATURE_INTEROP_CONSTANTS").is_some() {
        emit_bundle(&manifest, &mut out);
    } else {
        for name in [
            "KDF_TABLE1",
            "KDF_TABLE2",
            "REGISTRATION_TABLE",
            "MATERIAL_WRAP_TABLE",
            "PS4_KDF_TABLE1",
            "PS4_KDF_TABLE2",
            "PS4_REGISTRATION_TABLE",
            "PS4_MATERIAL_WRAP_TABLE",
        ] {
            emit_optional(&mut out, name, None, 512);
        }
        for name in ["CTX_CODEC_IN_HIGH", "CTX_SELECTOR_ONE", "CTX_SELECTOR_ZERO", "CTX_FALLBACK_ZERO"] {
            emit_optional(&mut out, name, None, 16);
        }
        writeln!(out, "pub(crate) const SELECTOR_OFFSET: Option<usize> = None;").unwrap();
    }
    writeln!(out, "pub(crate) const CLIENT_TYPE_HEX: &str = \"{}\";", client_type(&manifest)).unwrap();

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("halyard_v1_constants.rs");
    std::fs::write(dest, out).expect("write the generated constants");
}

/// Reads and checks the bundle, and writes every table into `out` as `Some`.
fn emit_bundle(manifest: &std::path::Path, out: &mut String) {
    let bundle_path = manifest.join(BUNDLE);
    println!("cargo:rerun-if-changed={}", bundle_path.display());

    let text = std::fs::read_to_string(&bundle_path).unwrap_or_else(|e| {
        panic!("the interop constants bundle {} could not be read: {e}", bundle_path.display())
    });
    let b: serde_json::Value = serde_json::from_str(&text).expect("the bundle is not valid JSON");
    let ctx = &b["contextKeys"];

    let need = |name: &str, v: &serde_json::Value, len: usize| {
        unhex(name, v, len).unwrap_or_else(|| panic!("the bundle is missing {name}"))
    };
    let kdf1 = need("kdfTable1", &b["kdfTable1"], 512);
    let kdf2 = need("kdfTable2", &b["kdfTable2"], 512);
    let codec_in_high = need("codecInHigh", &ctx["codecInHigh"], 16);
    let selector_one = need("selectorOne", &ctx["selectorOne"], 16);
    let selector_zero = need("selectorZero", &ctx["selectorZero"], 16);
    let fallback_zero = need("fallbackZero", &ctx["fallbackZero"], 16);
    let registration = need("registrationTable", &b["registrationTable"], 512);
    let wrap = need("materialWrapTable", &b["materialWrapTable"], 512);
    let context_key = need("contextKey", &b["contextKey"], 16);
    let selector_offset = b["selectorOffset"].as_u64().expect("the bundle is missing selectorOffset");
    assert_eq!(
        context_key, selector_one,
        "contextKey and contextKeys.selectorOne differ; registration would use the wrong field IV"
    );

    let ps4_kdf1 = unhex("ps4KdfTable1", &b["ps4KdfTable1"], 512);
    let ps4_kdf2 = unhex("ps4KdfTable2", &b["ps4KdfTable2"], 512);
    let ps4_registration = unhex("ps4RegistrationTable", &b["ps4RegistrationTable"], 512);
    let ps4_wrap = unhex("ps4MaterialWrapTable", &b["ps4MaterialWrapTable"], 512);
    // A family's pair is both or neither: half a PS4 set would build and fail at the console.
    assert_eq!(ps4_kdf1.is_some(), ps4_kdf2.is_some(), "the bundle has half of the PS4 KDF pair");
    assert_eq!(
        ps4_registration.is_some(),
        ps4_wrap.is_some(),
        "the bundle has half of the PS4 registration pair"
    );

    emit_optional(out, "KDF_TABLE1", Some(&kdf1), 512);
    emit_optional(out, "KDF_TABLE2", Some(&kdf2), 512);
    emit_optional(out, "CTX_CODEC_IN_HIGH", Some(&codec_in_high), 16);
    emit_optional(out, "CTX_SELECTOR_ONE", Some(&selector_one), 16);
    emit_optional(out, "CTX_SELECTOR_ZERO", Some(&selector_zero), 16);
    emit_optional(out, "CTX_FALLBACK_ZERO", Some(&fallback_zero), 16);
    emit_optional(out, "REGISTRATION_TABLE", Some(&registration), 512);
    emit_optional(out, "MATERIAL_WRAP_TABLE", Some(&wrap), 512);
    writeln!(out, "pub(crate) const SELECTOR_OFFSET: Option<usize> = Some({selector_offset});").unwrap();
    emit_optional(out, "PS4_KDF_TABLE1", ps4_kdf1.as_deref(), 512);
    emit_optional(out, "PS4_KDF_TABLE2", ps4_kdf2.as_deref(), 512);
    emit_optional(out, "PS4_REGISTRATION_TABLE", ps4_registration.as_deref(), 512);
    emit_optional(out, "PS4_MATERIAL_WRAP_TABLE", ps4_wrap.as_deref(), 512);
}
