//! Generates the v1 interoperability constants from the one committed bundle,
//! `src/Ripcord.Protocol.Halyard/Data/halyard-v1-constants.json`, into `OUT_DIR`. The same rule as
//! `libripcord/tools/gen_constants.py`, for the same reason: NOTICE argues for that file, once. A second
//! committed copy of the bytes would be a second bundle with no argument behind it, so no copy is kept
//! here, and a corrected bundle reaches this engine on its next build.
//!
//! The checks are the generator's: every table has its exact length, the control set and the
//! registration set are each complete, and the bundle's top-level `contextKey` equals
//! `contextKeys.selectorOne` (registration reads the latter, so a drift would corrupt the first 16 bytes
//! of the encrypted field). A build that fails any of them does not produce an engine.

use std::fmt::Write as _;
use std::path::PathBuf;

const BUNDLE: &str = "../../src/Ripcord.Protocol.Halyard/Data/halyard-v1-constants.json";

fn unhex(name: &str, value: &serde_json::Value, len: usize) -> Option<Vec<u8>> {
    let text = value.as_str()?;
    let bytes: Vec<u8> = (0..text.len())
        .step_by(2)
        .map(|i| {
            u8::from_str_radix(text.get(i..i + 2).unwrap_or_else(|| panic!("{name}: odd-length hex")), 16)
        })
        .collect::<Result<_, _>>()
        .unwrap_or_else(|_| panic!("{name}: not valid hex"));
    assert_eq!(bytes.len(), len, "{name}: expected {len} bytes");
    Some(bytes)
}

fn literal(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for b in bytes {
        write!(s, "{b},").unwrap();
    }
    s.push(']');
    s
}

fn emit(out: &mut String, name: &str, bytes: &[u8]) {
    writeln!(out, "pub(crate) const {name}: [u8; {}] = {};", bytes.len(), literal(bytes)).unwrap();
}

fn emit_optional(out: &mut String, name: &str, bytes: Option<&[u8]>, len: usize) {
    let value = bytes.map_or_else(|| "None".to_owned(), |b| format!("Some({})", literal(b)));
    writeln!(out, "pub(crate) const {name}: Option<[u8; {len}]> = {value};").unwrap();
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let bundle_path = manifest.join(BUNDLE);
    println!("cargo:rerun-if-changed={}", bundle_path.display());

    let text = std::fs::read_to_string(&bundle_path).unwrap_or_else(|e| {
        panic!("the interop constants bundle {} could not be read: {e}", bundle_path.display())
    });
    let b: serde_json::Value = serde_json::from_str(&text).expect("the bundle is not valid JSON");
    let ctx = &b["contextKeys"];

    let need = |name: &str, v: &serde_json::Value, len: usize| {
        unhex(name, v, len).unwrap_or_else(|| panic!("the bundle is missing {name}"))
    };
    let kdf1 = need("kdfTable1", &b["kdfTable1"], 512);
    let kdf2 = need("kdfTable2", &b["kdfTable2"], 512);
    let codec_in_high = need("codecInHigh", &ctx["codecInHigh"], 16);
    let selector_one = need("selectorOne", &ctx["selectorOne"], 16);
    let selector_zero = need("selectorZero", &ctx["selectorZero"], 16);
    let fallback_zero = need("fallbackZero", &ctx["fallbackZero"], 16);
    let registration = need("registrationTable", &b["registrationTable"], 512);
    let wrap = need("materialWrapTable", &b["materialWrapTable"], 512);
    let context_key = need("contextKey", &b["contextKey"], 16);
    let selector_offset = b["selectorOffset"].as_u64().expect("the bundle is missing selectorOffset");
    assert_eq!(
        context_key, selector_one,
        "contextKey and contextKeys.selectorOne differ; registration would use the wrong field IV"
    );

    let ps4_kdf1 = unhex("ps4KdfTable1", &b["ps4KdfTable1"], 512);
    let ps4_kdf2 = unhex("ps4KdfTable2", &b["ps4KdfTable2"], 512);
    let ps4_registration = unhex("ps4RegistrationTable", &b["ps4RegistrationTable"], 512);
    let ps4_wrap = unhex("ps4MaterialWrapTable", &b["ps4MaterialWrapTable"], 512);
    // A family's pair is both or neither: half a PS4 set would build and fail at the console.
    assert_eq!(ps4_kdf1.is_some(), ps4_kdf2.is_some(), "the bundle has half of the PS4 KDF pair");
    assert_eq!(
        ps4_registration.is_some(),
        ps4_wrap.is_some(),
        "the bundle has half of the PS4 registration pair"
    );

    let mut out = String::from(
        "// GENERATED by ripcord-proto/build.rs from the committed interop constants bundle. Not committed.\n\
         // Generic v1 constants, identical for every console and account (NOTICE). Nothing personal.\n",
    );
    emit(&mut out, "KDF_TABLE1", &kdf1);
    emit(&mut out, "KDF_TABLE2", &kdf2);
    emit(&mut out, "CTX_CODEC_IN_HIGH", &codec_in_high);
    emit(&mut out, "CTX_SELECTOR_ONE", &selector_one);
    emit(&mut out, "CTX_SELECTOR_ZERO", &selector_zero);
    emit(&mut out, "CTX_FALLBACK_ZERO", &fallback_zero);
    emit(&mut out, "REGISTRATION_TABLE", &registration);
    emit(&mut out, "MATERIAL_WRAP_TABLE", &wrap);
    writeln!(out, "pub(crate) const SELECTOR_OFFSET: usize = {selector_offset};").unwrap();
    emit_optional(&mut out, "PS4_KDF_TABLE1", ps4_kdf1.as_deref(), 512);
    emit_optional(&mut out, "PS4_KDF_TABLE2", ps4_kdf2.as_deref(), 512);
    emit_optional(&mut out, "PS4_REGISTRATION_TABLE", ps4_registration.as_deref(), 512);
    emit_optional(&mut out, "PS4_MATERIAL_WRAP_TABLE", ps4_wrap.as_deref(), 512);

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("halyard_v1_constants.rs");
    std::fs::write(dest, out).expect("write the generated constants");
}
