/*
 * ripcord-3ds - cryptographic primitives seam.
 *
 * This is the C counterpart of Ripcord.Core.Net.Crypto: AES-128 (forward direction only), SHA-256,
 * HMAC-SHA-256, and the keystream cipher modes built on them. It knows nothing about PlayStation - the
 * protocol layer in source/halyard sits on top, exactly as Ripcord.Core.Net sits below
 * Ripcord.Protocol.Halyard.Common.
 *
 * WHY A SEAM RATHER THAN A DIRECT mbedtls DEPENDENCY.
 *   devkitPro ships mbedtls for the 3DS, and on real hardware it is the better backend: the ARM11 has no
 *   crypto extensions, every A/V packet pays for AES, and mbedtls has hand-tuned paths this file does not.
 *   But the whole point of this port is to check the spec by running the same known-answer vectors the .NET
 *   side produces, and that check is worth far more if it runs on any machine with a C compiler and nothing
 *   else installed. So the default build uses the self-contained implementation here, and
 *   -DRC_CRYPTO_MBEDTLS swaps in mbedtls behind the same three functions. Same seam-and-stub shape the
 *   repository uses for IHalyardSessionCrypto.
 *
 * ON ROLLING OUR OWN. These are the forward AES block permutation and SHA-256, both transcribed from
 * FIPS-197 and FIPS 180-4 - public specifications, which is the only source clean-room rules permit here
 * anyway. Only the encrypt direction of AES exists, because CFB, OFB and CTR never invoke the inverse
 * cipher; that removes the inverse S-box and InvMixColumns entirely. Correctness is not asserted, it is
 * tested: tests/vector_runner.c checks every one of these against vectors generated by .NET's own
 * implementation, and the NIST SP 800-38A mode vectors are in there too.
 */
#ifndef RC_CRYPTO_H
#define RC_CRYPTO_H

#include <stddef.h>
#include <stdint.h>

#define RC_AES_BLOCK_SIZE 16
#define RC_AES128_KEY_SIZE 16
#define RC_SHA256_DIGEST_SIZE 32
#define RC_SHA256_BLOCK_SIZE 64

/* ---- AES-128, forward direction ---- */

/*
 * The schedule is held as 32-bit words, not bytes, and that is a performance decision rather than a
 * stylistic one. The block function keeps its state in four word-sized registers; a byte schedule would
 * force it to reassemble every round key from four byte loads and three shifts, 16 times per block.
 */
typedef struct {
    uint32_t round_keys[44]; /* 11 round keys of 4 big-endian words */
} rc_aes128;

/* Expand a 16-byte key into the round-key schedule. Cheap, but not free: the A/V path should expand once
 * per session and reuse the context, which is why the schedule is a caller-owned struct rather than an
 * argument to the block function. Ripcord learned this the expensive way - see the remarks on
 * AesKeystreamModes.CreateReusableEcb. */
void rc_aes128_init(rc_aes128 *ctx, const uint8_t key[RC_AES128_KEY_SIZE]);

/* Encrypt exactly one 16-byte block. `in` and `out` may alias. */
void rc_aes128_encrypt_block(const rc_aes128 *ctx,
                             const uint8_t in[RC_AES_BLOCK_SIZE],
                             uint8_t out[RC_AES_BLOCK_SIZE]);

/* ---- SHA-256 and HMAC-SHA-256 ---- */

typedef struct {
    uint32_t state[8];
    uint64_t bit_length;
    uint8_t buffer[RC_SHA256_BLOCK_SIZE];
    size_t buffered;
} rc_sha256;

void rc_sha256_init(rc_sha256 *ctx);
void rc_sha256_update(rc_sha256 *ctx, const uint8_t *data, size_t length);
void rc_sha256_final(rc_sha256 *ctx, uint8_t digest[RC_SHA256_DIGEST_SIZE]);

void rc_sha256_hash(const uint8_t *data, size_t length, uint8_t digest[RC_SHA256_DIGEST_SIZE]);

void rc_hmac_sha256(const uint8_t *key, size_t key_length,
                    const uint8_t *message, size_t message_length,
                    uint8_t mac[RC_SHA256_DIGEST_SIZE]);

/* ---- Keystream cipher modes (NIST SP 800-38A) ---- */

/*
 * AES-128-CFB with a 128-bit feedback segment. `encrypt` selects the direction, which is NOT a symmetric
 * operation: the feedback register always takes the ciphertext, so on encrypt it takes the output and on
 * decrypt the input. A partial final block terminates the stream and does not feed forward - invisible
 * whenever the input is a multiple of 16, which is why the vectors deliberately include lengths that are
 * not. `in` and `out` may alias.
 */
void rc_aes128_cfb128(const uint8_t key[RC_AES128_KEY_SIZE],
                      const uint8_t iv[RC_AES_BLOCK_SIZE],
                      const uint8_t *in, uint8_t *out, size_t length,
                      int encrypt);

/* AES-128-OFB. Symmetric: encrypt and decrypt are the same call. `in` and `out` may alias. */
void rc_aes128_ofb(const uint8_t key[RC_AES128_KEY_SIZE],
                   const uint8_t iv[RC_AES_BLOCK_SIZE],
                   const uint8_t *in, uint8_t *out, size_t length);

/*
 * AES-128-CTR over a caller-supplied 16-byte initial counter block.
 *
 * `little_endian_counter` picks which way the 128-bit counter increments. Standard CTR is big-endian;
 * the PS5 A/V stream cipher increments LITTLE-endian (byte 0 first, carry upward). This is not a
 * stylistic difference - getting it wrong corrupts every block after the first, which decodes as a valid
 * NAL header followed by garbage and so looks like a decoder bug rather than a crypto one. The .NET side
 * carries the same flag on AesKeystreamModes.Ctr for the same reason.
 */
void rc_aes128_ctr(const uint8_t key[RC_AES128_KEY_SIZE],
                   const uint8_t initial_counter[RC_AES_BLOCK_SIZE],
                   const uint8_t *in, uint8_t *out, size_t length,
                   int little_endian_counter);

#endif /* RC_CRYPTO_H */
