/*
 * ripcord-3ds - discovery parser self-test.
 *
 * Unlike the crypto vector runner, this needs no vector file from the .NET side: the SRCH wire format
 * is plain ASCII text taken verbatim from docs/protocol/ps5-local-discovery.md, so the expected bytes
 * are transcribed directly from the spec below rather than generated by a second implementation. What
 * this checks is that this port's C reads the same spec the same way - a hand-written mismatch here
 * would mean a misreading of the doc, not a cross-language KDF disagreement.
 *
 * THIS BUILDS FOR THE HOST, NOT THE 3DS - see tests/Makefile. halyard_discovery.c has no socket or
 * hardware dependency of its own (see its header), so there is nothing 3DS-specific to verify here.
 */
#include "../discovery/halyard_discovery.h"

#include <stdio.h>
#include <string.h>

static int g_passed;
static int g_failed;

#define CHECK(cond, ...) do { \
    if (cond) { \
        g_passed++; \
    } else { \
        g_failed++; \
        printf("FAIL %s:%d: ", __FILE__, __LINE__); \
        printf(__VA_ARGS__); \
        printf("\n"); \
    } \
} while (0)

static void test_build_probe(void)
{
    char buf[256];
    size_t n;

    /* Verbatim from the spec's "Request" block, CRLF-terminated, trailing blank line included. */
    static const char expected_ps5[] =
        "SRCH * HTTP/1.1\r\ndevice-discovery-protocol-version:00030010\r\n\r\n";
    static const char expected_ps4[] =
        "SRCH * HTTP/1.1\r\ndevice-discovery-protocol-version:00020020\r\n\r\n";

    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps5, buf, sizeof(buf));
    CHECK(n == strlen(expected_ps5) && memcmp(buf, expected_ps5, n) == 0,
        "ps5 probe bytes did not match the spec's request block");

    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps4, buf, sizeof(buf));
    CHECK(n == strlen(expected_ps4) && memcmp(buf, expected_ps4, n) == 0,
        "ps4 probe bytes did not match the spec's request block (device-discovery-protocol-version)");

    /* A buffer too small to hold the datagram must fail closed, not silently truncate a UDP payload the
     * caller would otherwise send as-is. */
    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps5, buf, 8);
    CHECK(n == 0, "undersized buffer should report 0, not a truncated length");
}

static void test_awake_response(void)
{
    /* Verbatim from the spec's "Response" block, with placeholders filled in. */
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n"
        "host-name:Living Room PS5\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00030010\r\n"
        "system-version:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), "192.168.1.42", &console);

    CHECK(ok == 1, "a well-formed 200 Ok response should parse");
    CHECK(console.is_awake == 1, "status 200 should set is_awake");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch: got '%s'", console.host_id);
    CHECK(strcmp(console.host_type, "PS5") == 0, "host_type mismatch: got '%s'", console.host_type);
    CHECK(strcmp(console.host_name, "Living Room PS5") == 0, "host_name mismatch: got '%s'", console.host_name);
    CHECK(strcmp(console.system_version, "09030008") == 0,
        "system_version mismatch: got '%s'", console.system_version);
    CHECK(strcmp(console.address, "192.168.1.42") == 0, "address mismatch: got '%s'", console.address);
}

static void test_standby_response(void)
{
    /* Verbatim from the "LAN wake" section's standby status line. */
    static const char response[] =
        "HTTP/1.1 620 Server Standby\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n"
        "host-name:Living Room PS5\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00030010\r\n"
        "system-version:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), NULL, &console);

    CHECK(ok == 1, "a well-formed 620 Server Standby response should still parse");
    CHECK(console.is_awake == 0, "status 620 should clear is_awake");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch on standby reply");
    CHECK(console.address[0] == '\0', "a NULL source_address should leave address empty, got '%s'", console.address);
}

static void test_ps4_response(void)
{
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:aabbccddeeff\r\n"
        "host-type:PS4\r\n"
        "host-name:Bedroom PS4\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00020020\r\n"
        "system-version:09000000\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), "10.0.0.5", &console);

    CHECK(ok == 1, "a well-formed PS4 response should parse the same as a PS5 one");
    CHECK(strcmp(console.host_type, "PS4") == 0, "host_type should be PS4, got '%s'", console.host_type);
}

static void test_defaults_and_case_insensitivity(void)
{
    /* host-type omitted entirely, and every remaining header name given in a different case - the
     * spec's own client (HalyardSearchClient.TryParse) does both: GetValueOrDefault("host-type", "PS5")
     * and an OrdinalIgnoreCase field dictionary. */
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "HOST-ID:  001122334455  \r\n"
        "Host-Name:Trimmed Name\r\n"
        "SYSTEM-VERSION:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), NULL, &console);

    CHECK(ok == 1, "omitting host-type entirely should not fail parsing");
    CHECK(strcmp(console.host_type, "PS5") == 0,
        "a missing host-type should default to PS5, got '%s'", console.host_type);
    CHECK(strcmp(console.host_id, "001122334455") == 0,
        "surrounding whitespace around a header value should be trimmed, got '%s'", console.host_id);
    CHECK(strcmp(console.host_name, "Trimmed Name") == 0, "host_name mismatch: got '%s'", console.host_name);
}

static void test_rejects_non_srch_and_missing_host_id(void)
{
    static const char garbage[] = "this is not a SRCH response at all\r\n\r\n";
    static const char no_host_id[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-type:PS5\r\n"
        "\r\n";
    halyard_discovered_console console;

    CHECK(halyard_discovery_parse_response(garbage, strlen(garbage), NULL, &console) == 0,
        "arbitrary text without an HTTP/1.1 status line must be rejected");
    CHECK(halyard_discovery_parse_response(no_host_id, strlen(no_host_id), NULL, &console) == 0,
        "a response with no host-id must be rejected - it is the one field the spec's own client requires");
}

static void test_truncated_datagram(void)
{
    /* A UDP datagram is delivered whole or not at all, but SRCH is worth being lenient with anyway: the
     * status line and host-id are both near the front, and a caller (e.g. a raced parse of a datagram
     * shorter than expected) should still get a usable result rather than a hard failure over a trailing
     * field it does not need. */
    static const char truncated[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(truncated, strlen(truncated), NULL, &console);

    CHECK(ok == 1, "a datagram missing its trailing blank line should still parse if host-id is present");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch on truncated datagram");
}

int main(void)
{
    test_build_probe();
    test_awake_response();
    test_standby_response();
    test_ps4_response();
    test_defaults_and_case_insensitivity();
    test_rejects_non_srch_and_missing_host_id();
    test_truncated_datagram();

    printf("\n%d passed, %d failed\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}
