using System.ComponentModel;
using Ripcord.Core.Reactive;
using Ripcord.Presentation.Threading;

namespace Ripcord.Presentation;

/// <summary>
/// Base for every view-model in this layer: one piece of state, immutable, recomposed whole.
///
/// <para>
/// <b>Why not per-property notification.</b> The app's previous only view-model raised <em>eleven</em> property
/// names from a single setter, with a comment warning that "missing one of these leaves a card reading 'Offline'
/// above a 'Connect' button", plus a second cascade of seven elsewhere in the same class. The lesson is not that
/// such a cascade should be generated by a source generator — it is that it should not exist. Here
/// <see cref="Compose"/> rebuilds the whole state, so there is exactly one property to notify about and a
/// half-updated view-model is unrepresentable. Record value equality then answers "did anything actually change?"
/// once, centrally, instead of via an early-return guard in every setter.
/// </para>
///
/// <para>
/// <b>Two channels, one value.</b> <see cref="INotifyPropertyChanged"/> on the single <see cref="State"/>
/// property is what XAML's compiled bindings want — a nested path such as <c>State.DisplayName</c> re-reads when
/// <c>State</c> itself changes, so the leaf record needs no notification of its own. <see cref="Changes"/> is what
/// a non-XAML front end wants, and maps onto SwiftUI/Combine, a GTK signal, or a callback across a NativeAOT
/// boundary. Both carry the identical immutable value, so neither is a projection of the other and there is
/// nothing to keep in sync. This is also the shape <c>SessionController.Status</c> already publishes, so it is
/// the house pattern rather than a new one.
/// </para>
///
/// <para>
/// <b>The cost, stated.</b> Because there is one notifying property, a change to any field re-evaluates every
/// binding on the object — a status change also re-reads the name. For the collection sizes here (a handful of
/// console cards) that is the right trade for deleting the cascade; if a surface ever binds hundreds of rows,
/// revisit it there rather than reintroducing per-property notification everywhere.
/// </para>
/// </summary>
public abstract class ObservableState<TState> : INotifyPropertyChanged
    where TState : class
{
    // Allocated once: this event fires on every mutation of every view-model, and the args are immutable.
    private static readonly PropertyChangedEventArgs StateChangedArgs = new(nameof(State));

    private readonly IUiDispatcher _dispatcher;
    private readonly Subject<TState> _changes = new();
    private TState? _state;

    protected ObservableState(IUiDispatcher dispatcher)
        => _dispatcher = dispatcher ?? throw new ArgumentNullException(nameof(dispatcher));

    /// <summary>
    /// Everything this view-model currently shows, as one value. Composed lazily on first read so a subclass
    /// constructor can finish initialising its fields before <see cref="Compose"/> is called.
    /// </summary>
    /// <remarks>Read on the UI thread. See <see cref="IUiDispatcher"/> for why that is a rule and not a hope.</remarks>
    public TState State => _state ??= Compose();

    /// <summary>The same values <see cref="PropertyChanged"/> announces, for a front end that prefers a stream.</summary>
    public IObservable<TState> Changes => _changes;

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>
    /// Build the current state from this view-model's fields. Called on the dispatcher thread only, so an
    /// implementation needs no synchronisation. Must be a pure function of the fields — it is called again after
    /// every mutation, and anything with a side effect would fire repeatedly.
    /// </summary>
    protected abstract TState Compose();

    /// <summary>
    /// Apply a field change, recompose, and notify — the only place in this layer where a mutation happens, and
    /// therefore the only place that marshals. A subclass never calls the dispatcher itself.
    /// </summary>
    protected void Mutate(Action apply)
    {
        ArgumentNullException.ThrowIfNull(apply);

        // Synchronous when already on the UI thread, so a caller that mutates and then reads State on the next
        // line sees its own write. Posting unconditionally would break that.
        if (_dispatcher.IsOnUiThread)
        {
            Apply(apply);
            return;
        }

        _dispatcher.Post(() => Apply(apply));
    }

    /// <summary>
    /// Force a recompose without changing a field, for state that depends on something external — a clock, say,
    /// where "played 2 hours ago" goes stale on its own.
    /// </summary>
    protected void Refresh() => Mutate(static () => { });

    private void Apply(Action apply)
    {
        apply();

        TState next = Compose();

        // Records give value equality for free, so a mutation that changes nothing observable is silent. This is
        // what makes Refresh() and idempotent setters cheap rather than a source of binding churn.
        if (next.Equals(_state))
        {
            return;
        }

        _state = next;
        PropertyChanged?.Invoke(this, StateChangedArgs);
        _changes.OnNext(next);
    }
}
