/*
 * ripcord-3ds - AES-128-GMAC (NIST SP 800-38D), the authentication-only half of GCM.
 *
 * Ported from Ripcord.Core.Net.Crypto.AesGcmCore's bit-serial reference path (its own doc comment: the
 * platform AesGcm type refuses non-96-bit nonces, and the Halyard stream MAC's nonce is a full 16 bytes,
 * so that project implements GCM from the specification too - this is not a case of the C side doing
 * something the .NET side avoided). Checked against it with cross-language vectors
 * (tests/vectors/stream-crypto.kat's `gmac` lines, generated by `dotnet run --project
 * tools/Ripcord.ProtocolLab -- vectors` via `AesGcmCore.Mac` directly) rather than transcribed NIST test
 * vectors - a memorized hex constant that turned out subtly wrong would be worse than no vector whatsoever.
 *
 * ONLY GMAC, NOT FULL GCM ENCRYPT/DECRYPT: the Halyard packet cipher never calls GCM's own GCTR path -
 * `HalyardPacketCrypto` computes the tag via `AesGcmCore.Mac` (AAD-only, empty message) and encrypts the
 * payload separately with a bespoke little-endian-counter AES-CTR (already ported as
 * rc_aes128_ctr(..., little_endian_counter=1) in rc_modes.c). So this file implements exactly the subset
 * this protocol needs - GHASH, the GHASH-based J0 derivation for a non-96-bit IV, and the single-block tag
 * - not the GCTR ciphertext path, which would be unused dead code here.
 *
 * ONLY THE NON-96-BIT IV PATH: GCM defines two ways to compute J0 - a shortcut for exactly a 96-bit (12-
 * byte) IV, and a GHASH-based derivation for any other length. This protocol's IV is always 16 bytes, so
 * only the GHASH path is implemented; passing a 12-byte IV here would NOT match the shortcut real GCM
 * defines for that length (a deliberate scope decision, not an oversight - see rc_gmac()'s doc comment).
 */
#ifndef RC_GCM_H
#define RC_GCM_H

#include <stddef.h>
#include <stdint.h>

/*
 * Computes the 16-byte GMAC tag over `aad` under `key`/`iv` (empty message - this protocol never uses
 * GCM's own encrypt path, see the file header). `iv_len` may be any length except 12 - a 12-byte IV
 * needs GCM's other J0 shortcut, not implemented here since this protocol's IV is always 16 bytes.
 * Callers needing the protocol's 4-byte truncated tag take the first 4 bytes of `tag`.
 */
void rc_gmac(const uint8_t key[16], const uint8_t *iv, size_t iv_len,
            const uint8_t *aad, size_t aad_len, uint8_t tag[16]);

#endif /* RC_GCM_H */
