/*
 * ripcord-3ds - AES-128-GMAC (NIST SP 800-38D), the authentication-only half of GCM.
 *
 * Ported from Ripcord.Core.Net.Crypto.AesGcmCore's bit-serial reference path (its own doc comment: the
 * platform AesGcm type refuses non-96-bit nonces, and the Halyard stream MAC's nonce is a full 16 bytes,
 * so that project implements GCM from the specification too - this is not a case of the C side doing
 * something the .NET side avoided). Checked against it with cross-language vectors
 * (tests/vectors/stream-crypto.kat's `gmac` lines, generated by `dotnet run --project
 * tools/Ripcord.ProtocolLab -- vectors` via `AesGcmCore.Mac` directly) rather than transcribed NIST test
 * vectors - a memorized hex constant that turned out subtly wrong would be worse than no vector whatsoever.
 *
 * ONLY GMAC, NOT FULL GCM ENCRYPT/DECRYPT: the Halyard packet cipher never calls GCM's own GCTR path -
 * `HalyardPacketCrypto` computes the tag via `AesGcmCore.Mac` (AAD-only, empty message) and encrypts the
 * payload separately with a bespoke little-endian-counter AES-CTR (already ported as
 * rc_aes128_ctr(..., little_endian_counter=1) in rc_modes.c). So this file implements exactly the subset
 * this protocol needs - GHASH, the GHASH-based J0 derivation for a non-96-bit IV, and the single-block tag
 * - not the GCTR ciphertext path, which would be unused dead code here.
 *
 * ONLY THE NON-96-BIT IV PATH: GCM defines two ways to compute J0 - a shortcut for exactly a 96-bit (12-
 * byte) IV, and a GHASH-based derivation for any other length. This protocol's IV is always 16 bytes, so
 * only the GHASH path is implemented; passing a 12-byte IV here would NOT match the shortcut real GCM
 * defines for that length (a deliberate scope decision, not an oversight - see rc_gmac()'s doc comment).
 */
#ifndef RC_GCM_H
#define RC_GCM_H

#include <stddef.h>
#include <stdint.h>

#include "rc_crypto.h"

/*
 * A GMAC key with its GHASH multiplication tables built.
 *
 * WHY THIS EXISTS RATHER THAN A KEY-AND-GO CALL. Measured on hardware, a GMAC over a ~1,100-byte packet
 * cost **1,264 us** - about 22% of one ARM11 core across a real stream, with a second, unsampled GMAC
 * inside the demux on top. The cause was the multiply: bit-serial GF(2^128), 128 iterations each doing a
 * 16-byte shift and a conditional 16-byte XOR, roughly 3,000 byte-operations per multiply and ~69
 * multiplies per packet.
 *
 * A byte-indexed table replaces that with one lookup and two XORs per input byte, about 5x fewer
 * operations - but the tables cost ~4.6 KB to build, so rebuilding them per call would be far worse than
 * the problem. Hence a prepared key: this protocol rotates its GMAC key roughly every 650 packets
 * (45,000 key-position units), so one build serves hundreds of packets.
 *
 * DO NOT put one on the stack in the 3DS build - it is over the 8 KB frame limit the build enforces, and
 * for good reason (see takion_reliable_channel.h for what an oversized local does on this hardware).
 */
typedef struct {
    rc_aes128 aes;
    uint8_t h[16];
    uint8_t table[256][16];   /* table[b] = b * H, with b's MSB as the x^0 coefficient */
    uint16_t reduce[256];     /* the reduction produced by shifting byte 15 out, bytes 0..1 only */
    uint8_t key[16];
    int ready;
} rc_gmac_key;

/* Derives H from `key` and builds the tables. Cheap enough to call whenever the key rotates, and far too
 * expensive to call per packet. */
void rc_gmac_key_init(rc_gmac_key *gk, const uint8_t key[16]);

/* 1 if `gk` is already prepared for exactly this key, so a caller can skip a rebuild. */
int rc_gmac_key_matches(const rc_gmac_key *gk, const uint8_t key[16]);

/*
 * Computes the 16-byte GMAC tag over `aad` under a prepared key and `iv` (empty message - this protocol
 * never uses GCM's own encrypt path, see the file header). `iv_len` may be any length except 12 - a
 * 12-byte IV needs GCM's other J0 shortcut, not implemented here since this protocol's IV is always 16
 * bytes. Callers needing the protocol's 4-byte truncated tag take the first 4 bytes of `tag`.
 */
void rc_gmac_with_key(const rc_gmac_key *gk, const uint8_t *iv, size_t iv_len,
                      const uint8_t *aad, size_t aad_len, uint8_t tag[16]);

#endif /* RC_GCM_H */
