/*
 * libripcord - the account route's 9303 datagram transport: framing, association, and the pump.
 *
 * THREE KINDS OF EVIDENCE, in order of strength:
 *
 *   1. vectors/dgram-transport.kat, generated by `ProtocolLab vectors` from HalyardControlAssociation
 *      itself (tools/Ripcord.ProtocolLab/LabDatagramVectors.cs). Every operation of three scripted
 *      exchanges is replayed here with the same counting random source, and every emitted datagram, every
 *      event and every phase must match the reference byte for byte. This is the check that the two
 *      state machines are one state machine.
 *   2. The .NET unit tests' own synthetic vectors, transcribed: HalyardControlChunkTests.cs (framing, the
 *      prelude, and every malformed shape), HalyardControlAssociationTests.cs (the rules asserted by name),
 *      and the two channel suites (HalyardDatagramControlChannelTests.cs,
 *      HalyardDatagramSessionControlChannelTests.cs), whose scripted consoles are reproduced below.
 *   3. The bounds C needs and C# does not, since here a trusted length is a memory-safety bug.
 *
 * Nothing here comes from a capture. The peer is a documentation address; the ids count up.
 */
#include "../session/halyard_dgram.h"
#include "../session/halyard_dgram_channel.h"
#include "../platform/rc_platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

static int g_passed;
static int g_failed;

#define CHECK(cond, ...) do { \
    if (cond) { \
        g_passed++; \
    } else { \
        g_failed++; \
        printf("FAIL %s:%d: ", __FILE__, __LINE__); \
        printf(__VA_ARGS__); \
        printf("\n"); \
    } \
} while (0)

/*
 * THE CHANNEL'S RANDOMNESS, AND IT IS NOT RANDOM: the host seam deliberately has no CSPRNG
 * (rc_platform_host.c says why), so the test supplies one - the same counter .NET's tests use, bytes
 * counting up from 0x40. Safe only because every peer here is a script in this process.
 */
static uint8_t g_next = 0x40;

int rc_random_bytes(uint8_t *out, size_t length)
{
    size_t i;

    for (i = 0; i < length; i++)
        out[i] = g_next++;
    return 1;
}

static int hex_nibble(char c)
{
    if (c >= '0' && c <= '9')
        return c - '0';
    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;
    if (c >= 'A' && c <= 'F')
        return c - 'A' + 10;
    return -1;
}

/* Decodes `text` (or "-" for empty) of `text_length` chars. Returns the byte count, or (size_t)-1. */
static size_t from_hex_n(const char *text, size_t text_length, uint8_t *out, size_t capacity)
{
    size_t i;

    if (text_length == 1 && text[0] == '-')
        return 0;
    if (text_length % 2 != 0 || text_length / 2 > capacity)
        return (size_t)-1;
    for (i = 0; i < text_length; i += 2) {
        int hi = hex_nibble(text[i]);
        int lo = hex_nibble(text[i + 1]);

        if (hi < 0 || lo < 0)
            return (size_t)-1;
        out[i / 2] = (uint8_t)((hi << 4) | lo);
    }
    return text_length / 2;
}

static size_t from_hex(const char *text, uint8_t *out, size_t capacity)
{
    return from_hex_n(text, strlen(text), out, capacity);
}

static const uint8_t *our_id(void)
{
    static uint8_t id[20];
    int i;

    for (i = 0; i < 20; i++)
        id[i] = (uint8_t)(i + 1);
    return id;
}

static const uint8_t *peer_id(void)
{
    static uint8_t id[20];
    int i;

    for (i = 0; i < 20; i++)
        id[i] = (uint8_t)(101 + i);
    return id;
}

static const uint8_t k_peer_address[4] = { 192, 0, 2, 7 };
#define PEER_PORT 9303u

/* ==== a recording association ======================================================================== */

#define REC_MAX_SENDS 16
#define REC_MAX_EVENTS 16

typedef struct {
    size_t send_count;
    size_t send_length[REC_MAX_SENDS];
    uint8_t sends[REC_MAX_SENDS][HALYARD_DGRAM_MAX_DATAGRAM];
    size_t event_count;
    halyard_dgram_event_kind events[REC_MAX_EVENTS];
    int opened_by_peer[REC_MAX_EVENTS];
    size_t data_length[REC_MAX_EVENTS];
    uint8_t data[REC_MAX_EVENTS][512];
    uint8_t random_next;
    int random_fails;
} recorder;

static void rec_send(void *ctx, const uint8_t *datagram, size_t length)
{
    recorder *r = (recorder *)ctx;

    if (r->send_count < REC_MAX_SENDS && length <= HALYARD_DGRAM_MAX_DATAGRAM) {
        memcpy(r->sends[r->send_count], datagram, length);
        r->send_length[r->send_count] = length;
    }
    r->send_count++;
}

static void rec_event(void *ctx, const halyard_dgram_event *event)
{
    recorder *r = (recorder *)ctx;

    if (r->event_count < REC_MAX_EVENTS) {
        r->events[r->event_count] = event->kind;
        r->opened_by_peer[r->event_count] = event->opened_by_peer;
        r->data_length[r->event_count] = event->data_length;
        if (event->kind == HALYARD_DGRAM_EVENT_DATA_RECEIVED && event->data_length <= sizeof(r->data[0]))
            memcpy(r->data[r->event_count], event->data, event->data_length);
    }
    r->event_count++;
}

static int rec_random(void *ctx, uint8_t *out, size_t length)
{
    recorder *r = (recorder *)ctx;
    size_t i;

    if (r->random_fails)
        return 0;
    for (i = 0; i < length; i++)
        out[i] = r->random_next++;
    return 1;
}

static void rec_reset(recorder *r)
{
    r->send_count = 0;
    r->event_count = 0;
}

static void new_assoc(halyard_dgram_assoc *a, recorder *r)
{
    halyard_dgram_callbacks cb;

    memset(r, 0, sizeof(*r));
    r->random_next = 0x40;
    cb.send = rec_send;
    cb.event = rec_event;
    cb.random = rec_random;
    cb.ctx = r;
    halyard_dgram_assoc_init(a, &cb, our_id(), peer_id(), k_peer_address, PEER_PORT);
}

/* ==== 1. the reference transcripts =================================================================== */

static char g_line[1 << 17];

/* Splits `text` on ',' and compares each piece against what was recorded. */
static int sends_match(const recorder *r, const char *expected)
{
    size_t index = 0;
    const char *p = expected;
    uint8_t want[HALYARD_DGRAM_MAX_DATAGRAM];

    if (strcmp(expected, "-") == 0)
        return r->send_count == 0;

    while (*p != '\0') {
        const char *end = strchr(p, ',');
        size_t piece = end != NULL ? (size_t)(end - p) : strlen(p);
        size_t n = from_hex_n(p, piece, want, sizeof(want));

        if (n == (size_t)-1 || index >= r->send_count || index >= REC_MAX_SENDS || r->send_length[index] != n
            || memcmp(r->sends[index], want, n) != 0)
            return 0;
        index++;
        p += piece;
        if (*p == ',')
            p++;
    }
    return index == r->send_count;
}

static int events_match(const recorder *r, const char *expected)
{
    size_t index = 0;
    const char *p = expected;

    if (strcmp(expected, "-") == 0)
        return r->event_count == 0;

    while (*p != '\0') {
        const char *end = strchr(p, ',');
        size_t piece = end != NULL ? (size_t)(end - p) : strlen(p);
        int ok = 0;

        if (index >= r->event_count || index >= REC_MAX_EVENTS)
            return 0;
        if (piece == 11 && strncmp(p, "established", 11) == 0)
            ok = r->events[index] == HALYARD_DGRAM_EVENT_PRELUDE_ESTABLISHED;
        else if (piece == 8 && strncmp(p, "opened:", 7) == 0)
            ok = r->events[index] == HALYARD_DGRAM_EVENT_CONNECTION_OPENED
                 && r->opened_by_peer[index] == (p[7] == '1');
        else if (piece == 6 && strncmp(p, "closed", 6) == 0)
            ok = r->events[index] == HALYARD_DGRAM_EVENT_PEER_CLOSED;
        else if (piece == 9 && strncmp(p, "unhandled", 9) == 0)
            ok = r->events[index] == HALYARD_DGRAM_EVENT_UNHANDLED;
        else if (piece > 5 && strncmp(p, "data:", 5) == 0) {
            uint8_t want[512];
            size_t n = from_hex_n(p + 5, piece - 5, want, sizeof(want));

            ok = r->events[index] == HALYARD_DGRAM_EVENT_DATA_RECEIVED && n != (size_t)-1
                 && r->data_length[index] == n && memcmp(r->data[index], want, n) == 0;
        }
        if (!ok)
            return 0;
        index++;
        p += piece;
        if (*p == ',')
            p++;
    }
    return index == r->event_count;
}

static void run_transcripts(const char *path)
{
    FILE *f = fopen(path, "r");
    static halyard_dgram_assoc assoc;
    static recorder rec;
    static uint8_t arg[1 << 16];
    char name[64] = "";
    int line_number = 0;
    int scenarios = 0;
    int steps = 0;

    if (f == NULL) {
        CHECK(0, "cannot open %s - run `dotnet run --project tools/Ripcord.ProtocolLab -- vectors`", path);
        return;
    }

    while (fgets(g_line, sizeof(g_line), f) != NULL) {
        char *fields[6];
        int count = 0;
        char *save = NULL;
        char *token;

        line_number++;
        if (g_line[0] == '#' || g_line[0] == '\n' || strncmp(g_line, "version", 7) == 0)
            continue;

        for (token = strtok_r(g_line, " \t\r\n", &save); token != NULL && count < 6;
             token = strtok_r(NULL, " \t\r\n", &save))
            fields[count++] = token;

        if (count == 6 && strcmp(fields[0], "assoc") == 0) {
            uint8_t local[20], peer[20], address[4];

            CHECK(from_hex(fields[2], local, 20) == 20 && memcmp(local, our_id(), 20) == 0
                      && from_hex(fields[3], peer, 20) == 20 && memcmp(peer, peer_id(), 20) == 0
                      && from_hex(fields[4], address, 4) == 4 && memcmp(address, k_peer_address, 4) == 0
                      && atoi(fields[5]) == (int)PEER_PORT,
                  "%s:%d: the transcript's association differs from the test's", path, line_number);
            snprintf(name, sizeof(name), "%s", fields[1]);
            new_assoc(&assoc, &rec);
            scenarios++;
            continue;
        }

        if (count == 6 && strcmp(fields[0], "step") == 0) {
            const char *op = fields[1];
            size_t arg_length = 0;

            rec_reset(&rec);
            if (strcmp(op, "send") == 0 || strcmp(op, "recv") == 0) {
                arg_length = from_hex(fields[2], arg, sizeof(arg));
                if (arg_length == (size_t)-1) {
                    CHECK(0, "%s:%d: bad hex", path, line_number);
                    continue;
                }
            }

            if (strcmp(op, "open") == 0)
                halyard_dgram_assoc_open(&assoc);
            else if (strcmp(op, "retry") == 0)
                halyard_dgram_assoc_retry(&assoc);
            else if (strcmp(op, "openconn") == 0)
                halyard_dgram_assoc_open_connection(&assoc, (halyard_dgram_addressing)atoi(fields[2]));
            else if (strcmp(op, "reopen") == 0)
                halyard_dgram_assoc_reopen_connection(&assoc);
            else if (strcmp(op, "closeconn") == 0)
                halyard_dgram_assoc_close_connection(&assoc);
            else if (strcmp(op, "send") == 0)
                halyard_dgram_assoc_send(&assoc, arg, arg_length);
            else if (strcmp(op, "recv") == 0)
                halyard_dgram_assoc_on_datagram(&assoc, arg, arg_length);
            else if (strcmp(op, "clear") == 0)
                halyard_dgram_assoc_clear_inbound(&assoc);
            else {
                CHECK(0, "%s:%d: unknown op %s", path, line_number, op);
                continue;
            }

            CHECK(strcmp(halyard_dgram_phase_name(assoc.phase), fields[3]) == 0,
                  "%s step %d (%s, line %d): phase %s, the reference says %s", name, steps, op, line_number,
                  halyard_dgram_phase_name(assoc.phase), fields[3]);
            CHECK(sends_match(&rec, fields[4]), "%s step %d (%s, line %d): sent %lu datagram(s) differing from the reference",
                  name, steps, op, line_number, (unsigned long)rec.send_count);
            CHECK(events_match(&rec, fields[5]), "%s step %d (%s, line %d): events differ from the reference", name,
                  steps, op, line_number);
            steps++;
            continue;
        }

        CHECK(0, "%s:%d: unrecognised line", path, line_number);
    }
    fclose(f);

    CHECK(scenarios >= 3 && steps >= 50, "the transcript file is short: %d scenarios, %d steps", scenarios, steps);
    printf("  replayed %d reference steps across %d scenarios\n", steps, scenarios);
}

/* ==== 2a. framing (HalyardControlChunkTests) ========================================================= */

static void test_chunks(void)
{
    uint8_t wire[4096];
    halyard_dgram_chunk chunk;
    size_t consumed;
    size_t n;
    const uint8_t body[] = { 1, 2, 3, 4, 5 };

    /* Chunk_RoundTrips */
    n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, body, sizeof(body), 3);
    CHECK(halyard_dgram_chunk_read(wire, n, &chunk, &consumed) && chunk.type == HALYARD_DGRAM_CHUNK_DATA
              && chunk.flags == 0x30 && chunk.body_length == 5 && memcmp(chunk.body, body, 5) == 0 && consumed == n,
          "a chunk round-trips");

    /* Chunk_WritesThePairedWordCount */
    CHECK(chunk.word_count == 3 && chunk.source_port == HALYARD_DGRAM_CONTROL_PORT
              && chunk.destination_port == HALYARD_DGRAM_CONTROL_PORT,
          "the paired word count carries the control port twice");

    /* Chunk_WordCountOfTwo_CarriesOnePortUsedForBothEnds */
    {
        const uint8_t two[] = { 0x80, 0x06, 0x24, 0x4F, 0x02, 0x30 };

        CHECK(halyard_dgram_chunk_read(two, sizeof(two), &chunk, &consumed) && chunk.word_count == 2
                  && chunk.type == HALYARD_DGRAM_CHUNK_DATA && chunk.flags == 0x30
                  && chunk.destination_port == HALYARD_DGRAM_CONTROL_PORT && chunk.source_port == chunk.destination_port
                  && consumed == 6,
              "a word count of 2 carries one port used for both ends");
    }

    /* Chunk_WordCountOfOne_CarriesNoPortAtAll */
    {
        const uint8_t one[] = { 0x40, 0x05, 0x02, 0x30, 0x77 };

        CHECK(halyard_dgram_chunk_read(one, sizeof(one), &chunk, &consumed) && chunk.word_count == 1
                  && chunk.type == HALYARD_DGRAM_CHUNK_DATA && chunk.body_length == 1 && chunk.body[0] == 0x77
                  && consumed == 5,
              "a word count of 1 carries no port");
    }

    /* Chunk_PortWordsAreReadThrough_NotRequiredToBeTheControlPort */
    {
        const uint8_t ports[] = { 0xC0, 0x08, 0x11, 0x22, 0x33, 0x44, 0x02, 0x30 };

        CHECK(halyard_dgram_chunk_read(ports, sizeof(ports), &chunk, &consumed) && chunk.source_port == 0x1122
                  && chunk.destination_port == 0x3344,
              "port words are read through");
    }

    /* Chunk_ReservedLengthBits_AreMaskedAwayRatherThanRead */
    {
        const uint8_t two_bytes[] = { 1, 2 };

        n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, two_bytes, 2, 3);
        wire[0] |= 0x38;
        CHECK(halyard_dgram_chunk_read(wire, n, &chunk, &consumed) && consumed == n && chunk.body_length == 2
                  && chunk.body[0] == 1 && chunk.body[1] == 2,
              "reserved length bits are masked away");
    }

    /* Chunk_LengthFieldCountsItsOwnPrefix */
    {
        const uint8_t ab[] = { 0xAA, 0xBB };

        n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_ACK, 0x30, ab, 2, 3);
        CHECK(n == 10 && wire[0] == 0xC0 && wire[1] == 0x0A, "the length counts its own prefix");
    }

    /* Chunk_CarriesTheControlPortAtBothWords */
    n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_HELLO, 0x30, NULL, 0, 3);
    CHECK(n == 8 && wire[2] == 0x24 && wire[3] == 0x4F && wire[4] == 0x24 && wire[5] == 0x4F,
          "both port words are 9295");

    /* Chunk_LongBody_SetsOnlyTheTopTwoBitsOfTheLength */
    {
        static uint8_t zeros[2048];

        n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, zeros, 278, 3);
        CHECK(n == 286 && wire[0] == 0xC1 && wire[1] == 0x1E, "a 286-byte chunk begins C1 1E");

        /* Chunk_TooLongForTheLengthField_Throws: 2047 fits, one more does not. */
        n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, zeros, 2047 - 8, 3);
        CHECK(n == HALYARD_DGRAM_MAX_CHUNK_LENGTH && halyard_dgram_chunk_read(wire, n, &chunk, &consumed)
                  && consumed == n,
              "the longest chunk the length field expresses round-trips");
        CHECK(halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, zeros, 2047 - 7, 3) == 0,
              "one byte longer is refused");
        CHECK(halyard_dgram_chunk_write(wire, 7, HALYARD_DGRAM_CHUNK_DATA, 0x30, NULL, 0, 3) == 0,
              "a buffer too small is refused");
        CHECK(halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, NULL, 0, 0) == 0
                  && halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, NULL, 0, 4) == 0,
              "word counts outside 1..3 are refused");
        CHECK(halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, zeros, (size_t)-1, 3) == 0,
              "a body length near SIZE_MAX cannot wrap into a short chunk");
    }

    /* ReadAll_SplitsConcatenatedChunks */
    {
        const uint8_t ack_body[] = { 0x2B, 0xFA, 0xA6, 0x5F };
        size_t a = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_ACK, 0x30, ack_body, 4, 3);
        size_t d = halyard_dgram_chunk_write(wire + a, sizeof(wire) - a, HALYARD_DGRAM_CHUNK_DATA, 0x30,
                                             (const uint8_t *)"POST /", 6, 3);
        size_t offset = 0;
        halyard_dgram_chunk first, second;
        int got1 = halyard_dgram_chunk_next(wire, a + d, &offset, &first);
        int got2 = halyard_dgram_chunk_next(wire, a + d, &offset, &second);
        int got3 = halyard_dgram_chunk_next(wire, a + d, &offset, &chunk);

        CHECK(got1 && got2 && !got3 && first.type == HALYARD_DGRAM_CHUNK_ACK && second.type == HALYARD_DGRAM_CHUNK_DATA
                  && second.body_length == 6 && memcmp(second.body, "POST /", 6) == 0,
              "concatenated chunks split");

        /* ReadAll_KeepsTheChunksItAlreadyParsed_WhenTrailingBytesAreRubbish */
        {
            const uint8_t nines[] = { 9, 9 };

            n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, nines, 2, 3);
            wire[n] = 0x00;
            wire[n + 1] = 0x01;
            wire[n + 2] = 0x02;
            offset = 0;
            got1 = halyard_dgram_chunk_next(wire, n + 3, &offset, &first);
            got2 = halyard_dgram_chunk_next(wire, n + 3, &offset, &second);
            CHECK(got1 && !got2 && first.body_length == 2 && first.body[0] == 9, "trailing rubbish keeps the good chunk");
        }
    }

    /* Chunk_Malformed_IsRejectedRatherThanGuessedAt */
    {
        static const uint8_t bad[6][8] = {
            { 0x00, 0x08, 0x24, 0x4F, 0x24, 0x4F, 0x02, 0x30 },
            { 0xC0, 0x04, 0x24, 0x4F, 0x24, 0x4F, 0x02, 0x30 },
            { 0xC0, 0x07, 0x24, 0x4F, 0x24, 0x4F, 0x02, 0x30 },
            { 0xC0, 0xFF, 0x24, 0x4F, 0x24, 0x4F, 0x02, 0x30 },
            { 0xC0, 0x08, 0x24, 0x4F },
            { 0xC0 },
        };
        static const size_t bad_length[6] = { 8, 8, 8, 8, 4, 1 };
        int i;

        for (i = 0; i < 6; i++) {
            size_t offset = 0;

            CHECK(!halyard_dgram_chunk_read(bad[i], bad_length[i], &chunk, &consumed)
                      && !halyard_dgram_chunk_next(bad[i], bad_length[i], &offset, &chunk),
                  "malformed chunk %d is rejected", i);
        }
        CHECK(!halyard_dgram_chunk_read(bad[0], 0, &chunk, &consumed), "an empty datagram is not a chunk");
    }
}

/* ==== 2b. the prelude ================================================================================ */

static void test_prelude(void)
{
    halyard_dgram_prelude p, parsed;
    uint8_t wire[128];
    uint8_t chunk_wire[128];
    static const uint8_t zeros[80];
    size_t n;

    /* Prelude_RoundTrips */
    memset(&p, 0, sizeof(p));
    p.type = HALYARD_DGRAM_PRELUDE_INIT;
    memcpy(p.sender_id, our_id(), 20);
    memcpy(p.peer_id, peer_id(), 20);
    p.tag_pair = 0x000168B9u;
    p.request_word = 0x19;
    n = halyard_dgram_prelude_write(&p, wire, sizeof(wire));
    CHECK(n == 88 && halyard_dgram_prelude_parse(wire, n, &parsed) && parsed.type == p.type
              && memcmp(parsed.sender_id, our_id(), 20) == 0 && memcmp(parsed.peer_id, peer_id(), 20) == 0
              && parsed.tag_pair == p.tag_pair && parsed.request_word == p.request_word,
          "a prelude round-trips");

    /* Prelude_TypeIsLittleEndian */
    CHECK(wire[0] == 0x06 && wire[1] == 0 && wire[2] == 0 && wire[3] == 0, "the type is little-endian");

    /* Prelude_SwappedTagPair_ExchangesTheHalves */
    CHECK(halyard_dgram_swap_halves(0x000168B9u) == 0x68B90001u, "the tag pair halves swap");

    /* Prelude_WrongLength_IsRejected / Prelude_UnknownType_IsRejected */
    memset(wire, 0, sizeof(wire));
    wire[0] = 6;
    CHECK(!halyard_dgram_prelude_parse(wire, 87, &parsed) && !halyard_dgram_prelude_parse(wire, 89, &parsed),
          "wrong lengths are rejected");
    wire[0] = 5;
    CHECK(!halyard_dgram_prelude_parse(wire, 88, &parsed), "an unknown type is rejected");

    /* Prelude_AndChunk_AreNotConfusableForEachOther */
    n = halyard_dgram_chunk_write(chunk_wire, sizeof(chunk_wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, zeros, 80, 3);
    CHECK(n == 88 && !halyard_dgram_prelude_parse(chunk_wire, n, &parsed), "an 88-byte chunk is not a prelude");
    memset(&p, 0, sizeof(p));
    p.type = HALYARD_DGRAM_PRELUDE_INIT;
    n = halyard_dgram_prelude_write(&p, wire, sizeof(wire));
    {
        halyard_dgram_chunk chunk;
        size_t consumed;

        CHECK(!halyard_dgram_chunk_read(wire, n, &chunk, &consumed), "a prelude is not a chunk");
    }
    CHECK(halyard_dgram_prelude_write(&p, wire, 87) == 0, "a short buffer is refused");

    /* The reflected tail: STUN's XOR-MAPPED trick keyed on the tag pair. Worked by hand from the spec. */
    {
        uint8_t tail[8];
        const uint8_t address[4] = { 192, 0, 2, 7 };

        halyard_dgram_reflect_peer_endpoint(address, 9303, 0x77770001u, tail);
        CHECK(tail[0] == (192 ^ 0x77) && tail[1] == (0 ^ 0x77) && tail[2] == (2 ^ 0x00) && tail[3] == (7 ^ 0x01)
                  && ((tail[4] << 8) | tail[5]) == (9303 ^ 0x7777) && tail[6] == 0 && tail[7] == 0,
              "the tail reflects the peer endpoint XOR the tag pair");
    }
}

/* ==== 2c. the association's rules, by name (HalyardControlAssociationTests) ========================== */

static size_t peer_prelude(uint8_t *out, uint32_t type, uint32_t tag_pair, uint32_t token)
{
    halyard_dgram_prelude p;

    memset(&p, 0, sizeof(p));
    p.type = type;
    memcpy(p.sender_id, peer_id(), 20);
    memcpy(p.peer_id, our_id(), 20);
    p.tag_pair = tag_pair;
    p.request_word = type == HALYARD_DGRAM_PRELUDE_INIT ? 0x19u : 0u;
    p.token = token;
    return halyard_dgram_prelude_write(&p, out, 88);
}

static void established(halyard_dgram_assoc *a, recorder *r)
{
    uint8_t d[88];

    new_assoc(a, r);
    halyard_dgram_assoc_on_datagram(a, d, peer_prelude(d, HALYARD_DGRAM_PRELUDE_INIT, 0x00017777u, 0x11223344u));
    halyard_dgram_assoc_on_datagram(a, d, peer_prelude(d, HALYARD_DGRAM_PRELUDE_COOKIE_ECHO, 0x00017777u, 0));
    rec_reset(r);
}

static void test_association_rules(void)
{
    static halyard_dgram_assoc a;
    static recorder r;
    halyard_dgram_prelude p;
    uint8_t d[4096];
    size_t n;

    /* Open_AnnouncesUsWithTheInitiatorsRequestWord / OurInit_CarriesNoReflectedEndpoint */
    new_assoc(&a, &r);
    halyard_dgram_assoc_open(&a);
    CHECK(r.send_count == 1 && halyard_dgram_prelude_parse(r.sends[0], r.send_length[0], &p)
              && p.type == HALYARD_DGRAM_PRELUDE_INIT && p.request_word == 0x40 && p.token != 0
              && memcmp(p.tail, "\0\0\0\0\0\0\0\0", 8) == 0 && a.phase == HALYARD_DGRAM_PHASE_HANDSHAKING,
          "open announces us as the initiator, with a zero tail");

    /* AsResponder_WeAnswerWithTheTagPairExchangedAndAZeroRequestWord, ...AlsoEchoTheirToken,
     * OurEcho_ReflectsThePeersOwnEndpoint_RatherThanAZeroTail */
    new_assoc(&a, &r);
    halyard_dgram_assoc_on_datagram(&a, d, peer_prelude(d, HALYARD_DGRAM_PRELUDE_INIT, 0x00017777u, 0x11223344u));
    {
        halyard_dgram_prelude echo;
        uint8_t tail[8];

        halyard_dgram_reflect_peer_endpoint(k_peer_address, PEER_PORT, 0x77770001u, tail);
        CHECK(r.send_count == 2 && halyard_dgram_prelude_parse(r.sends[0], r.send_length[0], &p)
                  && halyard_dgram_prelude_parse(r.sends[1], r.send_length[1], &echo)
                  && p.type == HALYARD_DGRAM_PRELUDE_INIT && p.tag_pair == 0x77770001u && p.request_word == 0
                  && echo.type == HALYARD_DGRAM_PRELUDE_COOKIE_ECHO && echo.token == 0x11223344u
                  && echo.tag_pair == 0x77770001u && memcmp(echo.tail, tail, 8) == 0,
              "a responder answers in the responder's shape and echoes with a reflected tail");
    }

    /* EveryPeerInit_IsEchoed_NotJustTheFirst / AnEchoedProbe_DoesNotReopenTheAssociation */
    rec_reset(&r);
    halyard_dgram_assoc_on_datagram(&a, d, peer_prelude(d, HALYARD_DGRAM_PRELUDE_INIT, 0x00017777u, 0x11229999u));
    CHECK(r.send_count == 1 && halyard_dgram_prelude_parse(r.sends[0], r.send_length[0], &p)
              && p.type == HALYARD_DGRAM_PRELUDE_COOKIE_ECHO && p.token == 0x11229999u,
          "every probe is echoed with its own token, and not re-answered with an Init");

    /* OpenConnection_BeforeThePreludeIsEstablished_DoesNothing / Send_BeforeAConnectionIsOpen */
    new_assoc(&a, &r);
    CHECK(halyard_dgram_assoc_open_connection(&a, HALYARD_DGRAM_ADDRESS_PORT_PAIR) == HALYARD_DGRAM_OK
              && r.send_count == 0,
          "opening a connection before the prelude does nothing");
    established(&a, &r);
    CHECK(halyard_dgram_assoc_send(&a, (const uint8_t *)"POST /x", 7) == HALYARD_DGRAM_NOT_CONNECTED
              && r.send_count == 0,
          "sending before a connection is open sends nothing, and says so");

    /* OpenConnection_SendsAHelloCarryingTheCapabilityBlockAndWindow */
    halyard_dgram_assoc_open_connection(&a, HALYARD_DGRAM_ADDRESS_PORT_PAIR);
    {
        halyard_dgram_chunk hello;
        size_t consumed;
        static const uint8_t cap[6] = { 0x0B, 0x01, 0x01, 0x00, 0x01, 0x00 };

        CHECK(r.send_count == 1 && halyard_dgram_chunk_read(r.sends[0], r.send_length[0], &hello, &consumed)
                  && hello.type == HALYARD_DGRAM_CHUNK_HELLO && hello.body_length == 14
                  && memcmp(hello.body + 2, cap, 6) == 0 && hello.body[12] == 0x05 && hello.body[13] == 0x82,
              "the hello carries the capability block and window");
    }

    /* EachPayload_GetsItsOwnSequence, and the ack-in-front shape */
    {
        const uint8_t accept[12] = { 0xA6, 0x5E, 0x2B, 0xFA };
        halyard_dgram_chunk c1, c2;
        size_t offset;
        uint16_t seqs[3];
        int i;

        n = halyard_dgram_chunk_write(d, sizeof(d), HALYARD_DGRAM_CHUNK_ACCEPT, 0x30, accept, 12, 3);
        halyard_dgram_assoc_on_datagram(&a, d, n);
        CHECK(a.phase == HALYARD_DGRAM_PHASE_CONNECTED, "an accept opens the connection");
        for (i = 0; i < 3; i++) {
            uint8_t payload = (uint8_t)(i + 1);

            rec_reset(&r);
            halyard_dgram_assoc_send(&a, &payload, 1);
            offset = 0;
            CHECK(r.send_count == 1 && halyard_dgram_chunk_next(r.sends[0], r.send_length[0], &offset, &c1)
                      && halyard_dgram_chunk_next(r.sends[0], r.send_length[0], &offset, &c2)
                      && c1.type == HALYARD_DGRAM_CHUNK_ACK && c2.type == HALYARD_DGRAM_CHUNK_DATA
                      && offset == r.send_length[0],
                  "a payload goes out as ack + data in one datagram");
            seqs[i] = (uint16_t)((c2.body[0] << 8) | c2.body[1]);
        }
        CHECK(seqs[1] == (uint16_t)(seqs[0] + 1) && seqs[2] == (uint16_t)(seqs[0] + 2), "each payload gets its own sequence");
    }

    /* C only: the payload bound, and entropy failures that change nothing. */
    {
        static uint8_t big[HALYARD_DGRAM_MAX_PAYLOAD + 1];

        rec_reset(&r);
        CHECK(halyard_dgram_assoc_send(&a, big, sizeof(big)) == HALYARD_DGRAM_TOO_LONG && r.send_count == 0,
              "a payload over one chunk is refused, not truncated");
        halyard_dgram_status st = halyard_dgram_assoc_send(&a, big, HALYARD_DGRAM_MAX_PAYLOAD);
        CHECK(st == HALYARD_DGRAM_OK && r.send_count == 1
                  && r.send_length[0] == HALYARD_DGRAM_MAX_DATAGRAM,
              "the largest payload fills one chunk exactly");
    }
    new_assoc(&a, &r);
    r.random_fails = 1;
    CHECK(halyard_dgram_assoc_open(&a) == HALYARD_DGRAM_NO_ENTROPY && r.send_count == 0
              && a.phase == HALYARD_DGRAM_PHASE_IDLE,
          "an entropy failure sends nothing and changes nothing");
    CHECK(halyard_dgram_assoc_on_datagram(&a, d, peer_prelude(d, HALYARD_DGRAM_PRELUDE_INIT, 0x00017777u, 1))
                  == HALYARD_DGRAM_NO_ENTROPY
              && r.send_count == 0 && a.phase == HALYARD_DGRAM_PHASE_IDLE,
          "a responder that cannot draw a token does not answer");

    /* C only: the inbound bound refuses (and does not acknowledge) what it cannot hold. */
    established(&a, &r);
    halyard_dgram_assoc_open_connection(&a, HALYARD_DGRAM_ADDRESS_PORT_PAIR);
    {
        const uint8_t accept[12] = { 0x00, 0x10, 0x00, 0x01 };
        static uint8_t body[2 + 2000];
        int i;

        n = halyard_dgram_chunk_write(d, sizeof(d), HALYARD_DGRAM_CHUNK_ACCEPT, 0x30, accept, 12, 3);
        halyard_dgram_assoc_on_datagram(&a, d, n);
        for (i = 0; i < 9; i++) {
            body[0] = 0x00;
            body[1] = (uint8_t)(0x11 + i);
            rec_reset(&r);
            n = halyard_dgram_chunk_write(d, sizeof(d), HALYARD_DGRAM_CHUNK_DATA, 0x30, body, sizeof(body), 3);
            halyard_dgram_assoc_on_datagram(&a, d, n);
        }
        CHECK(a.inbound_length == 8 * 2000u && r.send_count == 0 && r.event_count == 1
                  && r.events[0] == HALYARD_DGRAM_EVENT_UNHANDLED,
              "a payload that does not fit is reported and not acknowledged");
        halyard_dgram_assoc_consume_inbound(&a, 2000);
        rec_reset(&r);
        halyard_dgram_assoc_on_datagram(&a, d, n);
        CHECK(a.inbound_length == 8 * 2000u && r.send_count == 1 && r.events[0] == HALYARD_DGRAM_EVENT_DATA_RECEIVED,
              "the retransmission is taken once there is room");
    }

    /* C only: a cookie whose echo cannot fit one chunk is reported, where .NET's encoder throws. */
    established(&a, &r);
    halyard_dgram_assoc_open_connection(&a, HALYARD_DGRAM_ADDRESS_PORT_PAIR);
    {
        static uint8_t cookie[2039];

        rec_reset(&r);
        n = halyard_dgram_chunk_write(d, sizeof(d), HALYARD_DGRAM_CHUNK_COOKIE, 0x00, cookie, sizeof(cookie), 3);
        halyard_dgram_assoc_on_datagram(&a, d, n);
        CHECK(n == 2047 && r.send_count == 0 && r.event_count == 1 && r.events[0] == HALYARD_DGRAM_EVENT_UNHANDLED,
              "an unechoable cookie is reported");
    }

    CHECK(halyard_dgram_assoc_init(&a, NULL, our_id(), peer_id(), k_peer_address, 1) == HALYARD_DGRAM_BAD_ARGUMENT,
          "init refuses NULL callbacks");
}

/* ==== 2d. HTTP completeness ========================================================================== */

static int complete(const char *text)
{
    return halyard_dgram_http_complete((const uint8_t *)text, strlen(text));
}

static void test_http_complete(void)
{
    CHECK(!complete("HTTP/1.1 200 OK\r\nContent-Length: 4\r\n"), "no terminator: incomplete");
    CHECK(!complete("HTTP/1.1 200 OK\r\nContent-Length: 4\r\n\r\nabc"), "short body: incomplete");
    CHECK(complete("HTTP/1.1 200 OK\r\nContent-Length: 4\r\n\r\nabcd"), "full body: complete");
    CHECK(complete("HTTP/1.1 200 OK\r\ncontent-length :  4 \r\n\r\nabcdef"), "names match case-insensitively and trimmed");
    CHECK(complete("HTTP/1.1 200 OK\r\nRP-Version: 1.0\r\n\r\n"), "no Content-Length: complete");
    CHECK(!complete("HTTP/1.1 200 OK\r\nContent-Length: x\r\nContent-Length: 2\r\n\r\n"),
          "an unparseable value is skipped for the next one");
    CHECK(complete("HTTP/1.1 200 OK\r\nContent-Length: 99999999999\r\n\r\n"), "an out-of-range value does not parse");
    CHECK(complete("HTTP/1.1 200 OK\r\nContent-Length: -1\r\n\r\n"), "a negative length is always met, as in .NET");
    CHECK(complete("\r\n\r\n") && !complete("\r\n\r") && !complete(""), "edge lengths");
}

/* ==== 2e. the pump, against scripted consoles ========================================================= */

#define QUEUE_MAX 64

/*
 * A console that answers each step as it arrives (so a channel that sent the steps out of order would
 * stall rather than accidentally pass). The two .NET suites' consoles, in one: `session_mode` closes each
 * connection after answering an HTTP request, as a real console does, and pushes queued control frames
 * once the client sends one of its own.
 */
typedef struct {
    size_t count;
    size_t head;
    size_t length[QUEUE_MAX];
    uint8_t data[QUEUE_MAX][2100];

    int swallow_inits;
    int session_mode;
    int inits;
    int hellos;
    int requests;
    char request_lines[4][64];
    uint16_t sequence;
    size_t frame_count;
    uint8_t frames[4][64];
    size_t frame_length[4];
} scripted_console;

static void enqueue(scripted_console *c, const uint8_t *data, size_t length)
{
    size_t slot = (c->head + c->count) % QUEUE_MAX;

    if (c->count < QUEUE_MAX && length <= sizeof(c->data[0])) {
        memcpy(c->data[slot], data, length);
        c->length[slot] = length;
        c->count++;
    }
}

static void push_data(scripted_console *c, const uint8_t *payload, size_t length)
{
    uint8_t body[1024];
    uint8_t wire[1100];
    size_t n;

    c->sequence++;
    body[0] = (uint8_t)(c->sequence >> 8);
    body[1] = (uint8_t)c->sequence;
    memcpy(body + 2, payload, length);
    n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_DATA, 0x30, body, length + 2, 3);
    enqueue(c, wire, n);
}

static int console_send(void *ctx, const uint8_t *datagram, size_t length)
{
    scripted_console *c = (scripted_console *)ctx;
    halyard_dgram_prelude p;
    halyard_dgram_chunk chunk;
    size_t offset = 0;
    uint8_t wire[256];
    size_t n;

    if (halyard_dgram_prelude_parse(datagram, length, &p)) {
        if (p.type != HALYARD_DGRAM_PRELUDE_INIT)
            return 1;
        c->inits++;
        if (c->swallow_inits > 0) {
            c->swallow_inits--;
            return 1;
        }
        /* Answer, then echo - the shape a real console uses. */
        enqueue(c, wire, peer_prelude(wire, HALYARD_DGRAM_PRELUDE_INIT, halyard_dgram_swap_halves(p.tag_pair), 0x01B9ACBEu));
        enqueue(c, wire, peer_prelude(wire, HALYARD_DGRAM_PRELUDE_COOKIE_ECHO, p.tag_pair, p.token));
        return 1;
    }

    while (halyard_dgram_chunk_next(datagram, length, &offset, &chunk)) {
        if (chunk.type == HALYARD_DGRAM_CHUNK_HELLO) {
            uint8_t cookie[42];
            int i;

            c->hellos++;
            for (i = 0; i < 42; i++)
                cookie[i] = (uint8_t)(0xE0 + i);
            n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_COOKIE, 0x00, cookie, 42, 3);
            enqueue(c, wire, n);
        } else if (chunk.type == HALYARD_DGRAM_CHUNK_HELLO_ECHO) {
            uint16_t hello_seq = (uint16_t)((chunk.body[0] << 8) | chunk.body[1]);
            uint8_t accept[12] = { 0 };

            accept[0] = (uint8_t)(c->sequence >> 8);
            accept[1] = (uint8_t)c->sequence;
            accept[2] = (uint8_t)((hello_seq + 1) >> 8);
            accept[3] = (uint8_t)(hello_seq + 1);
            n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_ACCEPT, 0x30, accept, 12, 3);
            enqueue(c, wire, n);
        } else if (chunk.type == HALYARD_DGRAM_CHUNK_DATA && chunk.body_length > 2) {
            const uint8_t *payload = chunk.body + 2;
            size_t payload_length = chunk.body_length - 2;
            int is_http = (payload_length >= 4 && memcmp(payload, "GET ", 4) == 0)
                          || (payload_length >= 5 && memcmp(payload, "POST ", 5) == 0);

            if (!c->session_mode) {
                static const char response[] = "HTTP/1.1 200 OK\r\nContent-Length: 4\r\n\r\nabcd";

                push_data(c, (const uint8_t *)response, sizeof(response) - 1);
            } else if (!is_http) {
                size_t i;

                for (i = 0; i < c->frame_count; i++)
                    push_data(c, c->frames[i], c->frame_length[i]);
                c->frame_count = 0;
            } else {
                static const char response[] = "HTTP/1.1 200 OK\r\nRP-Version: 1.0\r\nContent-Length: 0\r\n\r\n";
                static const uint8_t close_body[8];
                size_t line = 0;

                while (line < payload_length && payload[line] != '\r' && line < 63)
                    line++;
                if (c->requests < 4) {
                    memcpy(c->request_lines[c->requests], payload, line);
                    c->request_lines[c->requests][line] = '\0';
                }
                c->requests++;
                push_data(c, (const uint8_t *)response, sizeof(response) - 1);

                /* ...and tear the connection down, which is what makes the next request need a new one. */
                n = halyard_dgram_chunk_write(wire, sizeof(wire), HALYARD_DGRAM_CHUNK_CLOSE, 0x00, close_body, 8, 3);
                enqueue(c, wire, n);
            }
        }
    }
    return 1;
}

static long console_receive(void *ctx, uint8_t *buffer, size_t capacity)
{
    scripted_console *c = (scripted_console *)ctx;
    size_t length;

    if (c->count == 0)
        return 0;
    length = c->length[c->head];
    if (length > capacity)
        length = capacity;
    memcpy(buffer, c->data[c->head], length);
    c->head = (c->head + 1) % QUEUE_MAX;
    c->count--;
    return (long)length;
}

static void quick(halyard_dgram_options *o, uint32_t stage_ms)
{
    halyard_dgram_options_default(o);
    o->receive_timeout_ms = 20;
    o->stage_timeout_ms = stage_ms;
}

static void open_scripted(halyard_dgram_channel *ch, scripted_console *console, uint32_t stage_ms)
{
    halyard_dgram_transport t;
    halyard_dgram_options o;

    console->sequence = 0xA65E;
    t.send = console_send;
    t.receive = console_receive;
    t.ctx = console;
    quick(&o, stage_ms);
    halyard_dgram_channel_init(ch, &t, k_peer_address, PEER_PORT, our_id(), peer_id(), &o);
}

static void test_channel(void)
{
    static halyard_dgram_channel ch;
    static scripted_console console;
    uint8_t response[512];
    size_t response_length;
    static const char rgst[] = "POST /sie/ps5/rp/sess/rgst HTTP/1.1\r\n\r\n";
    uint64_t start;

    /* Exchange_CompletesTheWholeCycle_AndReturnsTheHttpResponse */
    memset(&console, 0, sizeof(console));
    open_scripted(&ch, &console, 2000);
    CHECK(halyard_dgram_channel_exchange(&ch, (const uint8_t *)rgst, sizeof(rgst) - 1, response, sizeof(response),
                                         &response_length) == HALYARD_DGRAM_CHANNEL_OK
              && response_length > 15 && memcmp(response, "HTTP/1.1 200 OK", 15) == 0
              && halyard_dgram_channel_phase(&ch) == HALYARD_DGRAM_PHASE_CONNECTED,
          "an exchange completes the whole cycle");

    /* Exchange_RetriesTheOpeningInit_WhenTheFirstProbesGoUnanswered */
    memset(&console, 0, sizeof(console));
    console.swallow_inits = 2;
    open_scripted(&ch, &console, 2000);
    CHECK(halyard_dgram_channel_exchange(&ch, (const uint8_t *)"GET / HTTP/1.1\r\n\r\n", 18, response,
                                         sizeof(response), &response_length) == HALYARD_DGRAM_CHANNEL_OK
              && console.inits == 3,
          "the opening Init is retried on quiet windows (%d sent)", console.inits);

    /* Exchange_UnansweredPrelude_ReportsSomethingActionable (the text goes to the log in C) */
    memset(&console, 0, sizeof(console));
    console.swallow_inits = 1 << 30;
    open_scripted(&ch, &console, 200);
    start = rc_time_ms();
    CHECK(halyard_dgram_channel_exchange(&ch, (const uint8_t *)"GET / HTTP/1.1\r\n\r\n", 18, response,
                                         sizeof(response), &response_length) == HALYARD_DGRAM_CHANNEL_TIMEOUT
              && rc_time_ms() - start < 1000,
          "an unanswered prelude times out at the stage deadline");

    /* A response larger than the caller's buffer is refused rather than truncated. */
    memset(&console, 0, sizeof(console));
    open_scripted(&ch, &console, 2000);
    CHECK(halyard_dgram_channel_exchange(&ch, (const uint8_t *)rgst, sizeof(rgst) - 1, response, 8,
                                         &response_length) == HALYARD_DGRAM_CHANNEL_BUFFER_TOO_SMALL,
          "a too-small response buffer is reported");

    /* InitAndCtrl_RunAsSeparateConnectionsOverOneAssociation */
    {
        static const char init[] = "GET /sie/ps5/rp/sess/init HTTP/1.1\r\n\r\n";
        static const char ctrl[] = "GET /sie/ps5/rp/sess/ctrl HTTP/1.1\r\n\r\n";
        uint8_t got[256];
        size_t got_length;
        int ok = 1;

        memset(&console, 0, sizeof(console));
        console.session_mode = 1;
        open_scripted(&ch, &console, 2000);

        ok &= halyard_dgram_channel_establish(&ch) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_open_connection(&ch) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_send_bytes(&ch, (const uint8_t *)init, sizeof(init) - 1) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_receive_bytes(&ch, got, sizeof(got), &got_length) == HALYARD_DGRAM_CHANNEL_OK
              && got_length > 15 && memcmp(got, "HTTP/1.1 200 OK", 15) == 0;

        ok &= halyard_dgram_channel_establish(&ch) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_open_connection(&ch) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_send_bytes(&ch, (const uint8_t *)ctrl, sizeof(ctrl) - 1) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_receive_bytes(&ch, got, sizeof(got), &got_length) == HALYARD_DGRAM_CHANNEL_OK;
        ok &= halyard_dgram_channel_receive_bytes(&ch, got, sizeof(got), &got_length)
              == HALYARD_DGRAM_CHANNEL_PEER_CLOSED;

        CHECK(ok && console.requests == 2 && strcmp(console.request_lines[0], "GET /sie/ps5/rp/sess/init HTTP/1.1") == 0
                  && strcmp(console.request_lines[1], "GET /sie/ps5/rp/sess/ctrl HTTP/1.1") == 0
                  && console.hellos == 2 && console.inits == 1,
              "init and ctrl run as two connections over one association (hellos %d, inits %d)", console.hellos,
              console.inits);
    }

    /* ControlFrames_FlowOnTheConnectionThatServedCtrl. The frames are opaque bytes to this layer, so they
     * are written by hand: an 8-byte control-frame header with the heartbeat request and reply types. */
    {
        static const uint8_t heartbeat_req[8] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x00 };
        static const uint8_t heartbeat_rep[8] = { 0x00, 0x00, 0x00, 0x00, 0x01, 0xFE, 0x00, 0x00 };
        uint8_t got[256];
        size_t got_length;

        memset(&console, 0, sizeof(console));
        console.session_mode = 1;
        open_scripted(&ch, &console, 2000);
        memcpy(console.frames[0], heartbeat_req, 8);
        console.frame_length[0] = 8;
        console.frame_count = 1;

        halyard_dgram_channel_establish(&ch);
        halyard_dgram_channel_open_connection(&ch);
        halyard_dgram_channel_send_bytes(&ch, heartbeat_rep, sizeof(heartbeat_rep));
        CHECK(halyard_dgram_channel_receive_bytes(&ch, got, sizeof(got), &got_length) == HALYARD_DGRAM_CHANNEL_OK
                  && got_length == 8 && memcmp(got, heartbeat_req, 8) == 0,
              "control frames flow on the connection that served ctrl");

        /* C only: poll() answers a probe without blocking, and reports no data. */
        {
            uint8_t probe[88];
            int data = -1;
            int closed = -1;
            size_t before_inits = (size_t)console.inits;

            enqueue(&console, probe,
                    peer_prelude(probe, HALYARD_DGRAM_PRELUDE_INIT, halyard_dgram_swap_halves(ch.assoc.tag_pair), 7));
            CHECK(halyard_dgram_channel_poll(&ch, &data, &closed) == HALYARD_DGRAM_CHANNEL_OK && data == 0
                      && closed == 0 && (size_t)console.inits == before_inits
                      && halyard_dgram_channel_phase(&ch) == HALYARD_DGRAM_PHASE_CONNECTED,
                  "poll echoes a probe and leaves the connection open");
        }
    }

    /* SendingBeforeConnecting_SaysSoRatherThanHanging */
    memset(&console, 0, sizeof(console));
    open_scripted(&ch, &console, 2000);
    CHECK(halyard_dgram_channel_send_bytes(&ch, (const uint8_t *)"x", 1) == HALYARD_DGRAM_CHANNEL_NOT_CONNECTED,
          "sending before connecting says so");
}

/* The UDP transport, on loopback: Begin puts exactly one 88-byte Init on the wire, to the named peer. */
static void test_udp_transport(void)
{
    int client = socket(AF_INET, SOCK_DGRAM, 0);
    int peer = socket(AF_INET, SOCK_DGRAM, 0);
    struct sockaddr_in any, peer_addr;
    socklen_t len = (socklen_t)sizeof(peer_addr);
    static halyard_dgram_udp udp;
    halyard_dgram_transport t;
    static halyard_dgram_channel ch;
    uint8_t buf[256];
    ssize_t n = -1;
    int i;

    memset(&any, 0, sizeof(any));
    any.sin_family = AF_INET;
    any.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    bind(client, (struct sockaddr *)&any, (socklen_t)sizeof(any));
    bind(peer, (struct sockaddr *)&any, (socklen_t)sizeof(any));
    getsockname(peer, (struct sockaddr *)&peer_addr, &len);

    CHECK(halyard_dgram_udp_transport(&udp, client, &peer_addr, &t), "the UDP transport wires up");
    halyard_dgram_channel_init(&ch, &t, (const uint8_t *)&peer_addr.sin_addr.s_addr, ntohs(peer_addr.sin_port),
                               our_id(), peer_id(), NULL);
    CHECK(halyard_dgram_channel_begin(&ch) == HALYARD_DGRAM_CHANNEL_OK, "begin sends");
    for (i = 0; i < 100 && n <= 0; i++) {
        n = recv(peer, buf, sizeof(buf), MSG_DONTWAIT);
        if (n <= 0)
            rc_sleep_ms(5);
    }
    CHECK(n == 88 && buf[0] == 6, "the peer received one 88-byte Init (%ld bytes)", (long)n);
    CHECK(t.receive(t.ctx, buf, sizeof(buf)) == 0, "an empty non-blocking socket reads as nothing, not an error");

    close(client);
    close(peer);
}

int main(int argc, char **argv)
{
    const char *vectors = argc > 1 ? argv[1] : "vectors/dgram-transport.kat";

    run_transcripts(vectors);
    test_chunks();
    test_prelude();
    test_association_rules();
    test_http_complete();
    test_channel();
    test_udp_transport();

    printf("dgram_test: %d passed, %d failed\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}
