/*
 * ripcord-3ds - discovery parser self-test.
 *
 * Unlike the crypto vector runner, this needs no vector file from the .NET side: the SRCH wire format
 * is plain ASCII text taken verbatim from docs/protocol/ps5-local-discovery.md, so the expected bytes
 * are transcribed directly from the spec below rather than generated by a second implementation. What
 * this checks is that this port's C reads the same spec the same way - a hand-written mismatch here
 * would mean a misreading of the doc, not a cross-language KDF disagreement.
 *
 * THIS BUILDS FOR THE HOST, NOT THE 3DS - see tests/Makefile. halyard_discovery.c has no socket or
 * hardware dependency of its own (see its header), so there is nothing 3DS-specific to verify here.
 */
#include "../discovery/halyard_discovery.h"
#include "../discovery/halyard_wake.h"

#include <stdio.h>
#include <string.h>

static int g_passed;
static int g_failed;

#define CHECK(cond, ...) do { \
    if (cond) { \
        g_passed++; \
    } else { \
        g_failed++; \
        printf("FAIL %s:%d: ", __FILE__, __LINE__); \
        printf(__VA_ARGS__); \
        printf("\n"); \
    } \
} while (0)

static void test_build_probe(void)
{
    char buf[256];
    size_t n;

    /* Verbatim from the spec's "Request" block, CRLF-terminated, trailing blank line included. */
    static const char expected_ps5[] =
        "SRCH * HTTP/1.1\r\ndevice-discovery-protocol-version:00030010\r\n\r\n";
    static const char expected_ps4[] =
        "SRCH * HTTP/1.1\r\ndevice-discovery-protocol-version:00020020\r\n\r\n";

    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps5, buf, sizeof(buf));
    CHECK(n == strlen(expected_ps5) && memcmp(buf, expected_ps5, n) == 0,
        "ps5 probe bytes did not match the spec's request block");

    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps4, buf, sizeof(buf));
    CHECK(n == strlen(expected_ps4) && memcmp(buf, expected_ps4, n) == 0,
        "ps4 probe bytes did not match the spec's request block (device-discovery-protocol-version)");

    /* A buffer too small to hold the datagram must fail closed, not silently truncate a UDP payload the
     * caller would otherwise send as-is. */
    n = halyard_discovery_build_probe(&halyard_discovery_profile_ps5, buf, 8);
    CHECK(n == 0, "undersized buffer should report 0, not a truncated length");
}

static void test_awake_response(void)
{
    /* Verbatim from the spec's "Response" block, with placeholders filled in. */
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n"
        "host-name:Living Room PS5\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00030010\r\n"
        "system-version:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), "192.168.1.42", &console);

    CHECK(ok == 1, "a well-formed 200 Ok response should parse");
    CHECK(console.is_awake == 1, "status 200 should set is_awake");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch: got '%s'", console.host_id);
    CHECK(strcmp(console.host_type, "PS5") == 0, "host_type mismatch: got '%s'", console.host_type);
    CHECK(strcmp(console.host_name, "Living Room PS5") == 0, "host_name mismatch: got '%s'", console.host_name);
    CHECK(strcmp(console.system_version, "09030008") == 0,
        "system_version mismatch: got '%s'", console.system_version);
    CHECK(strcmp(console.address, "192.168.1.42") == 0, "address mismatch: got '%s'", console.address);
}

static void test_standby_response(void)
{
    /* Verbatim from the "LAN wake" section's standby status line. */
    static const char response[] =
        "HTTP/1.1 620 Server Standby\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n"
        "host-name:Living Room PS5\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00030010\r\n"
        "system-version:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), NULL, &console);

    CHECK(ok == 1, "a well-formed 620 Server Standby response should still parse");
    CHECK(console.is_awake == 0, "status 620 should clear is_awake");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch on standby reply");
    CHECK(console.address[0] == '\0', "a NULL source_address should leave address empty, got '%s'", console.address);
}

static void test_ps4_response(void)
{
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:aabbccddeeff\r\n"
        "host-type:PS4\r\n"
        "host-name:Bedroom PS4\r\n"
        "host-request-port:997\r\n"
        "device-discovery-protocol-version:00020020\r\n"
        "system-version:09000000\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), "10.0.0.5", &console);

    CHECK(ok == 1, "a well-formed PS4 response should parse the same as a PS5 one");
    CHECK(strcmp(console.host_type, "PS4") == 0, "host_type should be PS4, got '%s'", console.host_type);
}

static void test_defaults_and_case_insensitivity(void)
{
    /* host-type omitted entirely, and every remaining header name given in a different case - the
     * spec's own client (HalyardSearchClient.TryParse) does both: GetValueOrDefault("host-type", "PS5")
     * and an OrdinalIgnoreCase field dictionary. */
    static const char response[] =
        "HTTP/1.1 200 Ok\r\n"
        "HOST-ID:  001122334455  \r\n"
        "Host-Name:Trimmed Name\r\n"
        "SYSTEM-VERSION:09030008\r\n"
        "\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(response, strlen(response), NULL, &console);

    CHECK(ok == 1, "omitting host-type entirely should not fail parsing");
    CHECK(strcmp(console.host_type, "PS5") == 0,
        "a missing host-type should default to PS5, got '%s'", console.host_type);
    CHECK(strcmp(console.host_id, "001122334455") == 0,
        "surrounding whitespace around a header value should be trimmed, got '%s'", console.host_id);
    CHECK(strcmp(console.host_name, "Trimmed Name") == 0, "host_name mismatch: got '%s'", console.host_name);
}

static void test_rejects_non_srch_and_missing_host_id(void)
{
    static const char garbage[] = "this is not a SRCH response at all\r\n\r\n";
    static const char no_host_id[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-type:PS5\r\n"
        "\r\n";
    halyard_discovered_console console;

    CHECK(halyard_discovery_parse_response(garbage, strlen(garbage), NULL, &console) == 0,
        "arbitrary text without an HTTP/1.1 status line must be rejected");
    CHECK(halyard_discovery_parse_response(no_host_id, strlen(no_host_id), NULL, &console) == 0,
        "a response with no host-id must be rejected - it is the one field the spec's own client requires");
}

static void test_truncated_datagram(void)
{
    /* A UDP datagram is delivered whole or not at all, but SRCH is worth being lenient with anyway: the
     * status line and host-id are both near the front, and a caller (e.g. a raced parse of a datagram
     * shorter than expected) should still get a usable result rather than a hard failure over a trailing
     * field it does not need. */
    static const char truncated[] =
        "HTTP/1.1 200 Ok\r\n"
        "host-id:001122334455\r\n"
        "host-type:PS5\r\n";
    halyard_discovered_console console;
    int ok = halyard_discovery_parse_response(truncated, strlen(truncated), NULL, &console);

    CHECK(ok == 1, "a datagram missing its trailing blank line should still parse if host-id is present");
    CHECK(strcmp(console.host_id, "001122334455") == 0, "host_id mismatch on truncated datagram");
}

/* ---------------------------------------------------------------------------------------------------
 * LAN wake - ps5-local-discovery.md, "LAN wake (rest mode -> awake)"
 *
 * The key below is SYNTHETIC. A real registration key is personal to one console and one account and
 * never appears in this tree; "1a2b3c4d" is eight ASCII hex characters chosen because the spec's own
 * worked derivation is easy to follow through them - 0x1a2b3c4d = 439041101.
 * ------------------------------------------------------------------------------------------------ */

static void test_wake_credential(void)
{
    char credential[HALYARD_WAKE_CREDENTIAL_MAX];

    /* The spec's derivation: user-credential = int(ascii(hex_decode(RP-Registkey)), 16). The record
     * stores the hex-decoded bytes, which for a real key are themselves ASCII hex digits. */
    CHECK(halyard_wake_credential((const uint8_t *)"1a2b3c4d", 8u, credential, sizeof(credential)) == 1,
        "a well-formed key should produce a credential");
    CHECK(strcmp(credential, "439041101") == 0, "expected 439041101, got %s", credential);

    /* Case does not matter - both spellings are the same number. */
    CHECK(halyard_wake_credential((const uint8_t *)"1A2B3C4D", 8u, credential, sizeof(credential)) == 1
        && strcmp(credential, "439041101") == 0, "uppercase hex should derive identically");

    /*
     * THE SIGNED CASE, WHICH IS THE WHOLE REASON THIS FUNCTION IS NOT A ONE-LINER.
     *
     * ps5-local-discovery.md's PS4 section pins the field as a signed 32-bit decimal [W], because the
     * PS4's observed credential is negative. Every PS5 sample is below 2^31, where signed and unsigned
     * print identically, so nothing we had held distinguished the two readings.
     *
     * halyard_wake.h records that the .NET side renders these unsigned and that this file follows the
     * spec instead. If that ever flips, this is the assertion that has to change with it - deliberately,
     * not by accident.
     */
    CHECK(halyard_wake_credential((const uint8_t *)"ffffffff", 8u, credential, sizeof(credential)) == 1,
        "an all-Fs key is well-formed");
    CHECK(strcmp(credential, "-1") == 0,
        "0xffffffff is -1 as a signed 32-bit decimal, got %s (unsigned would be 4294967295)", credential);

    CHECK(halyard_wake_credential((const uint8_t *)"80000000", 8u, credential, sizeof(credential)) == 1
        && strcmp(credential, "-2147483648") == 0, "the sign boundary itself");
    CHECK(halyard_wake_credential((const uint8_t *)"7fffffff", 8u, credential, sizeof(credential)) == 1
        && strcmp(credential, "2147483647") == 0, "one below the boundary is still positive");

    /* A corrupt key is refused, not guessed at. strtoul() would have accepted every one of these. */
    CHECK(halyard_wake_credential((const uint8_t *)"1a2b3c4g", 8u, credential, sizeof(credential)) == 0,
        "a non-hex digit should be refused");
    CHECK(halyard_wake_credential((const uint8_t *)" 1a2b3c4", 8u, credential, sizeof(credential)) == 0,
        "leading whitespace should be refused");
    CHECK(halyard_wake_credential((const uint8_t *)"0x1a2b3c", 8u, credential, sizeof(credential)) == 0,
        "an 0x prefix should be refused");
    CHECK(halyard_wake_credential((const uint8_t *)"123456789", 9u, credential, sizeof(credential)) == 0,
        "a key longer than 32 bits would discard its leading digits - refuse instead");
    CHECK(halyard_wake_credential((const uint8_t *)"1a2b3c4d", 0u, credential, sizeof(credential)) == 0,
        "an empty key is not a key");
    CHECK(halyard_wake_credential((const uint8_t *)"1a2b3c4d", 8u, credential, 4u) == 0,
        "a buffer too small for the widest credential should fail closed");
}

static void test_wake_payload(void)
{
    char buf[256];
    size_t n;

    /* Verbatim from the spec's WAKEUP block, LF-terminated, with the synthetic credential filled in. */
    static const char expected_ps5[] =
        "WAKEUP * HTTP/1.1\n"
        "client-type:vr\n"
        "auth-type:R\n"
        "model:w\n"
        "app-type:r\n"
        "user-credential:439041101\n"
        "device-discovery-protocol-version:00030010\n";

    n = halyard_wake_build_payload(&halyard_discovery_profile_ps5, "439041101", buf, sizeof(buf));
    CHECK(n == strlen(expected_ps5) && memcmp(buf, expected_ps5, n) == 0,
        "ps5 WAKEUP bytes did not match the spec's datagram block");

    /* Bare line feeds, and not one carriage return - the SRCH probe in the same exchange uses CRLF, and
     * making the two "consistent" is the change this guards against. */
    CHECK(memchr(buf, '\r', n) == NULL, "WAKEUP must not contain CR; SRCH does and WAKEUP does not");

    /* A PS4 WAKEUP differs only in the version token. */
    n = halyard_wake_build_payload(&halyard_discovery_profile_ps4, "439041101", buf, sizeof(buf));
    CHECK(n > 0 && strstr(buf, "device-discovery-protocol-version:00020020\n") != NULL,
        "ps4 WAKEUP should carry the PS4 protocol version");
    CHECK(strstr(buf, "00030010") == NULL, "ps4 WAKEUP should not carry the PS5 version");

    n = halyard_wake_build_payload(&halyard_discovery_profile_ps5, "439041101", buf, 16u);
    CHECK(n == 0, "undersized buffer should report 0, not a truncated datagram");
}

static void test_wake_ports(void)
{
    /*
     * Wire-confirmed source ports, and they are SOURCE ports - where the datagram comes from. The
     * destination is the discovery port in both families, never the host-request-port:997 the standby
     * reply advertises, which the spec calls a red herring for wake.
     */
    CHECK(halyard_discovery_profile_ps5.port == 9302
        && halyard_discovery_profile_ps5.wake_source_port == 9303
        && halyard_discovery_profile_ps5.wake_search_source_port == 9303,
        "ps5 wake ports: 9302 destination, 9303 source (cap49)");

    CHECK(halyard_discovery_profile_ps4.port == 987
        && halyard_discovery_profile_ps4.wake_source_port == 987
        && halyard_discovery_profile_ps4.wake_search_source_port == 0,
        "ps4 wake ports: 987 destination and source, ephemeral for the poll (cap53-cap57)");
}

int main(void)
{
    test_build_probe();
    test_awake_response();
    test_standby_response();
    test_ps4_response();
    test_defaults_and_case_insensitivity();
    test_rejects_non_srch_and_missing_host_id();
    test_truncated_datagram();
    test_wake_credential();
    test_wake_payload();
    test_wake_ports();

    printf("\n%d passed, %d failed\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}
