/*
 * ripcord-ps3 - the PPU half of the SPE probe. See rc_spu.h for what it is for.
 *
 * *** THE SEQUENCE HERE IS THE SDK'S, NOT AN INVENTION. *** It follows PSL1GHT's own
 * samples/spu/spudma: initialize, import, create group, initialize thread, start, wait, join, close.
 * That mattering is a lesson this port paid for - the packaging rules were written from ppu_rules "in
 * spirit" and dropped a step, and the result was four hardware runs that produced nothing at all. When
 * an SDK ships a worked example of the exact thing you are doing, the example is the specification.
 */
#include "rc_spu.h"

#include "platform/rc_platform.h"

#include <string.h>

/*
 * The pragma is around the include for the reason source/app/main.c documents at its own: PSL1GHT's
 * lv2syscall macros take u64 while these wrappers declare s32 parameters, and the conversions are
 * diagnosed inside the header where the inline bodies are, not at our call sites.
 */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include <sys/spu.h>
#pragma GCC diagnostic pop

/*
 * The SPE program, embedded in this binary. The symbol is generated by the Makefile: bin2s turns
 * build/rc_spu_probe.bin into an assembly blob, and the header it writes alongside declares these.
 * Naming is bin2s's, derived from the filename, which is why it is rc_spu_probe_bin rather than
 * anything this project chose.
 */
#include "rc_spu_probe_bin.h"

/* Shared with the SPE half. No code, no includes - see the header for why that is what makes it safe. */
#include "rc_spu_phase.h"

/* Generated by the Makefile from the linked SPU image: the heartbeat's local-store address, and the
 * entry point the linker chose. Both are compile-time truth to compare the console's answers against. */
#include "rc_spu_symbols.h"

/*
 * Pointer to effective address. Via uintptr_t so it works on a const pointer without casting const away,
 * which matters because rc_spu_run's source buffer is const and ought to stay that way.
 */
#define EA(x) ((u64)(uintptr_t)(x))

/* Three orders of magnitude above any plausible job. See the wait loop for why it is not infinite. */
#define RC_SPU_TIMEOUT_SECONDS 2ULL

static int s_ready;
static sysSpuImage s_image;

/*
 * The completion flag the SPE writes into. 128-byte aligned because that is the alignment the MFC wants
 * and the granularity a DMA write disturbs; volatile because the PPE spins on it and the only thing that
 * changes it is another processor, which is precisely the case a compiler is entitled to optimise away.
 */
static volatile uint32_t s_done __attribute__((aligned(128)));

/*
 * The job block the SPE fetches. 128-byte aligned for the MFC, and file-scope rather than a local
 * because the SPE reads it by DMA after this function has set it up - a stack copy would be a promise
 * about lifetime that nothing here enforces.
 */
static rc_spu_job s_job __attribute__((aligned(128)));

int rc_spu_init(void)
{
    if (s_ready)
        return 1;

    /*
     * [X] The argument is the number of RAW SPUs to reserve, and 6 is what the SDK's own sample passes.
     * A PS3 has 8 SPEs: one is fused off for yield and one is reserved by the hypervisor, leaving 6 to
     * the application. Taking the sample's number rather than reasoning to it is deliberate - what
     * matters for a probe is that it works, and what the split actually is can be measured later by the
     * thing that needs more than one.
     */
    if (sysSpuInitialize(6, 0) != 0)
        return 0;

    if (sysSpuImageImport(&s_image, rc_spu_probe_bin, 0) != 0)
        return 0;

    s_ready = 1;
    return 1;
}

uint64_t rc_spu_done_ea(void)
{
    /* What the PPE hands the SPE as the completion address, exposed so the caller can print the two
     * sides of the comparison without duplicating the EA arithmetic. */
    return EA(&s_done);
}

uint64_t rc_spu_job_ea(void)
{
    return EA(&s_job);
}

void rc_spu_image_info(uint32_t *entry, uint32_t *segments, uint32_t *expected_entry)
{
    /*
     * *** THESE FIELDS ARE NOT TRUSTWORTHY AND MUST NOT DRIVE A CONCLUSION. ***
     *
     * b9 read entryPoint as 0x22043300 where the linker had written 0x278, and segmentCount as 0, and
     * this function's caller duly concluded that the imported image was not ours. That conclusion was
     * wrong: the heartbeat in the same run proved the SPE was executing our program, which it could not
     * have been unless the image loaded correctly.
     *
     * The declaration is what is wrong. lv2/spu.h declares sysSpuImage as four u32s, and its third
     * member is documented as "address of segments" - an address, in a process whose pointers are 64
     * bits. That does not fit, so the struct lv2 writes cannot be the struct PSL1GHT declares, and
     * reading the later fields yields fragments of whatever the real layout is.
     *
     * It is still logged, because raw numbers from the console are worth having and the next person may
     * be able to work the real layout out from them. It is no longer allowed to decide anything.
     */
    *entry = s_ready ? s_image.entryPoint : 0u;
    *segments = s_ready ? s_image.segmentCount : 0u;
    *expected_entry = (uint32_t)RC_SPU_IMAGE_ENTRY;
}

void rc_spu_exit(void)
{
    if (s_ready) {
        (void)sysSpuImageClose(&s_image);
        s_ready = 0;
    }
}

int rc_spu_run(const void *src, void *dst, size_t size, uint64_t *ticks,
               uint32_t *phase, uint32_t *heartbeat, uint64_t *spu_args,
               uint32_t *join_cause, uint32_t *join_status)
{
    sys_spu_group_t group = 0;
    sys_spu_thread_t thread = 0;
    sysSpuThreadArgument arg;
    sysSpuThreadGroupAttribute grpattr;
    sysSpuThreadAttribute attr;
    u32 cause = 0, status = 0;
    uint64_t started, deadline;

    if (!s_ready || ticks == NULL || phase == NULL || heartbeat == NULL || spu_args == NULL
        || join_cause == NULL || join_status == NULL)
        return 0;

    {
        int i;
        for (i = 0; i < RC_SPU_ARG_COUNT; i++)
            spu_args[i] = 0u;
    }

    *phase = RC_SPU_PHASE_NOTHING;
    *heartbeat = RC_SPU_HEARTBEAT_UNREAD;
    *join_cause = 0u;
    *join_status = 0u;

    /* The names are read by the kernel through an effective address, so they must outlive the call -
     * string literals do, and nothing here is reentrant. */
    memset(&arg, 0, sizeof(arg));
    memset(&grpattr, 0, sizeof(grpattr));
    memset(&attr, 0, sizeof(attr));

    /*
     * `name` is declared `const char *`, not a u64 effective address - PSL1GHT's own spudma sample
     * writes ptr2ea() into it through a positional brace initializer, which compiles only because that
     * sample is not built with -Werror. Assign the pointer. nsize counts the terminating NUL, which is
     * what sizeof of a string literal gives.
     */
    grpattr.nsize = (u32)sizeof("ripcord-spu");
    grpattr.name = "ripcord-spu";

    attr.nsize = (u32)sizeof("rc_spu_probe");
    attr.name = "rc_spu_probe";
    attr.option = SPU_THREAD_ATTR_NONE;

    /*
     * ONE ARGUMENT: the address of the job block. b10 measured lv2 delivering arg3 as zero while arg0
     * through arg2 arrived intact, and PSL1GHT's samples never populate past arg1 - so the remaining
     * slots are not a mechanism to build on. rc_spu_phase.h argues it in full.
     */
    s_job.src_ea = EA(src);
    s_job.dst_ea = EA(dst);
    s_job.size = (uint64_t)size;
    s_job.done_ea = EA(&s_done);

    arg.arg0 = EA(&s_job);
    arg.arg1 = 0u;
    arg.arg2 = 0u;
    arg.arg3 = 0u;

    /* Cleared before the group is created, not after it is started: the SPE could in principle write it
     * the instant it runs, and a clear racing that would lose the completion and hang the spin below. */
    s_done = RC_SPU_PHASE_NOTHING;

    if (sysSpuThreadGroupCreate(&group, 1, 100, &grpattr) != 0)
        return 0;

    if (sysSpuThreadInitialize(&thread, group, 0, &s_image, &attr, &arg) != 0) {
        (void)sysSpuThreadGroupDestroy(group);
        return 0;
    }

    /*
     * THE MEASUREMENT. From here to the flag being observed is what a caller handing out a unit of work
     * actually pays: thread group start, the SPE's own startup, the DMA, and the completion write. It
     * deliberately does NOT exclude thread start - a decoder that starts a thread per macroblock row
     * would pay exactly this, and pretending otherwise would produce a number that flatters the design
     * it is meant to inform.
     */
    started = rc_tick();

    if (sysSpuThreadGroupStart(group) != 0) {
        (void)sysSpuThreadGroupDestroy(group);
        return 0;
    }

    /*
     * Poll the flag rather than join, because of what is being measured: sysSpuThreadGroupJoin returns
     * when the thread has exited and been reaped, which folds teardown into the number, while the flag
     * is written the moment the SPE's work is done.
     *
     * BOUNDED, and the previous version was not. It said a hang was "the correct failure, because a
     * silent hang on a specific line is a far better clue than a spurious success". That was wrong on
     * its own terms and the console proved it: the SPE did not finish, the PPE spun forever, and what
     * the operator got was a blank screen, a log that simply stopped, and a power cycle. A hang is not a
     * clue - it is the absence of one, and it destroys the run that would have produced it.
     *
     * The deadline is generous by three orders of magnitude. A 256 KB DMA job is tens of microseconds;
     * anything still running after two seconds is not slow, it is broken, and waiting longer only
     * postpones the report.
     */
    deadline = started + (rc_tick_hz() * RC_SPU_TIMEOUT_SECONDS);

    while (s_done != RC_SPU_PHASE_DONE && rc_tick() < deadline)
        ;

    *ticks = rc_tick() - started;

    if (s_done != RC_SPU_PHASE_DONE) {
        /*
         * Timed out. Everything from here is about turning a non-result into a finding, so it reports
         * rather than returns: how far the SPE got, and what lv2 says became of the thread.
         *
         * Terminate before join. Join on a thread that is still running would reproduce the hang this
         * whole branch exists to prevent - the kernel would simply block instead of the spin loop.
         */
        *phase = s_done;

        /*
         * READ THE SPE'S LOCAL STORE BEFORE TERMINATING IT. This is the measurement that separates "the
         * program never ran" from "it ran and its DMA went nowhere", and it needs a live thread - after
         * termination there is nothing to read. See spu/rc_spu_phase.h for the decision tree.
         */
        {
            u64 value = 0u;
            int i;

            if (sysSpuThreadReadLocalStorage(thread, (u32)RC_SPU_HEARTBEAT_ADDR, &value, 4) == 0)
                *heartbeat = (uint32_t)value;
            else
                *heartbeat = RC_SPU_HEARTBEAT_UNREADABLE;

            /* The addresses the SPE actually received, straight out of its local store. Read here
             * rather than inferred, because what the PPE passed and what the SPE got are exactly the
             * two things that might differ. */
            for (i = 0; i < RC_SPU_ARG_COUNT; i++) {
                u64 a = 0u;
                u32 at = (u32)(RC_SPU_ARGS_ADDR + (unsigned)i * 8u);
                spu_args[i] = (sysSpuThreadReadLocalStorage(thread, at, &a, 8) == 0) ? a : 0u;
            }
        }

        (void)sysSpuThreadGroupTerminate(group, 1);
        (void)sysSpuThreadGroupJoin(group, &cause, &status);
        (void)sysSpuThreadGroupDestroy(group);
        *join_cause = cause;
        *join_status = status;
        return 0;
    }

    (void)sysSpuThreadGroupJoin(group, &cause, &status);
    (void)sysSpuThreadGroupDestroy(group);

    *phase = s_done;
    *join_cause = cause;
    *join_status = status;
    return 1;
}
