//! Builds the C core's stream and Halyard layers the way `libripcord/tests/Makefile` does: its own
//! sources, its own include paths, and constants generated by its own `tools/gen_constants.py` from the
//! committed bundle into OUT_DIR. Nothing of the C core is copied.

use std::path::PathBuf;
use std::process::Command;

const SOURCES: &[&str] = &[
    "crypto/rc_aes.c",
    "crypto/rc_gcm.c",
    "crypto/rc_modes.c",
    "crypto/rc_sha256.c",
    "stream/fec_galois.c",
    "stream/fec_reed_solomon.c",
    "stream/stream_demux.c",
    "stream/stream_header.c",
    "stream/stream_key_schedule.c",
    "stream/stream_packet_crypto.c",
    "halyard/halyard_control_crypto.c",
    "halyard/halyard_registration.c",
    "halyard/halyard_account_seed.c",
    "util/rc_base64.c",
    "takion/takion_data_chunk.c",
    "takion/takion_sack_chunk.c",
    "takion/takion_handshake.c",
    "takion/takion_message.c",
    "takion/takion_control_proto.c",
    "takion/takion_control_sealer.c",
    "takion/senkusha_echo.c",
    "session/halyard_dgram_wire.c",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let core = manifest.join("../../libripcord");
    let bundle = manifest.join("../../src/Ripcord.Protocol.Halyard/Data/halyard-v1-constants.json");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let constants = out.join("halyard_v1_constants.g.c");

    let status = Command::new(std::env::var("PYTHON").unwrap_or_else(|_| "python3".into()))
        .arg(core.join("tools/gen_constants.py"))
        .args(["--registration", "--for", "engine/ripcord-diff"])
        .arg(&bundle)
        .arg(&constants)
        .env("PYTHONDONTWRITEBYTECODE", "1")
        .status()
        .expect("run python3 for libripcord/tools/gen_constants.py");
    assert!(status.success(), "gen_constants.py failed");

    let mut build = cc::Build::new();
    build.std("c99").warnings(false);
    for dir in ["crypto", "halyard", "platform"] {
        build.include(core.join(dir));
    }
    for source in SOURCES {
        build.file(core.join(source));
        println!("cargo:rerun-if-changed={}", core.join(source).display());
    }
    build.file(&constants).file(manifest.join("shim/diff_shim.c"));
    build.compile("ripcord_c_core");

    println!("cargo:rerun-if-changed=shim/diff_shim.c");
    // Headers the shim includes whole: the C scripted console is header-only.
    println!("cargo:rerun-if-changed={}", core.join("tests/fake_dgram_console.h").display());
    for dir in ["crypto", "halyard", "stream", "takion", "session"] {
        println!("cargo:rerun-if-changed={}", core.join(dir).display());
    }
    println!("cargo:rerun-if-changed={}", bundle.display());
    println!("cargo:rerun-if-changed={}", core.join("tools/gen_constants.py").display());
}
