//! The v1 Halyard derivations: the control-session KDF, field IVs and ciphers, PIN and account
//! registration, and the account seed. Ported from `libripcord/halyard/`, which is ported from
//! `Ripcord.Protocol.Halyard.Common/Crypto/V1`. The .NET side stays the reference for these
//! (docs/engine-plan.md, "The reference implementation"), and the vector files check this port against it.

pub mod account_seed;
pub mod control;
pub mod registration;

/// The generic v1 interoperability constants, generated by `build.rs` from the one committed bundle.
pub(crate) mod constants {
    include!(concat!(env!("OUT_DIR"), "/halyard_v1_constants.rs"));
}

pub const KEY_LENGTH: usize = 16;

/// The console-family discriminator. It selects the KDF variant and takes part in context-key selection,
/// so it is one value threaded through both.
pub const VERSION_SELECTOR_PS4: i32 = 0;
pub const VERSION_SELECTOR_PS5: i32 = 1;

/// Whether the PS4 tables were in the bundle this engine was built from.
pub fn has_ps4_tables() -> bool {
    constants::PS4_KDF_TABLE1.is_some()
}

/// Whether the PS4 registration tables were in the bundle.
pub fn has_ps4_registration() -> bool {
    constants::PS4_REGISTRATION_TABLE.is_some()
}

/// Entry `index` (0..32) of a 32-by-16 table.
fn entry(table: &[u8; 512], index: usize) -> &[u8; 16] {
    table[index * 16..index * 16 + 16].try_into().expect("16-byte entry")
}
