/*
 * ripcord-ps3 - platform bring-up: does the toolchain work, and is the clock what we think it is.
 *
 * This is step 4 of the port's order of work, and it is deliberately the cheapest program that can fail
 * informatively. It links the portable core's platform seam against PSL1GHT, prints a timestamp, and
 * then does the one measurement that everything timing-dependent in this port rests on.
 *
 * *** NEVER CROSS-COMPILED, NEVER RUN ON A CONSOLE. *** No PSL1GHT here and no PS3, so everything
 * SDK-facing is [X]. It has been built and run on a host, which is a narrower claim - see the end of
 * this comment for exactly how much narrower.
 *
 * WHY IT MEASURES THE CLOCK RATHER THAN JUST PRINTING ONE.
 *
 * rc_platform_ps3.c carries a single magic number - the PPE time base at 79.8 MHz - and a wrong value
 * there does not crash anything. It scales every timeout in the core by the ratio, so a handshake
 * deadline quietly becomes 20% short and the console looks flaky. That class of fault is expensive to
 * find later and trivial to find now: sleep a known interval, count ticks, divide.
 *
 * WHAT THE MEASUREMENT TELLS YOU - AND THIS IS NARROWER, AND BETTER, THAN IT USED TO BE.
 *
 * This comment used to warn that the measurement tests the CONJUNCTION of two unknowns: if the figure
 * came out a thousand times wrong, that was either a microsecond/millisecond mix-up in sysUsleep or a
 * wrong hard-coded frequency, and the program could not say which. It advised watching a wall clock to
 * disambiguate, since the run sleeps about five seconds in total.
 *
 * That is no longer the situation. rc_tick_hz() now asks lv2 for the frequency (syscall 147) instead of
 * asserting it, so the frequency is not an unknown being tested - it is the known the sleep is tested
 * AGAINST. A measurement that disagrees is evidence about sysUsleep specifically. The wall-clock trick
 * still works and is still worth doing on the first boot, but it is now a confirmation rather than the
 * only way to read the result.
 *
 * The hard-coded figure has not gone away; it has been demoted to an expectation, and this program
 * checks lv2's answer against it as a separate line. If those two ever disagree, the kernel is right.
 *
 * OUTPUT GOES TO A FILE, following both other ports. Results you can copy off the drive beat a
 * photograph of a television that you then retype.
 *
 * WHAT HAS ACTUALLY BEEN RUN, since "never run on a console" above is about the PS3 and this file is
 * not only a PS3 file. Everything below touches the platform seam, the logger and the CSPRNG seam and
 * nothing else, so it compiles and runs on a host against stand-ins for all three. Re-run on 2026-09-11
 * after the CSPRNG check was added, and every branch was exercised rather than only the happy one,
 * because a check that has never failed is not yet known to be a check:
 *
 *   - the pass: five seconds of wall time against the five this comment claims, all four ok lines.
 *   - the time-base FAIL: a stand-in reporting a frequency a thousand times too high. Both the note
 *     line and the failure fire, and the program exits 1.
 *   - the CSPRNG FAIL: a stand-in generator returning an lv2 error. rc_random_init refuses, the
 *     alignment hint prints, and the program exits 1.
 *
 * That says nothing about rc_platform_ps3.c or rc_random_ps3.c, whose mftb, sysUsleep and
 * sysGetRandomNumber remain [X] - the host run swapped all three out. It says the program around them
 * is sound, which is the half that can be settled without a console.
 */

#include "platform/rc_platform.h"
#include "util/rc_log.h"
#include "util/rc_random.h"

/*
 * Generated by the Makefile, which bumps a counter whenever a source file changes. The number appears in
 * the XMB title, in the beacon file and at the top of both logs, and all three have to agree with what
 * `make` printed. See the Makefile's BUILD_NO comment for the five runs that made this necessary.
 */
#include "rc_build_id.h"
#include "rc_spu.h"
#include "rc_spu_phase.h"
#include "rc_netlog.h"
#include "rc_decode_probe.h"
#include "rc_core_tests.h"
#include "rc_discover.h"
#include "rc_connect.h"

#include "../platform/rc_platform_ps3.h"

#include <stdarg.h>   /* the ps3_log tee */
#include <stdint.h>
#include <stdio.h>    /* fopen/fclose for the probe; vsnprintf for the tee */
#include <string.h>   /* memcmp, for the CSPRNG check */

/*
 * sysLv2Fs* - the log channel that does not go through newlib. See lv2_log_open below for why.
 *
 * THE PRAGMA IS AROUND THE INCLUDE, NOT AROUND THE CALL SITES, and the difference is not cosmetic. The
 * SDK's lv2syscall macros take their arguments as u64 while the sysLv2Fs* wrappers declare theirs as
 * s32, so each wrapper converts signed to unsigned in its own body - and these are inline functions, so
 * GCC diagnoses those bodies where the header is read, not where we call them. A pragma wrapped around
 * our three functions suppressed nothing at all; this is what the first attempt got wrong.
 *
 * It is scoped to this one include rather than dropped from the Makefile. The conversions are the SDK's,
 * on syscall numbers and file descriptors, and there is nothing at our call sites to fix - but a flag
 * relaxed globally to get one file to build is how a real narrowing bug gets through later, in a port
 * that also does bitstream parsing and crypto.
 */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include <sys/file.h>
#include <sys/process.h>
#pragma GCC diagnostic pop

/*
 * THE MAIN THREAD'S STACK - and this line is here because its absence cost two hardware runs.
 *
 * README.md has carried the warning since before this port compiled: the 3DS crashed twice on a 32 KB
 * default and the Vita raised its 4 KiB default to 256 KB before running anything. When the toolchain
 * arrived, the mechanism was found (this macro), the Vita's --gc-sections trap was checked for and shown
 * not to apply here, the finding was written up in three documents - and nobody put the macro in the
 * program. Two runs then produced no output of any kind, and a long investigation of the filesystem
 * layer followed, which was the wrong tree: the first thing main() does is call a function with a
 * 512-byte frame, and the second is another one.
 *
 * The lesson is not about stacks. It is that "we identified the mechanism" and "the program uses it" are
 * different claims, and the documentation recorded the first as though it settled the second.
 *
 * THE SECOND ARGUMENT IS A RAW BYTE COUNT. It is not the SYS_PROCESS_SPAWN_STACK_SIZE_* enumeration,
 * and the first version of this line passed SYS_PROCESS_SPAWN_STACK_SIZE_1M because the name was such a
 * good fit. That constant is 0x70. The field is a size in bytes, so the shipped binary asked lv2 for a
 * ONE HUNDRED AND TWELVE BYTE stack - worse than the default it was written to replace, and a crash
 * before main() with no output, which is precisely the symptom it was meant to cure.
 *
 * Two things say it is bytes, and both were available before that build was made. Every sample in
 * PSL1GHT writes SYS_PROCESS_PARAM(1001, 0x100000) or 0x10000 - a byte count, spelled in hex. And the
 * field immediately after this one in the same struct is SYS_PROCESS_SPAWN_MALLOC_PAGE_SIZE_1M, which is
 * 0x00100000: the struct's own neighbouring member makes the units unambiguous. The _STACK_SIZE_ names
 * belong to the `flags` argument of sysProcessExitSpawn, a different call entirely.
 *
 * 1 MB rather than a snug fit. The deepest measured path in shared code is the audio loss-concealment
 * chain at ~12.4 KB and this program is nowhere near that; there is nothing to buy by being tight and a
 * silent crash to lose by being wrong.
 *
 * [X] The loader's DEFAULT, when this macro is absent, is still unmeasured.
 */
SYS_PROCESS_PARAM(1001, 0x100000)

/*
 * WHERE THE LOG CAN GO, IN ORDER OF PREFERENCE - and this list exists because the first hardware run
 * produced nothing at all.
 *
 * That run installed cleanly, appeared on the XMB, launched, exited without a crash report, and wrote no
 * log anywhere. The program's entire output is that file, so "no file" and "did not run" look identical
 * from the outside, which is a rotten place to be on the first boot of a new platform.
 *
 * The suspect is the sandbox. A packaged title is not a shell script: it gets its own directory under
 * /dev_hdd0/game/<APPID>/ and there is no reason to assume it may write outside it. The build before
 * that run had been pointed at /dev_hdd0/ precisely BECAUSE that directory always exists - which was
 * true, and irrelevant, because existing and being writable by this process are different questions.
 *
 * So the program stops assuming and measures. It tries each of these, uses the first that accepts a
 * file, and then logs the whole table - every candidate, and whether it worked. One run answers "where
 * may a packaged PS3 homebrew write?" for good, and the answer goes in the log rather than in a comment
 * somebody has to trust.
 *
 * The order is deliberate: the app's own USRDIR first, because it is the one a sandbox is most likely to
 * permit and the one a real client would use anyway.
 */
#ifndef RC_PS3_LOG_DIRS
#define RC_PS3_LOG_DIRS \
    "/dev_hdd0/game/" RC_PS3_APPID "/USRDIR/", \
    "/dev_hdd0/tmp/", \
    "/dev_hdd0/", \
    "/dev_usb000/"
#endif

static const char *const g_log_dirs[] = { RC_PS3_LOG_DIRS };

#define LOG_DIR_COUNT ((int)(sizeof(g_log_dirs) / sizeof(g_log_dirs[0])))

/*
 * Can this process create a file here? Opened for append and closed immediately, which leaves the real
 * log file in place if this is the directory rc_log_open goes on to use, and leaves an empty one behind
 * if it is not. An empty stray file is a small price for an unambiguous answer, and it is itself
 * evidence - a zero-byte ps3-bringup.log in a directory the program did NOT choose still proves that
 * directory was writable.
 */
static int dir_accepts_a_file(const char *dir, const char *filename)
{
    /* Static, not a local. rc_log.c makes this argument in full for its own format buffer: a 512-byte
     * frame on a thread whose stack size was until now unset is not worth the tidiness, and this program
     * is single-threaded so there is nothing to race with. */
    static char path[512];
    FILE *f;

    if (snprintf(path, sizeof(path), "%s%s", dir, filename) < 0)
        return 0;

    f = fopen(path, "a");
    if (f == NULL)
        return 0;
    fclose(f);
    return 1;
}

/*
 * THE SECOND LOG CHANNEL, AND WHY A BRING-UP PROGRAM HAS TWO.
 *
 * The first hardware run produced no output of any kind. Not a wrong answer - nothing: installed,
 * launched, exited, no crash report, no file in any of the four directories the probe above tries, not
 * even the zero-byte marker the probe leaves behind. That is the worst possible result, because "the
 * program did not run" and "the program ran and could not tell you" are indistinguishable from outside.
 *
 * Static analysis said the plumbing was right, which is exactly why it was not worth more of it: the
 * PPU's newlib routes file I/O through a devoptab table, _open_r returns -1/ENOSYS when the entry it
 * wants is null, and the whole chain - lv2-crt0.o's constructor, librt's __librt_open_r, a kept .ctors
 * section - is present and correct in the linked ELF. Something in it does not do at runtime what it
 * plainly does on paper, and another hour of objdump was not going to say what.
 *
 * So this program stops depending on that layer to report on itself. sysLv2FsOpen and sysLv2FsWrite are
 * inline syscall wrappers in <sys/file.h> - no library, no devoptab, no newlib, nothing between this
 * code and lv2 but a `sc` instruction. If the console can write a file at all, this writes it.
 *
 * BOTH channels stay. fopen's is not dead weight: whether it works is now itself one of the things this
 * program reports, and the log says which channels carried it. A bring-up program that quietly routed
 * around a broken subsystem, rather than naming it, would be hiding the finding.
 */
static s32 g_lv2_fd = -1;
static const char *g_lv2_dir;

static int lv2_log_open(const char *dir, const char *filename)
{
    static char path[512];   /* static for the reason dir_accepts_a_file gives */
    s32 fd = -1;

    if (snprintf(path, sizeof(path), "%s%s", dir, filename) < 0)
        return 0;

    /* TRUNC rather than APPEND, unlike the fopen channel. Runs of this program are meant to be read one
     * at a time and an lv2 append needs an explicit seek to end that this does not do; a file that is
     * unambiguously the last run beats one that might be two runs concatenated. */
    if (sysLv2FsOpen(path, SYS_O_WRONLY | SYS_O_CREAT | SYS_O_TRUNC, &fd, 0666u, NULL, 0u) != 0)
        return 0;

    g_lv2_fd = fd;
    g_lv2_dir = dir;
    return 1;
}

static void lv2_log_write(const char *text)
{
    u64 written = 0u;

    if (g_lv2_fd < 0)
        return;
    (void)sysLv2FsWrite(g_lv2_fd, text, (u64)strlen(text), &written);
}

static void lv2_log_close(void)
{
    if (g_lv2_fd >= 0) {
        (void)sysLv2FsClose(g_lv2_fd);
        g_lv2_fd = -1;
    }
}

/*
 * Tee. Every ps3_log in this file reaches both channels, and neither can suppress the other.
 *
 * The buffer is static rather than a local for the reason rc_log.c gives at length about its own: this
 * is a 512-byte frame on a thread whose stack size is still an open question on this platform, and the
 * program is single-threaded, so there is nothing for it to race with.
 */
static char g_line[512];

static void ps3_log(const char *fmt, ...) __attribute__((format(printf, 1, 2)));

static void ps3_log(const char *fmt, ...)
{
    va_list args;

    va_start(args, fmt);
    (void)vsnprintf(g_line, sizeof(g_line), fmt, args);
    va_end(args);

    rc_log("%s", g_line);
    lv2_log_write(g_line);
    rc_netlog_write(g_line);
}

/* The sleep used for calibration. Long enough that the sleep's own wake-up jitter - a scheduler
 * granularity of a millisecond or two - is a rounding error rather than the measurement, and short
 * enough that nobody minds running it. */
#define CALIBRATE_MS 1000u

static int measure_timebase(void)
{
    uint64_t t0, t1, ticks, measured_hz, claimed_hz;
    int failures = 0;

    claimed_hz = rc_tick_hz();

    /* lv2's answer against this port's expectation. Separate from the measurement below and reported
     * separately, because they fail for different reasons: this line disagreeing means the frequency
     * table in rc_platform_ps3.c is wrong for this machine, and the kernel wins. It is not a failure -
     * a console that genuinely runs at another rate is still a console this port should work on - so it
     * is logged rather than counted. */
    if (claimed_hz != rc_ps3_timebase_hz_expected()) {
        ps3_log("note:  lv2 reports %llu Hz, this port expected %llu - believing lv2\n",
               (unsigned long long)claimed_hz,
               (unsigned long long)rc_ps3_timebase_hz_expected());
    }

    t0 = rc_tick();
    rc_sleep_ms(CALIBRATE_MS);
    t1 = rc_tick();

    if (t1 <= t0) {
        /* Either the tick does not advance at all, or it went backwards - and the second would be
         * worse, because rc_time_ms() is derived from this same counter and the core's timeout loops
         * are written assuming it cannot. */
        ps3_log("FAIL  tick did not advance across a %u ms sleep (%llu -> %llu)\n",
               CALIBRATE_MS, (unsigned long long)t0, (unsigned long long)t1);
        return 1;
    }

    ticks = t1 - t0;
    measured_hz = ticks * 1000ULL / CALIBRATE_MS;

    ps3_log("tick:  %llu ticks across a %u ms sleep\n", (unsigned long long)ticks, CALIBRATE_MS);
    ps3_log("       measured ~%llu Hz, rc_tick_hz() claims %llu Hz\n",
           (unsigned long long)measured_hz, (unsigned long long)claimed_hz);

    /* A tenth is a deliberately loose bound. It is not trying to certify the constant to the last
     * digit - it is trying to catch the failures that actually happen here, which are a wrong unit or
     * a wrong divisor, and those are out by factors of a thousand or of forty, not by percent. */
    if (measured_hz > claimed_hz + claimed_hz / 10ULL
        || measured_hz < claimed_hz - claimed_hz / 10ULL) {
        ps3_log("FAIL  that is not within 10%% - suspect sysUsleep's units\n");
        ps3_log("      (the frequency came from lv2, so it is the sleep that is in question; check a\n");
        ps3_log("       wall clock anyway - this program sleeps about five seconds in total)\n");
        failures++;
    } else {
        ps3_log("ok    the sleep agrees with lv2's time base - both units look right\n");
    }

    return failures;
}

static int check_monotonic(void)
{
    uint64_t previous;
    unsigned i;
    int failures = 0;

    /* rc_time_ms() must never step backwards - see rc_platform.h. On this port it is derived from the
     * time base rather than from a wall clock precisely so that it cannot, which makes this check a
     * test of that reasoning rather than of the system clock. It is cheap, so it runs anyway: the
     * reasoning is only worth what the implementation actually does. */
    previous = rc_time_ms();
    for (i = 0u; i < 4u; i++) {
        uint64_t now;
        rc_sleep_ms(1000u);
        now = rc_time_ms();
        if (now < previous) {
            ps3_log("FAIL  rc_time_ms went backwards: %llu then %llu\n",
                   (unsigned long long)previous, (unsigned long long)now);
            failures++;
        }
        previous = now;
    }

    if (failures == 0) {
        ps3_log("ok    rc_time_ms advanced monotonically across 4 seconds, now %llu ms\n",
               (unsigned long long)previous);
    }
    return failures;
}

static int check_csprng(void)
{
    uint8_t a[32], b[32];

    /*
     * The whole value of this check is that it runs on a console. rc_random_ps3.c can be read, reasoned
     * about and compiled on a host, and none of that establishes the two things it marks [X]: whether
     * sysGetRandomNumber returns zero for success, and whether it tolerates an unaligned destination.
     * rc_random_init() is written as a probe precisely so that both are settled here, on the first boot,
     * rather than inside a handshake key where nobody can see them.
     */
    if (!rc_random_init()) {
        ps3_log("FAIL  rc_random_init: no usable entropy source\n");
        ps3_log("      either sysGetRandomNumber failed, or it succeeded and wrote nothing. It is asked\n");
        ps3_log("      for bytes at an ODD address on purpose - if alignment is the problem, this is\n");
        ps3_log("      where it shows. See the [X] notes in rc_random_ps3.c.\n");
        return 1;
    }

    if (!rc_random_bytes(a, sizeof(a)) || !rc_random_bytes(b, sizeof(b))) {
        ps3_log("FAIL  rc_random_bytes returned failure after init succeeded\n");
        return 1;
    }

    /*
     * Two draws must differ. This is a weak test and is meant to be: it catches a generator that
     * returns a fixed buffer, which is the remaining plausible way for a broken implementation to look
     * alive after the init probe has passed. It is NOT evidence of cryptographic quality and must never
     * be described as any - a counter would pass it. The only real assurance here is that the bytes come
     * from the system's own generator.
     */
    if (memcmp(a, b, sizeof(a)) == 0) {
        ps3_log("FAIL  two 32-byte draws were identical - this is not a random source\n");
        return 1;
    }

    ps3_log("ok    CSPRNG live: init probed an unaligned draw, two draws differ\n");

    /*
     * THIS USED TO CALL rc_random_exit() HERE, AND THAT WAS A BUG worth leaving a note about.
     *
     * The generator is a process-wide resource, not this check's property. Tearing it down on the way out
     * of a PROBE left s_ready clear for everything after it, so every later draw returned failure - and
     * the failure was invisible in exactly the place it mattered: the run reported "CSPRNG live" a few
     * lines above, and then the stream session's 16-byte handshake key could not be drawn at all.
     *
     * b49 spent a hardware round trip finding that, and only found it because the failing step was named
     * rather than guessed at. The lifetime belongs to main(), which closes it beside the log channels.
     */
    return 0;
}

/*
 * 256 KB each way. Large enough that the DMA dominates the per-job overhead measured beside it - at any
 * plausible Cell bandwidth this is hundreds of microseconds against a start-up cost in the tens - and
 * small enough to sit in .bss on a console with 256 MB. 128-byte aligned because the MFC requires it.
 */
#define SPU_BYTES (256u * 1024u)

static unsigned char g_spu_src[SPU_BYTES] __attribute__((aligned(128)));
static unsigned char g_spu_dst[SPU_BYTES] __attribute__((aligned(128)));

/* Renders a phase word for the log. The SPE's values are ASCII on purpose, but a raw hex figure beside
 * the name is what you actually want when the value is none of them. */
static const char *spu_phase_name(uint32_t phase)
{
    switch (phase) {
    case RC_SPU_PHASE_NOTHING: return "NOTHING - the SPE never wrote anything";
    case RC_SPU_PHASE_ENTERED: return "ENTERED - the SPE ran, then stalled or died";
    case RC_SPU_PHASE_DONE:    return "DONE";
    default:                   return "unrecognised - not a value this program writes";
    }
}

static const char *spu_heartbeat_name(uint32_t hb)
{
    switch (hb) {
    case RC_SPU_HEARTBEAT_RUNNING:    return "RUNNING - executed, but died at or inside the DMA";
    case RC_SPU_HEARTBEAT_GOTJOB:     return "GOTJOB - the job block arrived, died signalling";
    case RC_SPU_HEARTBEAT_PASTDMA:    return "PASTDMA - the transfer returned on the SPE side";
    case RC_SPU_HEARTBEAT_LOADED:     return "LOADED - image in local store, main() never ran";
    case RC_SPU_HEARTBEAT_UNREADABLE: return "local store could not be read";
    case RC_SPU_HEARTBEAT_UNREAD:     return "not read";
    default:                          return "local store does not hold our program";
    }
}

static int spu_report_failure(const char *what, uint32_t phase, uint32_t heartbeat,
                              const uint64_t *spu_args, const uint64_t *passed,
                              uint32_t cause, uint32_t status)
{
    /* What each mirrored slot means now that a job block replaced the argument list: the address the
     * SPE was handed, then three fields it read back out of the block at that address. */
    static const char *const argname[RC_SPU_ARG_COUNT] = { "job", "src", "size", "done" };
    uint32_t entry = 0u, segments = 0u, expected = 0u;
    int mismatch = 0;
    int i;

    rc_spu_image_info(&entry, &segments, &expected);

    ps3_log("FAIL  %s\n", what);
    ps3_log("      heartbeat 0x%08x  %s\n", heartbeat, spu_heartbeat_name(heartbeat));
    ps3_log("      phase     0x%08x  %s\n", phase, spu_phase_name(phase));
    ps3_log("      join      cause 0x%08x  status 0x%08x\n", cause, status);

    /* Raw only. PSL1GHT's sysSpuImage layout does not match lv2's on this target - b9's reading of
     * these fields produced a confident and wrong conclusion, so they no longer decide anything. */
    ps3_log("      image     entry 0x%08x segs %u (linker 0x%08x; fields unreliable)\n",
            entry, segments, expected);

    ps3_log("      arguments  as passed        as the SPE saw them\n");
    for (i = 0; i < RC_SPU_ARG_COUNT; i++) {
        int bad = (spu_args[i] != passed[i]);
        if (bad)
            mismatch = 1;
        ps3_log("        %-4s  %016llx  %016llx %s\n",
                argname[i],
                (unsigned long long)passed[i],
                (unsigned long long)spu_args[i],
                bad ? "<- MISMATCH" : "");
    }

    /*
     * The decision tree, in the log rather than in a header nobody has open beside the console. Each of
     * these runs costs an install, so the log should say what to do next, not only what it saw.
     */
    if (mismatch)
        ps3_log("      -> the job block did not survive the round trip. Address or DMA path.\n");
    else if (heartbeat == RC_SPU_HEARTBEAT_RUNNING)
        ps3_log("      -> died at the transfer, with the right address. Suspect MFC rules.\n");
    else if (heartbeat == RC_SPU_HEARTBEAT_PASTDMA)
        ps3_log("      -> the SPE completed the transfer and the PPE cannot see it. Coherency.\n");
    else if (heartbeat == RC_SPU_HEARTBEAT_LOADED)
        ps3_log("      -> image loaded but main() never ran. Suspect entry point or scheduling.\n");
    else
        ps3_log("      -> local store does not hold our program. Suspect the import or the thread.\n");

    return 1;
}

/*
 * HOW MANY TIMES TO REPEAT A MEASUREMENT, AND WHY THE MINIMUM IS TAKEN.
 *
 * The first two hardware runs disagreed badly: dispatch measured 65 us and then 89 us, and the DMA
 * figure derived from subtracting them came out at 9,967 MB/s and then 39,741 MB/s. The second is not
 * credible for one SPE, and the pair of them are not a measurement - they are one sample each, of a
 * quantity that shares a console with the XMB, a network stack and a filesystem, put through a
 * subtraction that amplifies whatever noise each carried.
 *
 * DECODE.md now cites these numbers, so they have to be worth citing. Ten runs, keep the minimum: the
 * fastest observed time is the one least contaminated by something else happening on the machine, which
 * is the right estimator for "what does this cost when nothing is in the way". The spread is reported
 * beside it, because a wide spread is itself the finding - it would mean dispatch cost is not a stable
 * quantity on this hardware and the decoder cannot budget against it.
 */
#define SPU_REPEATS 10

static int spu_measure(size_t size, uint64_t *best, uint64_t *worst,
                       uint32_t *phase, uint32_t *heartbeat, uint64_t *spu_args,
                       uint32_t *cause, uint32_t *status)
{
    unsigned i;

    *best = 0u;
    *worst = 0u;

    for (i = 0u; i < SPU_REPEATS; i++) {
        uint64_t t = 0u;

        if (!rc_spu_run(g_spu_src, g_spu_dst, size, &t, phase, heartbeat, spu_args, cause, status))
            return 0;

        if (i == 0u || t < *best)
            *best = t;
        if (t > *worst)
            *worst = t;
    }
    return 1;
}

static int check_spu(void)
{
    uint64_t empty_ticks = 0u, copy_ticks = 0u;
    uint64_t empty_worst = 0u, copy_worst = 0u;
    uint64_t hz = rc_tick_hz();
    uint32_t phase = 0u, heartbeat = 0u, cause = 0u, status = 0u;
    uint64_t spu_args[RC_SPU_ARG_COUNT];
    uint64_t passed[RC_SPU_ARG_COUNT];
    size_t i;

    if (!rc_spu_init()) {
        ps3_log("FAIL  rc_spu_init: could not bring up the SPU subsystem or import the image\n");
        return 1;
    }

    /*
     * TWO RUNS, AND THE SUBTRACTION IS THE POINT. The first asks the SPE to copy nothing: what it times
     * is thread-group start, the SPE's own startup, and the completion write - the cost of ASKING. The
     * second copies 256 KB. The difference is the DMA, and the first number on its own is what decides
     * how coarsely the decoder must batch. Neither is interesting without the other.
     */
    passed[0] = rc_spu_job_ea();
    passed[1] = (uint64_t)(uintptr_t)g_spu_src;
    passed[2] = 0u;
    passed[3] = rc_spu_done_ea();

    if (!spu_measure(0u, &empty_ticks, &empty_worst, &phase, &heartbeat, spu_args,
                     &cause, &status)) {
        int r = spu_report_failure("rc_spu_run: the empty job did not complete",
                                   phase, heartbeat, spu_args, passed, cause, status);
        rc_spu_exit();
        return r;
    }

    for (i = 0u; i < SPU_BYTES; i++) {
        g_spu_src[i] = (unsigned char)(i * 7u + 1u);
        g_spu_dst[i] = 0u;
    }

    passed[2] = (uint64_t)SPU_BYTES;

    if (!spu_measure(SPU_BYTES, &copy_ticks, &copy_worst, &phase, &heartbeat, spu_args,
                     &cause, &status)) {
        int r = spu_report_failure("rc_spu_run: the 256 KB job did not complete",
                                   phase, heartbeat, spu_args, passed, cause, status);
        rc_spu_exit();
        return r;
    }

    /* The SPE actually moved the bytes, or the timing measures an empty loop. memcmp rather than a
     * checksum: a wrong byte anywhere is what matters, not how many. */
    if (memcmp(g_spu_src, g_spu_dst, SPU_BYTES) != 0) {
        ps3_log("FAIL  the SPE reported done but the copy does not match\n");
        rc_spu_exit();
        return 1;
    }

    ps3_log("spu:   best of %u runs each; spread is the worst case beside it\n", SPU_REPEATS);
    ps3_log("       empty job      %llu us  (worst %llu us)  <- cost of asking\n",
            (unsigned long long)(empty_ticks * 1000000ULL / hz),
            (unsigned long long)(empty_worst * 1000000ULL / hz));
    ps3_log("       %u KB copied  %llu us  (worst %llu us)\n",
            SPU_BYTES / 1024u,
            (unsigned long long)(copy_ticks * 1000000ULL / hz),
            (unsigned long long)(copy_worst * 1000000ULL / hz));

    if (copy_ticks > empty_ticks) {
        uint64_t dma_ticks = copy_ticks - empty_ticks;
        /* Both directions: the SPE reads the source into local store and writes it back out, so the
         * MFC moved twice what the buffer holds. Reported in MB/s, which is the unit the decoder
         * budget will be argued in. */
        uint64_t bytes = (uint64_t)SPU_BYTES * 2ULL;
        uint64_t mb_per_s = (dma_ticks > 0ULL)
                            ? (bytes * hz / dma_ticks) / (1024ULL * 1024ULL)
                            : 0ULL;
        ps3_log("       DMA alone     %llu us, %llu MB/s both ways, single-buffered\n",
                (unsigned long long)(dma_ticks * 1000000ULL / hz),
                (unsigned long long)mb_per_s);
        /* The subtraction of two best-of-ten figures is still a difference of two noisy quantities, and
         * it is small here relative to either. Treated as an order of magnitude, not a throughput. */
        ps3_log("                     (a difference of two measurements - read it as an order)\n");
    }

    ps3_log("ok    one SPE ran a DMA job and the bytes arrived intact\n");
    rc_spu_exit();
    return 0;
}

/*
 * WHERE THE CAPTURE LIVES ON THE CONSOLE. Copied there by hand over FTP; not embedded in the binary and
 * never committed, because it is dirty-room material - docs/protocol/captures/ is gitignored and a 2 MB
 * capture baked into a .self would be that rule defeated by a build step.
 *
 * Its absence is not a failure. The check reports "no stream" and the run continues, which is the same
 * shape as the .NET suite's fixture-backed tests: a machine without the dirty room still gets a green
 * run of everything that does not need it.
 */
#ifndef RC_DECODE_STREAM_PATH
#define RC_DECODE_STREAM_PATH "/dev_hdd0/video.264"
#endif

/*
 * HOW MANY FRAMES TO DECODE FOR THE RATE. Enough that start-up costs - the decoder's first allocations,
 * the 22-slice IDR that opens the stream - average out, and few enough that the run stays a couple of
 * minutes rather than ten. The capture holds 1,214.
 */
#ifndef RC_DECODE_FRAMES
#define RC_DECODE_FRAMES 300
#endif

/*
 * ports/common's own suites, on the console. See source/coretest/rc_core_tests.h for why this matters:
 * every assertion in the shared core has only ever run on little-endian x86, and the PPE is big-endian.
 *
 * THE RUNNERS PRINT WITH printf, which here goes to a TTY nobody is reading, so stdout is redirected to
 * a file for the duration and replayed through ps3_log afterwards - which puts it on the network log and
 * in both files, like everything else. Their output is the useful part when something fails: a bare exit
 * code would say "fec failed" and leave the next step to a rebuild.
 */
#define RC_CORE_TEST_CAPTURE "/dev_hdd0/ripcord-core-tests.txt"

static void replay_captured(const char *path)
{
    static char line[512];
    FILE *f = fopen(path, "r");

    if (f == NULL) {
        ps3_log("      (could not reopen %s to replay it)\n", path);
        return;
    }
    while (fgets(line, (int)sizeof(line), f) != NULL) {
        size_t n = strlen(line);
        while (n > 0u && (line[n - 1u] == '\n' || line[n - 1u] == '\r'))
            line[--n] = '\0';
        if (n > 0u)
            ps3_log("      | %s\n", line);
    }
    fclose(f);
}

static int check_core(void)
{
    rc_core_test_result results[RC_CORE_TEST_COUNT];
    int failed;
    int i;

    ps3_log("core:  running ports/common's suites on this hardware\n");

    /* Redirected, not duplicated: there is no dup2 to restore through here, and rc_log still reaches
     * its own file and the network, so nothing is actually lost by giving stdout away. */
    if (freopen(RC_CORE_TEST_CAPTURE, "w", stdout) == NULL)
        ps3_log("      (stdout could not be captured - the runners' detail will be lost)\n");

    failed = rc_core_tests_run(results);

    fflush(stdout);

    for (i = 0; i < RC_CORE_TEST_COUNT; i++)
        ps3_log("       %-14s %s\n", results[i].name,
                results[i].skipped ? "skipped - no vectors on this console"
                                   : (results[i].exit_code == 0 ? "pass" : "FAIL"));

    for (i = 0; i < RC_CORE_TEST_COUNT; i++)
        if (results[i].skipped) {
            ps3_log("       (copy ports/common/tests/vectors/*.kat to %s to run those)\n",
                    RC_CORE_TEST_VECTOR_DIR);
            break;
        }

    if (failed != 0) {
        ps3_log("FAIL  %d of %d core suites failed on big-endian - their output follows\n",
                failed, RC_CORE_TEST_COUNT);
        replay_captured(RC_CORE_TEST_CAPTURE);
        return 1;
    }

    {
        int ran = 0;
        for (i = 0; i < RC_CORE_TEST_COUNT; i++)
            if (!results[i].skipped)
                ran++;
        ps3_log("ok    %d of %d core suites pass on the PPE - the shared core is byte-order clean\n",
                ran, RC_CORE_TEST_COUNT);
    }
    return 0;
}

/*
 * THE FIRST THING IN THIS PORT THAT TALKS TO A PS5. Everything else has been checked against vectors,
 * captures and reference decodes, all of which are recordings - and a recording cannot refuse a
 * datagram, answer from an address you did not expect, or take longer than you allowed.
 *
 * A console that is off, resting, or on another subnet is not a failure of this program, so finding
 * nothing is reported and not counted against the run. What IS reported either way is how far the
 * socket work got, because "no console answered" and "this port cannot broadcast" look identical from
 * the outside and are entirely different problems.
 */
#ifndef RC_DISCOVER_TIMEOUT_MS
#define RC_DISCOVER_TIMEOUT_MS 3000u
#endif

static int check_discovery(void)
{
    rc_discover_result d;
    int n;
    int i;

    ps3_log("disc:  broadcasting SRCH for %u ms\n", RC_DISCOVER_TIMEOUT_MS);

    n = rc_discover(RC_DISCOVER_TIMEOUT_MS, &d);

    /* The [X] rc_platform.h left open, asked and answered on hardware. Reported whatever discovery
     * found, because it is a fact about the platform rather than about the network. */
    ps3_log("       bind() to port 0: %s%s\n",
            d.bind_port0_ok ? "accepted" : "REFUSED",
            d.bind_port0_ok ? " - the 3DS's restriction does not apply here"
                            : " - fell back to the discovery port");
    if (!d.bind_port0_ok)
        ps3_log("       (errno %d)\n", d.bind_errno);

    /*
     * Whether sin_len is required, which decides whether ports/common needs a change. It builds
     * sockaddr_in in three places and never sets the field, so this is a question about the shared core
     * rather than about this port.
     */
    ps3_log("       sendto with sin_len=0: %s;  with sin_len set: %s\n",
            d.sinlen_zero_send_ok ? "accepted" : "REFUSED",
            d.sinlen_set_send_ok ? "accepted" : "REFUSED");
    if (!d.sinlen_zero_send_ok && d.sinlen_set_send_ok)
        ps3_log("       -> sin_len IS required. ports/common must set it before it can connect here.\n");
    else if (d.sinlen_zero_send_ok)
        ps3_log("       -> sin_len is not required for sendto. ports/common needs no change for this.\n");

    if (!d.socket_ok) {
        ps3_log("FAIL  could not create or configure the broadcast socket\n");
        return 1;
    }
    if (d.probes_sent == 0) {
        ps3_log("FAIL  the socket came up but the SRCH broadcast could not be sent\n");
        return 1;
    }

    ps3_log("       sent %d probe(s), %d datagram(s) back, %d parsed\n",
            d.probes_sent, d.datagrams_rx, d.parsed);

    if (n == 0) {
        ps3_log("       no console answered - not a failure; check it is on the same LAN and awake\n");
        return 0;
    }

    for (i = 0; i < n; i++)
        ps3_log("       %s  %s  %s  id=%s  sysver=%s  %s\n",
                d.console[i].address, d.console[i].host_type, d.console[i].host_name,
                d.console[i].host_id, d.console[i].system_version,
                d.console[i].is_awake ? "awake" : "standby");

    ps3_log("ok    found %d console(s) from the PS3 - discovery works end to end\n", n);
    return 0;
}

/*
 * Wake the console and open the control session. Needs a pairing record, which is dirty-room material -
 * see rc_connect.h. NOTHING BELOW PRINTS ANYTHING FROM IT: not the keys, not the derived credential, not
 * the host address. What it reports is which stage was reached, which is the useful part anyway.
 */
#ifndef RC_CONNECT_WAKE_TIMEOUT_MS
#define RC_CONNECT_WAKE_TIMEOUT_MS 30000u
#endif

/* Printed the moment rc_connect enters a step that can block, so a hang names the call that did not
 * return rather than leaving the log stopping after the previous check. */
static void connect_progress(const char *stage_text)
{
    ps3_log("       .. %s\n", stage_text);
}

static int check_connect(void)
{
    rc_connect_result c;
    rc_connect_stage stage;

    ps3_log("conn:  starting\n");
    stage = rc_connect(RC_CONNECT_WAKE_TIMEOUT_MS, connect_progress, g_log_dirs, LOG_DIR_COUNT, &c);

    if (stage == RC_CONNECT_NO_RECORD) {
        ps3_log("conn:  no pairing record - skipping\n");
        ps3_log("       generate one with `ProtocolLab -- register`, copy it to the console as\n");
        ps3_log("       pairing.txt - that exact name, which is what the core's loader appends;\n");
        ps3_log("       it is per-console and per-account, so it never belongs in this repository.\n");
        ps3_log("       every directory listed in the writable-directory probe above was searched,\n");
        ps3_log("       so any of them will do - the install directory is the one tried first.\n");
        return 0;
    }

    /*
     * Only claims what was observed. An earlier version printed "console was awake" off a flag that was
     * still at its memset default when nothing had answered at all - which read as a successful probe
     * immediately above a line saying no console answered.
     */
    ps3_log("conn:  record loaded from %s; recorded address %s\n",
            c.record_dir != NULL ? c.record_dir : "the compiled-in directory",
            c.host_parsed ? "parses" : "IS NOT A DOTTED QUAD");
    ps3_log("       fcntl(F_SETFL,O_NONBLOCK)=%d, reads back non-blocking: %s; SO_NBIO: %s\n",
            c.fcntl_set_rc,
            c.fcntl_readback_nonblock ? "yes" : "NO - sockets are not newlib fds here",
            c.so_nbio_ok ? "accepted" : "refused");
    ps3_log("       inet_pton: %s   inet_aton: %s   agree: %s\n",
            c.pton_ok ? "ok" : "FAILED",
            c.aton_ok ? "ok" : "FAILED",
            c.aton_matches_pton ? "yes" : "NO - the core uses inet_aton everywhere");

    if (c.unicast_replied)
        ps3_log("       it answered; %s\n", c.was_asleep ? "in standby" : "awake");
    else if (c.broadcast_found && !c.broadcast_matches)
        ps3_log("       it did not answer, but a console answered a BROADCAST from a different\n"
                "       address - the record is stale, not the console missing. Re-register, or\n"
                "       give the console a reservation so its address stops moving.\n");
    else if (c.broadcast_found)
        ps3_log("       it did not answer a unicast SRCH, yet the same address answered a\n"
                "       broadcast - suspect the source port this binds, not the address.\n");
    else
        ps3_log("       nothing answered, unicast or broadcast - console off, or another subnet\n");

    if (c.wakeups_sent > 0) {
        ps3_log("       wake credential derived: %s\n", c.credential_ok ? "yes" : "NO");
        ps3_log("       WAKEUP sent from %s source port\n",
                c.wake_source_bound ? "the spec's" : "an ephemeral");
        if (stage != RC_CONNECT_WAKE_SENT)
            ps3_log("       woke after %u ms (%d SRCH polls)\n", c.woke_after_ms, c.polls);
    }

    ps3_log("       stage reached: %s\n", rc_connect_stage_name(stage));

    switch (stage) {
    case RC_CONNECT_STREAM_KEYS:
        if (c.login_verdict == 0)
            ps3_log("       the console accepted the passcode (LOGIN 0x0005 -> 0x00)\n");
        ps3_log("       senkusha  local 0x%08x  peer 0x%08x  version-ack %s, gating legs %s\n",
                c.senkusha_local_tag, c.senkusha_peer_tag,
                c.senkusha_version_ack ? "yes" : "NO", c.senkusha_complete ? "complete" : "INCOMPLETE");
        ps3_log("       stream    local 0x%08x  peer 0x%08x\n",
                c.takion_local_tag, c.takion_peer_tag);
        ps3_log("       asked for %dx%d @ %d fps (rtt declared 0 - the echo leg is not run yet)\n",
                c.asked_width, c.asked_height, c.asked_fps);
        ps3_log("       protocol version %u (%s), so the curve is %s\n",
                c.stream_version, c.stream_version_acked ? "the console's choice" : "ours - no ack",
                c.curve_p521 ? "P-521" : "P-256");
        ps3_log("       SESSION_REQUEST %u bytes, SESSION_REPLY %u bytes\n",
                c.session_request_bytes, c.session_reply_bytes);
        ps3_log("       the reply's ECDH point verified under the handshake key - that signature\n");
        ps3_log("       check is what stops an injected DATA chunk substituting its own key.\n");
        ps3_log("ok    stream keys derived - the session is negotiated end to end\n");
        return 0;
    case RC_CONNECT_TAKION_UP:
        if (c.login_verdict == 0)
            ps3_log("       the console accepted the passcode (LOGIN 0x0005 -> 0x00)\n");
        ps3_log("       senkusha  local 0x%08x  peer 0x%08x\n",
                c.senkusha_local_tag, c.senkusha_peer_tag);
        ps3_log("       stream    local 0x%08x  peer 0x%08x\n",
                c.takion_local_tag, c.takion_peer_tag);
        ps3_log("       senkusha gating legs: version-ack %s, keyless session %s\n",
                c.senkusha_version_ack ? "yes" : "NO", c.senkusha_complete ? "complete" : "INCOMPLETE");
        ps3_log("FAIL  Takion is up on both channels but the stream SESSION exchange did not finish.\n");
        if (c.session_reply_bytes > 0u) {
            static const char *const kReject[] = {
                "no reason recorded - which should not happen here",
                "bad arguments - a bug on this side, not the console's",
                "it did not parse as a SESSION_REPLY at all",
                "the console REFUSED OUR PROTOCOL VERSION",
                "version accepted, but the reply carried no ECDH key",
                "the ecdhSignature was not 32 bytes",
                "the ecdhSignature DID NOT VERIFY under our handshake key - the console computed"
                " it under a different one, which points at the launch spec's encryption",
                "the console's point LENGTH names a different curve than the one we used",
                "the length agreed and the derivation still failed - this is the crypto, not"
                " the negotiation"
            };
            int why = c.reply_reject_reason;

            ps3_log("      the console's point: %u bytes, first byte 0x%02x"
                    " (65 = P-256, 133 = P-521, 0x04 = uncompressed)\n",
                    c.peer_key_length, c.peer_key_prefix);
            ps3_log("      protocol version %u (%s), curve %s\n",
                    c.stream_version, c.stream_version_acked ? "the console's choice" : "ours - no ack",
                    c.curve_p521 ? "P-521" : "P-256");

            ps3_log("      A SESSION_REPLY of %u bytes DID arrive and was refused - so the console\n",
                    c.session_reply_bytes);
            ps3_log("      answered and we declined it, which is not the same as silence.\n");
            if (why >= 0 && why < (int)(sizeof(kReject) / sizeof(kReject[0])))
                ps3_log("      %s\n", kReject[why]);
            if (c.ecdh_step != 0) {
                static const char *const kEcdhStep[] = {
                    "none", "arguments", "curve", "sizes", "group load", "our private key",
                    "reading the peer point", "checking the peer point",
                    "THE POINT MULTIPLY", "the result was the identity", "writing the result"
                };
                int st = c.ecdh_step;

                ps3_log("      backend step %d (%s), code %d (0x%04x)\n", st,
                        (st >= 0 && st < (int)(sizeof(kEcdhStep) / sizeof(kEcdhStep[0])))
                            ? kEcdhStep[st] : "?",
                        c.ecdh_code, (unsigned)(-c.ecdh_code));
                ps3_log("      the code is mbedtls's own and unmapped - -0x4c80 is INVALID_KEY,\n");
                ps3_log("      -0x4d80 is ALLOC_FAILED.\n");
            }
            if (c.peer_key_length > 0u && c.peer_key_length <= sizeof(c.peer_key)) {
                /*
                 * The point itself. An ephemeral public key for one session - no secret, no account, no
                 * console identity - printed so it can be checked off the console, because the four
                 * P-521 vectors sitting on this machine pass the check this point fails.
                 */
                unsigned i;

                ps3_log("      control: a known-good P-521 vector point %s here; the console's %s\n",
                        c.control_point_ok ? "PASSES" : "FAILS",
                        c.peer_point_ok ? "PASSES" : "FAILS");
                if (!c.control_point_ok)
                    ps3_log("      control failed at step %d code %d - so this is the call site, not the key\n",
                            c.control_step, c.control_code);
                ps3_log("      peer point, for off-console analysis:\n      ");
                for (i = 0u; i < c.peer_key_length; i++) {
                    ps3_log("%02x", c.peer_key[i]);
                    if (((i + 1u) % 32u) == 0u && (i + 1u) < c.peer_key_length)
                        ps3_log("\n      ");
                }
                ps3_log("\n");
            }
        } else if (c.session_request_bytes > 0u) {
            ps3_log("      SESSION_REQUEST went out (%u bytes, %s) and nothing came back. If the\n",
                    c.session_request_bytes, c.curve_p521 ? "P-521" : "P-256");
            ps3_log("      senkusha gating legs above are incomplete, suspect those first.\n");
        } else {
            /*
             * Name the step that failed rather than the set of candidates. The same sequence with the
             * same parameters and buffers succeeds on the host, so "one of these three" was never going
             * to be enough to act on.
             */
            static const char *const kStep[] = {
                "the handshake key could not be drawn - the CSPRNG refused 16 bytes",
                "the launch spec JSON would not build (resolution ladder, or the buffer)",
                "the launch spec would not encrypt-and-base64",
                "SESSION_REQUEST would not build - this is the ECDH keygen",
                "SESSION_REQUEST was built but the channel refused to send it",
                "SESSION_REQUEST went out and no SESSION_REPLY came back"
            };
            int step = c.stream_build_step;

            ps3_log("      spec %u bytes, base64 %u bytes, step reached %d\n",
                    c.launch_spec_bytes, c.launch_spec_b64_bytes, step);
            if (step >= 0 && step < (int)(sizeof(kStep) / sizeof(kStep[0])))
                ps3_log("      %s\n", kStep[step]);
        }
        return 1;
    case RC_CONNECT_SENKUSHA_UP:
        ps3_log("       senkusha  local 0x%08x  peer 0x%08x\n",
                c.senkusha_local_tag, c.senkusha_peer_tag);
        ps3_log("FAIL  senkusha came up but the stream channel's Takion handshake did not. The\n");
        ps3_log("      console answered on one UDP port and not the other, which is a different\n");
        ps3_log("      problem from never answering at all.\n");
        return 1;
    case RC_CONNECT_SESSION_READY:
        if (c.login_verdict == 0)
            ps3_log("       the console accepted the passcode (LOGIN 0x0005 -> 0x00)\n");
        ps3_log("FAIL  the console is willing to stream but senkusha's Takion handshake never\n");
        ps3_log("      completed - no INIT_ACK. The control plane is healthy, so this is the UDP\n");
        ps3_log("      leg specifically.\n");
        return 1;
    case RC_CONNECT_SESSION_OPEN:
        ps3_log("       %d control frame(s) while waiting; first 0x%04x, last 0x%04x, %d heartbeat(s)\n",
                c.frames_seen, c.first_type, c.last_type, c.heartbeats);
        if (c.login_prompt && c.login_verdict == 1) {
            ps3_log("FAIL  the console REJECTED the passcode in the pairing record. That is its own\n");
            ps3_log("      answer, not a timeout - correct `pin=` and re-run.\n");
        } else if (c.login_prompt && c.login_verdict == 2) {
            ps3_log("FAIL  the console answered the passcode with a verdict byte nobody has seen\n");
            ps3_log("      before - neither 0x00 nor 0x01. Worth a look rather than a retry.\n");
        } else if (c.login_prompt && c.login_verdict == 0) {
            ps3_log("FAIL  the console ACCEPTED the passcode and then sent no SESSION_ID within the\n");
            ps3_log("      deadline. The reference sees session-ready ~2.3 s after a LAN submit, so\n");
            ps3_log("      this is the console being slow or the session stalling after login - it\n");
            ps3_log("      is NOT a bad passcode.\n");
        } else if (c.login_prompt && c.login_submitted) {
            ps3_log("FAIL  the passcode went back to the console and nothing returned - no verdict,\n");
            ps3_log("      no SESSION_ID. The console went quiet rather than saying no.\n");
        } else if (c.login_prompt) {
            ps3_log("       the console wants a sign-in passcode and none was supplied. Either put\n");
            ps3_log("       `pin=<digits>` in the pairing record beside the console, or sign in on\n");
            ps3_log("       the console, leave it on the home screen, and re-run.\n");
        } else if (c.frames_seen == 0) {
            ps3_log("FAIL  the channel opened and the console said nothing at all - not even a\n");
            ps3_log("      heartbeat, which it normally sends within seconds. Suspect the channel.\n");
        } else {
            ps3_log("FAIL  the channel is live (frames arriving) but no SESSION_ID in 20 s\n");
        }
        return 1;
    case RC_CONNECT_AWAKE:
        ps3_log("FAIL  console is awake but the control session would not open\n");
        return 1;
    case RC_CONNECT_WAKE_SENT:
        ps3_log("FAIL  it did not wake within %u ms\n", RC_CONNECT_WAKE_TIMEOUT_MS);
        return 1;
    default:
        ps3_log("FAIL  %s\n", rc_connect_stage_name(stage));
        return 1;
    }
}

static int check_decode(void)
{
    rc_decode_probe_result r;
    uint64_t hz = rc_tick_hz();
    int i;

    if (!rc_decode_probe(RC_DECODE_STREAM_PATH, RC_DECODE_FRAMES, &r)) {
        if (!r.opened) {
            /* Not a failure - see above. */
            ps3_log("dec:   no stream at %s - skipping (copy the capture there to run it)\n",
                    RC_DECODE_STREAM_PATH);
            return 0;
        }
        ps3_log("FAIL  openh264 read %u bytes and produced no frame\n", (unsigned)r.bytes);
        ps3_log("      initialised=%d nals=%d frames=%d last_error=%ld\n",
                r.initialised, r.nals_fed, r.frames_out, (long)r.last_error);
        return 1;
    }

    ps3_log("dec:   %u bytes, %d NALs fed, %d frames out, %dx%d\n",
            (unsigned)r.bytes, r.nals_fed, r.frames_out, r.width, r.height);
    for (i = 0; i < r.hashes; i++)
        ps3_log("       frame %3d  0x%016llx\n", i, (unsigned long long)r.hash[i]);

    if (r.frames_out > 0 && r.decode_ticks > 0u) {
        uint64_t us = r.decode_ticks * 1000000ULL / hz;
        uint64_t per_frame_us = us / (uint64_t)r.frames_out;
        /* Tenths, because integer fps loses the difference between 4 and 4.9 and this number is about
         * to be multiplied by four to guess at 720p. */
        uint64_t fps_tenths = (per_frame_us > 0u) ? (10000000ULL / per_frame_us) : 0u;

        ps3_log("       PPE alone: %llu frames in %llu ms, %llu us/frame, %llu.%llu fps\n",
                (unsigned long long)r.frames_out,
                (unsigned long long)(us / 1000ULL),
                (unsigned long long)per_frame_us,
                (unsigned long long)(fps_tenths / 10ULL),
                (unsigned long long)(fps_tenths % 10ULL));
        ps3_log("       (hashing %d frames cost %llu ms and is NOT in the above)\n",
                r.hashes, (unsigned long long)(r.hash_ticks * 1000000ULL / hz / 1000ULL));
        ps3_log("       (this is %dx%d - 720p is ~4x the pixels)\n", r.width, r.height);
    }

    ps3_log("ok    openh264 decoded on the PPE - compare the hashes with the reference decode\n");
    return 0;
}

int main(void)
{
    int failures = 0;
    int chosen;
    int lv2_dir;
    int i;

    /*
     * Pick a log directory by trying them, not by believing one. See RC_PS3_LOG_DIRS above for why.
     *
     * rc_log_open takes a path and uses its directory part, so a string that already ends in '/' names
     * itself - that is rc_program_dir's documented behaviour, not a trick. Passing NULL would take the
     * Makefile's compile-time fallback instead, which is exactly the assumption that produced a silent
     * first run.
     */
    /*
     * THE BEACON. Literally the first thing, and deliberately the stupidest thing in this file.
     *
     * Two runs have now produced no output whatsoever, and each time the question was the same: did the
     * program not start, or did it start and fail to tell us? Every answer this file gives costs stack -
     * a path buffer, a snprintf, a call into rc_log - and if the stack is what is wrong then every one
     * of them is unavailable precisely when it is needed.
     *
     * So this uses a string literal, one s32, and one syscall. No buffer, no formatting, no helper. If
     * ripcord-alive.txt exists after a run, main() was entered and lv2 accepted a write, and everything
     * after this point is an ordinary bug. If it does not, the program is dying before or at its first
     * instruction and no amount of logging machinery downstream would ever have shown it.
     *
     * It is not diagnostic scaffolding to be removed once this is solved. It costs one syscall at
     * startup and it is the only thing in the program that can distinguish "did not run" from "ran
     * badly", which is the distinction that cost the most time here.
     */
    {
        s32 beacon_fd = -1;
        if (sysLv2FsOpen("/dev_hdd0/ripcord-alive.txt",
                         SYS_O_WRONLY | SYS_O_CREAT | SYS_O_TRUNC,
                         &beacon_fd, 0666u, NULL, 0u) == 0) {
            u64 wrote = 0u;
            /* The build id goes in the beacon too. It is the one artifact that survives every failure
             * mode below, so it is the one that most needs to say which binary produced it. */
            (void)sysLv2FsWrite(beacon_fd, RC_PS3_BUILD_ID " main() entered\n",
                                (u64)(sizeof(RC_PS3_BUILD_ID " main() entered\n") - 1u), &wrote);
            (void)sysLv2FsClose(beacon_fd);
        }
    }

    /*
     * THE NETWORK CHANNEL FIRST OF ALL, because it is the only one that needs no write permission
     * anywhere. A program launched by ps3load transfers, spawns, blacks the screen and writes nothing to
     * disk; if its sandbox is what denies the file channels, this is the only voice it has.
     *
     * RC_NETLOG_HOST and RC_NETLOG_PORT come from the Makefile. Failure is ignored: a console with no
     * network is still a console worth running the rest of these checks on.
     */
    (void)rc_netlog_open(RC_NETLOG_HOST, RC_NETLOG_PORT);

    /* THE LV2 CHANNEL FIRST of the file channels, because it is the one that has to work. Opened before anything else in
     * the program so that a crash after this point still leaves a file behind - an empty
     * ps3-bringup-lv2.log is itself the finding that main() was entered. */
    for (lv2_dir = 0; lv2_dir < LOG_DIR_COUNT; lv2_dir++) {
        if (lv2_log_open(g_log_dirs[lv2_dir], "ps3-bringup-lv2.log"))
            break;
    }

    for (chosen = 0; chosen < LOG_DIR_COUNT; chosen++) {
        if (dir_accepts_a_file(g_log_dirs[chosen], "ps3-bringup.log"))
            break;
    }

    if (chosen < LOG_DIR_COUNT) {
        rc_log_open(g_log_dirs[chosen], "ps3-bringup.log");
    } else {
        /* Nothing took a file through newlib. That is a finding, not a fallback - it is reported in the
         * table below, and the lv2 channel above is what carries this run's output. */
        rc_log_open(NULL, "ps3-bringup.log");
    }

    ps3_log("ripcord-ps3 platform bring-up, build %s\n", RC_PS3_BUILD_ID);
    ps3_log("=========================================\n");
    ps3_log("If that build id is not the one `make` just printed, the console is running a stale\n");
    ps3_log("install and nothing below this line means anything.\n\n");

    /* The table, logged rather than merely acted on. This is the first thing a PS3 has ever been asked
     * about this port, and "which directories may a packaged homebrew write to" is worth answering once
     * and keeping. */
    ps3_log("log:   channels carrying this run\n");
    ps3_log("       [%c] udp to %s:%u  (first sendto returned %ld)\n",
            rc_netlog_is_open() ? 'x' : ' ', RC_NETLOG_HOST, (unsigned)RC_NETLOG_PORT,
            rc_netlog_first_send_result());
    ps3_log("       [%c] lv2 syscalls (sysLv2FsOpen)   %s\n",
            (g_lv2_fd >= 0) ? 'x' : ' ',
            (g_lv2_dir != NULL) ? g_lv2_dir : "- nowhere accepted a file");
    ps3_log("       [%c] newlib stdio (fopen)          %s\n",
            (chosen < LOG_DIR_COUNT) ? 'x' : ' ',
            (chosen < LOG_DIR_COUNT) ? g_log_dirs[chosen] : "- ENOSYS everywhere, see main.c");
    ps3_log("\n");

    ps3_log("log:   writable-directory probe, in preference order\n");
    for (i = 0; i < LOG_DIR_COUNT; i++) {
        int fop = dir_accepts_a_file(g_log_dirs[i], "ps3-bringup.log");
        /* Both channels asked about the same directory. Where they disagree, the layer is the problem
         * rather than the path - which is the single most useful thing this run can establish. */
        ps3_log("       fopen[%c] lv2[%c] %s%s\n",
               fop ? 'x' : ' ',
               (i == lv2_dir) ? 'x' : '?',
               g_log_dirs[i],
               (i == chosen) ? "   <- newlib log" : "");
    }
    ps3_log("\n");

    /* The timestamp step 4 promised. It is also the first thing that proves the seam linked at all. */
    ps3_log("boot:  rc_time_ms() = %llu ms since power-on\n", (unsigned long long)rc_time_ms());
    ps3_log("       rc_tick()    = %llu\n\n", (unsigned long long)rc_tick());

    failures += measure_timebase();
    failures += check_monotonic();
    failures += check_csprng();
    failures += check_spu();
    failures += check_core();
    failures += check_discovery();
    failures += check_connect();
    failures += check_decode();

    ps3_log("\nnot covered here: the rest of the decoder. See README.md.\n");
    ps3_log("%s\n", failures == 0 ? "all checks passed" : "CHECKS FAILED");
    /* The generator was opened by the CSPRNG check and used by everything after it - see the note
     * there. It is closed here, with the other process-wide resources, rather than by any one check. */
    rc_random_exit();
    lv2_log_close();
    rc_log_close();
    rc_netlog_close();

    return failures == 0 ? 0 : 1;
}
