using System.Text;
using System.Text.Json;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Xunit;

namespace Ripcord.Protocol.Halyard.Tests;

/// <summary>
/// Validates the v1 registration key exchange against real captured ground truth: the variant lookup table
/// extracted from our own client binary plus live (request-context, PIN) → key and → response vectors. This
/// is extracted/interop material that stays in the gitignored dirty room, so these tests load a local
/// fixture and <see cref="Assert.SkipUnless"/> when it is absent — CI stays green, no secrets committed.
///
/// <para>
/// Fixture: <c>docs/protocol/captures/registration_crypto_vectors.json</c> (gitignored; generated by
/// <c>gen_registration_fixture.py</c>). When present, this upgrades the registration key exchange from
/// "[V] in the Python reference" to "[V] in our C# implementation".
/// </para>
/// </summary>
public class LiveRegistrationVectorTests
{
    private static readonly string FixturePath = LocateFixture();

    [SkippableFact]
    public void RegistrationKey_ReproducesCapturedKeys()
    {
        var fx = LoadOrSkip();
        var kdf = new HalyardRegistrationKdf(
            new HalyardRegistrationSecrets(Hex.Bytes(fx.RegistrationTable!), fx.SelectorOffset));

        Assert.NotEmpty(fx.KeyVectors!);
        foreach (var v in fx.KeyVectors!)
        {
            var key = kdf.DeriveKey(Hex.Bytes(v.Context), v.Passcode);
            Assert.Equal(v.Key, Hex.String(key));   // derived from wire context + PIN == captured key
        }
    }

    /// <summary>
    /// The account ("web"/no-PIN) seed delivery, against a captured console reply.
    ///
    /// <para>
    /// <b>Why this had to exist.</b> Every other seed-delivery test is a round trip through our own code —
    /// <c>SealSeed</c> then <c>RecoverSeed</c>, sharing the key, the material, the counter and the context key.
    /// A round trip like that passes whichever of those four is wrong, so it proved the pair consistent and
    /// nothing about whether either matches a console. This vector is the console's own <c>customData1</c> and
    /// the seed the vendor client actually derived from it, so it fails if any element of the schedule drifts.
    /// </para>
    ///
    /// <para>
    /// Note the ciphertext is <b>17</b> bytes for a 16-byte seed — true of every captured value — so the
    /// "first 16 bytes" rule is part of what is being pinned here, not an assumption around it.
    /// </para>
    /// </summary>
    [SkippableFact]
    public void AccountSeedDelivery_ReproducesTheConsolesDeliveredSeed()
    {
        var fx = LoadOrSkip();
        Skip.If(fx.SeedVectors is null or { Count: 0 }, "fixture carries no account seed-delivery vectors");

        foreach (var v in fx.SeedVectors!)
        {
            byte[] seed = HalyardAccountSeedDelivery.RecoverSeed(
                Hex.Bytes(v.Data1), Hex.Bytes(v.Data2), v.CustomData1, Hex.Bytes(fx.ContextKey!));

            Assert.Equal(v.ExpectSeed, Hex.String(seed));
        }
    }

    [SkippableFact]
    public void RegistrationResponse_DecryptsToPairingRecord()
    {
        var fx = LoadOrSkip();
        var kdf = new HalyardRegistrationKdf(
            new HalyardRegistrationSecrets(Hex.Bytes(fx.RegistrationTable!), fx.SelectorOffset));
        var cipher = new HalyardRegistrationCipher(kdf, Hex.Bytes(fx.ContextKey!));

        Assert.NotEmpty(fx.ResponseVectors!);
        foreach (var v in fx.ResponseVectors!)
        {
            var plain = cipher.DecryptWith(
                Hex.Bytes(v.Context), v.Passcode, Hex.Bytes(v.Material), Hex.Bytes(v.ResponseBody));
            var text = Encoding.ASCII.GetString(plain);
            Assert.Contains(v.ExpectContains!, text);

            // and the existing message parser turns it into a pairing record
            Assert.True(Common.Crypto.HalyardRegistrationMessage.TryParsePairingRecord(plain, out var record));
            Assert.NotNull(record);
        }
    }

    [SkippableFact]
    public void RegistrationResponse_RecoversCredentials_EvenWithWrongMaterial()
    {
        // The pairing credentials (PS5-RegistKey + RP-Key/companion) ride in CFB blocks 1+, which are
        // IV/material-independent. So even if the per-pairing material is wrong (only block 0 — the AP-Bssid
        // line — is affected), the registkey + companion still decrypt and parse. This is what lets the
        // client recover credentials without solving the send-side material mechanism.
        var fx = LoadOrSkip();
        var kdf = new HalyardRegistrationKdf(
            new HalyardRegistrationSecrets(Hex.Bytes(fx.RegistrationTable!), fx.SelectorOffset));
        var cipher = new HalyardRegistrationCipher(kdf, Hex.Bytes(fx.ContextKey!));

        foreach (var v in fx.ResponseVectors!)
        {
            var plain = cipher.DecryptWith(
                Hex.Bytes(v.Context), v.Passcode, new byte[16] /* deliberately wrong material */,
                Hex.Bytes(v.ResponseBody));
            Assert.True(Common.Crypto.HalyardRegistrationMessage.TryParsePairingRecord(plain, out var record));
            Assert.NotNull(record);
            Assert.Equal(16, record!.Companion.Length);        // RP-Key recovered from an IV-free block
            Assert.NotEmpty(record.RegistrationKey);
        }
    }

    [SkippableFact]
    public void BuildRequest_RoundTrips_ConsoleSideRecovery()
    {
        // The send side: BuildRequest scatters the wrapped material into the context. The console recovers it
        // (GatherWrapped -> UnwrapMaterial), derives the same key, and decrypts the field. A clean round-trip
        // proves the wrap transform + scatter offsets match what the console reverses.
        var fx = LoadOrSkip();
        Skip.If(fx.MaterialWrapTable is null, "Material wrap table absent from fixture (send-side path not exercised).");

        var kdf = new HalyardRegistrationKdf(new HalyardRegistrationSecrets(
            Hex.Bytes(fx.RegistrationTable!), fx.SelectorOffset, Hex.Bytes(fx.MaterialWrapTable!)));
        var cipher = new HalyardRegistrationCipher(kdf, Hex.Bytes(fx.ContextKey!));

        const string passcode = "48169600";
        byte[] fieldPlain = Encoding.ASCII.GetBytes(
            "Client-Type: dabfa2ec873de5839bee8d3f4c0239c4282c07c25c6077a2931afcf0adc0d34f\r\nNp-AccountId: AAAAAAAAAAA=\r\n");

        var exchange = cipher.BuildRequest(passcode, fieldPlain);

        // Split the body exactly as the console does: [0x1e0 context][field].
        var context = exchange.RequestBody.AsSpan(0, HalyardRegistrationCipher.ContextLength).ToArray();
        var field = exchange.RequestBody.AsSpan(HalyardRegistrationCipher.ContextLength).ToArray();

        // Console side: recover the material purely from the transmitted context, then decrypt the field.
        byte[] material = cipher.RecoverMaterial(context);
        byte[] recovered = cipher.DecryptWith(context, HalyardRegistrationKdf.ParsePasscode(passcode), material, field);

        Assert.Equal(fieldPlain, recovered);
    }

    private static Fixture LoadOrSkip()
    {
        Skip.IfNot(File.Exists(FixturePath),
            $"Dirty-room fixture not present ({FixturePath}). Run gen_registration_fixture.py in captures/ to enable.");
        return JsonSerializer.Deserialize<Fixture>(File.ReadAllText(FixturePath), JsonOpts)
               ?? throw new InvalidOperationException("Fixture failed to deserialize.");
    }

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    private static string LocateFixture()
    {
        // Explicit override first, matching the production loader's RIPCORD_REGIST_FIXTURE.
        string? env = Environment.GetEnvironmentVariable("RIPCORD_REGIST_FIXTURE");
        if (!string.IsNullOrEmpty(env) && File.Exists(env))
            return env;

        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8 && dir is not null; i++)
        {
            var candidate = Path.Combine(dir, "docs", "protocol", "captures", "registration_crypto_vectors.json");
            if (File.Exists(candidate))
                return candidate;
            dir = Directory.GetParent(dir)?.FullName;
        }
        return Path.Combine(AppContext.BaseDirectory, "registration_crypto_vectors.json"); // absent -> skip
    }

    private sealed class Fixture
    {
        public string? RegistrationTable { get; set; }
        public string? MaterialWrapTable { get; set; }
        public int SelectorOffset { get; set; }
        public string? ContextKey { get; set; }
        public List<KeyVector>? KeyVectors { get; set; }
        public List<ResponseVector>? ResponseVectors { get; set; }
        public List<SeedVector>? SeedVectors { get; set; }
    }

    /// <summary>
    /// One account-route seed delivery as captured: the client's ephemeral <c>data1</c>/<c>data2</c> from the
    /// cloud command, the console's <c>customData1</c> from the push channel, and the seed the vendor client
    /// derived from them.
    /// </summary>
    private sealed class SeedVector
    {
        public string Source { get; set; } = "";
        public string Data1 { get; set; } = "";
        public string Data2 { get; set; } = "";
        public string CustomData1 { get; set; } = "";
        public string ExpectSeed { get; set; } = "";
    }

    private sealed class KeyVector
    {
        public string Context { get; set; } = "";
        public uint Passcode { get; set; }
        public string Key { get; set; } = "";
    }

    private sealed class ResponseVector
    {
        public string Context { get; set; } = "";
        public uint Passcode { get; set; }
        public string Material { get; set; } = "";
        public string ResponseBody { get; set; } = "";
        public string? ExpectContains { get; set; }
    }
}
