using System.Text;
using System.Text.Json;
using Ripcord.Protocol.Halyard.Common.Crypto;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Ripcord.Protocol.Halyard.Session;
using Xunit;

namespace Ripcord.Protocol.Halyard.Tests;

/// <summary>
/// The account ("web"/no-PIN) route's key path, against three captured sessions.
///
/// <para>
/// <b>Why this suite had to exist.</b> Every other test of this path was a self-round-trip: the seed tests
/// sealed and recovered with the same four parameters, and the request builder was only ever checked against
/// its own output. So "the seed is recovered correctly" and "the transport key is <c>seed XOR
/// registrationTable[selector]</c>" were both believed without either being run against the console's own
/// bytes from the same session. When a live registration came back <c>403</c>, nothing in the suite could say
/// which link was wrong.
/// </para>
///
/// <para>
/// Each vector pairs the cloud half with the wire half of <em>one</em> session: the <c>data1</c>/<c>data2</c>
/// the client sent in the <c>commands</c> call, the <c>customData1</c> the console published in reply, and the
/// <c>/sess/rgst</c> request body that client then sent (480-byte context + 107-byte encrypted field, taken
/// chunk-aligned off 9303). Nothing here is generated by our own code.
/// </para>
///
/// <para>
/// Fixture: <c>docs/protocol/captures/account_key_path_vectors.json</c> (gitignored — real per-session
/// material), so these self-skip on a clean checkout.
/// </para>
/// </summary>
public class LiveAccountKeyPathVectorTests
{
    [SkippableFact]
    public void RecoverMaterial_ReproducesTheMaterialTheCapturedClientUsed()
    {
        // The PIN-route vectors carry the material explicitly alongside the context that wraps it, so this is
        // a direct check of the unwrap with nothing else in the way. It had never been asserted: every other
        // vector passes the material in rather than recovering it.
        string path = Path.Combine(
            RepoRoot(), "docs", "protocol", "captures", "registration_crypto_vectors.json");
        Skip.IfNot(File.Exists(path), $"Dirty-room fixture not present: {path}");

        using JsonDocument doc = JsonDocument.Parse(File.ReadAllText(path));
        HalyardRegistrationCipher cipher = CipherOrSkip(out _);

        foreach (JsonElement v in doc.RootElement.GetProperty("ResponseVectors").EnumerateArray())
        {
            byte[] context = Convert.FromHexString(v.GetProperty("Context").GetString()!);
            byte[] expected = Convert.FromHexString(v.GetProperty("Material").GetString()!);

            Assert.Equal(expected, cipher.RecoverMaterial(context));
        }
    }

    [SkippableFact]
    public void TheSeedFromTheCloud_DerivesTheKeyThatDecryptsTheSameSessionsRequest()
    {
        // THE assertion this suite exists for, and it now holds: the seed recovered from the console's
        // customData1 derives a key that correctly decrypts the same session's captured request field.
        //
        // Asserted from offset 16 rather than 0 on purpose. The field cipher is AES-128-CFB128, where the
        // first plaintext block depends on the IV and every block after it depends on the key alone. So this
        // is exactly the statement "the key derivation is right", isolated from the IV — and the IV is
        // separately known to be wrong (see TheFieldIvIsNotYetDerivable below). Three independent sessions.
        Fixture fx = LoadOrSkip();
        HalyardRegistrationCipher cipher = CipherOrSkip(out var bundled);

        Assert.Equal(3, fx.Vectors!.Count);
        foreach (Vector v in fx.Vectors)
        {
            byte[] plain = DecryptCapturedField(cipher, bundled, v);
            byte[] expected = Encoding.ASCII.GetBytes(
                "Client-Type: " + HalyardRegistrationMessage.ClientTypeHex);

            Assert.Equal(expected[16..], plain[16..expected.Length]);
        }
    }

    [SkippableFact]
    public void TheFieldIvIsNotYetDerivable_AndTheseAreTheKnownAnswers()
    {
        // The open question, pinned so it stays measurable and so the algebra never has to be redone.
        //
        // Exactly bytes 0..15 of every captured account request fail to decrypt, and nothing after them —
        // which localises the fault to the field IV. Because CFB gives C0 = P0 XOR E_K(IV) and P0 is known,
        // the IV the sender actually used follows exactly: IV = D_K(P0 XOR C0). Those three values are in the
        // fixture. What is NOT known is how the sender arrived at them: it is not
        // HMAC(<any of the four bundled context keys>, X || be64(0..4095)) for X in {the wrapped material,
        // the seed, data1, data2, the derived key, the raw registration-table entry, any 16-byte window of
        // the context}, nor any of the 32 wrap-table entries under any bias or offset-order variant.
        //
        // Ripcord therefore encrypts its own request's first block under an IV the console does not expect,
        // the console reads garbage where "Client-Type: " should be, and refuses with 403 / 80108b09.
        Fixture fx = LoadOrSkip();
        HalyardRegistrationCipher cipher = CipherOrSkip(out var bundled);

        foreach (Vector v in fx.Vectors!)
        {
            Skip.If(string.IsNullOrEmpty(v.SolvedFieldIv), "Fixture predates solvedFieldIv.");

            byte[] context = Convert.FromHexString(v.Context!);
            byte[] ours = HalyardFieldIv.Derive(
                bundled.ContextKey, cipher.RecoverMaterial(context), HalyardRegistrationCipher.FieldCounter);

            // The IV we send is not the one the console expects. When that stops being true, this test fails
            // and should be deleted along with the workaround it documents.
            Assert.NotEqual(Convert.FromHexString(v.SolvedFieldIv!), ours);

            // And the first block is the only thing wrong: proof the fault is the IV and not the key.
            byte[] plain = DecryptCapturedField(cipher, bundled, v);
            byte[] expected = Encoding.ASCII.GetBytes(
                "Client-Type: " + HalyardRegistrationMessage.ClientTypeHex);
            Assert.NotEqual(expected[..16], plain[..16]);
        }
    }

    private static byte[] DecryptCapturedField(
        HalyardRegistrationCipher cipher,
        (HalyardRegistrationSecrets Secrets, byte[] ContextKey, int VersionSelector) bundled,
        Vector v)
    {
        byte[] seed = HalyardAccountSeedDelivery.RecoverSeed(
            Convert.FromBase64String(v.Data1!),
            Convert.FromBase64String(v.Data2!),
            HalyardAccountSeedDelivery.DecodeCustomData1(v.CustomData1!),
            bundled.ContextKey);

        byte[] context = Convert.FromHexString(v.Context!);
        return cipher.DecryptAccountField(
            context, seed, cipher.RecoverMaterial(context), Convert.FromHexString(v.RequestField!));
    }

    private static HalyardRegistrationCipher CipherOrSkip(
        out (HalyardRegistrationSecrets Secrets, byte[] ContextKey, int VersionSelector) bundled)
    {
        var b = HalyardInteropConstants.Registration(HalyardConsolePlatform.Ps5);
        Skip.If(b is null, "Build omitted the interop constants (-p:BundleInteropConstants=false).");
        bundled = b!.Value;
        return new HalyardRegistrationCipher(
            new HalyardRegistrationKdf(bundled.Secrets, bundled.VersionSelector), bundled.ContextKey);
    }

    private static Fixture LoadOrSkip()
    {
        string path = Path.Combine(
            RepoRoot(), "docs", "protocol", "captures", "account_key_path_vectors.json");
        Skip.IfNot(File.Exists(path), $"Dirty-room fixture not present: {path}");
        return JsonSerializer.Deserialize<Fixture>(
                   File.ReadAllText(path),
                   new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
               ?? throw new InvalidOperationException("Fixture failed to deserialize.");
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Ripcord.slnx")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName ?? Directory.GetCurrentDirectory();
    }

    private sealed class Fixture
    {
        public List<Vector>? Vectors { get; set; }
    }

    private sealed class Vector
    {
        public string? Source { get; set; }
        public string? Context { get; set; }
        public string? RequestField { get; set; }
        public string? Data1 { get; set; }
        public string? Data2 { get; set; }
        public string? CustomData1 { get; set; }
        public string? SolvedFieldIv { get; set; }
    }
}
