using System.Text.Json;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Xunit;

namespace Ripcord.Protocol.Halyard.Tests;

/// <summary>
/// Pins the <b>control-plane GMAC AAD rule</b> (spec §5.5b) against real captured packets: control zeroes the
/// 4-byte key_pos field <i>in addition to</i> the 4-byte tag, unlike A/V and feedback which zero only the tag.
///
/// <para>Settled 2026-08-02 by recomputing the MAC over <c>cap3</c> with that session's dumped stream keys —
/// 727/727 authenticated type-0 packets reproduce with tag+key_pos zeroed, and the tag-only rule matches none
/// of the discriminating ones. That result previously lived only in prose; this is what makes it executable.
/// Complements <see cref="LiveStreamKeyVectorTests"/>, which pins the key <i>schedule</i> that produces the
/// keys used here — together they cover the chain from ECDH shared secret through to an authenticated packet.
/// </para>
///
/// <para>Fixture: <c>docs/protocol/captures/stream_packet_vectors.json</c> (gitignored; generated by
/// <c>make_stream_packet_vectors.py</c>). It holds real session keys and real packet bytes, so it stays in the
/// dirty room and these tests <see cref="Skip"/> when it is absent — CI stays green, no secrets committed.</para>
/// </summary>
public class LiveStreamPacketVectorTests
{
    private static readonly string FixturePath = LocateFixture();

    /// <summary>Every captured control packet's on-wire tag reproduces under the tag+key_pos AAD rule.</summary>
    [SkippableFact]
    public void ControlGmac_ReproducesCapturedTags()
    {
        var fx = LoadOrSkip();
        int checkedPackets = 0;

        foreach (var (name, dir) in fx.EnumerateDirections())
        {
            var crypto = new HalyardPacketCrypto(Hex.Bytes(dir.AesKey!), Hex.Bytes(dir.BaseIv!));
            foreach (var v in dir.Packets!)
            {
                byte[] packet = Hex.Bytes(v.Packet!);
                byte[] tag = crypto.ComputeTag(v.KeyPos, packet, fx.ControlTagOffset, zeroKeyPos: true);
                Assert.Equal(v.Tag, Hex.String(tag));
                checkedPackets++;
            }
        }

        Assert.True(checkedPackets > 0, "Fixture contained no packets.");
    }

    /// <summary>
    /// The negative control, and the assertion that actually pins the <i>rule</i> rather than merely "some AAD
    /// reproduces": zeroing only the tag — the A/V rule — must NOT reproduce these tags. Without this, flipping
    /// <c>zeroKeyPos</c> to false would still be caught only by chance. The fixture generator deliberately
    /// excludes <c>key_pos == 0</c> packets, where the two rules are byte-identical and discriminate nothing.
    /// </summary>
    [SkippableFact]
    public void ControlGmac_TagOnlyAad_DoesNotReproduceTags()
    {
        var fx = LoadOrSkip();
        int discriminating = 0;

        foreach (var (name, dir) in fx.EnumerateDirections())
        {
            var crypto = new HalyardPacketCrypto(Hex.Bytes(dir.AesKey!), Hex.Bytes(dir.BaseIv!));
            foreach (var v in dir.Packets!)
            {
                Assert.NotEqual(0u, v.KeyPos); // a zero key_pos would make the two rules identical
                byte[] packet = Hex.Bytes(v.Packet!);
                byte[] tagOnly = crypto.ComputeTag(v.KeyPos, packet, fx.ControlTagOffset, zeroKeyPos: false);
                Assert.NotEqual(v.Tag, Hex.String(tagOnly));
                discriminating++;
            }
        }

        Assert.True(discriminating > 0, "Fixture contained no discriminating packets.");
    }

    /// <summary>
    /// Congestion (base type 0x05, tag @7, key_pos @0xb) follows the SAME rule as control — measured, not
    /// assumed by analogy. Vectors come from a different session than the control ones above (congestion
    /// packets only exist in a capture that reached streaming), hence their own keys in the fixture.
    ///
    /// <para>Both directions asserted for the same reason as control: reproducing under tag+key_pos proves
    /// little on its own unless the tag-only rule is also shown to fail.</para>
    /// </summary>
    [SkippableFact]
    public void CongestionGmac_ReproducesCapturedTags_AndTagOnlyDoesNot()
    {
        var fx = LoadOrSkip();
        Skip.If(fx.Congestion is null, "Fixture has no congestion section (regenerate to run).");
        var c = fx.Congestion!;
        int checkedPackets = 0;

        foreach (var dir in c.Directions!.Values)
        {
            var crypto = new HalyardPacketCrypto(Hex.Bytes(dir.AesKey!), Hex.Bytes(dir.BaseIv!));
            foreach (var v in dir.Packets!)
            {
                Assert.NotEqual(0u, v.KeyPos); // else the two rules coincide and nothing is proven
                byte[] packet = Hex.Bytes(v.Packet!);

                byte[] both = crypto.ComputeTag(v.KeyPos, packet, c.TagOffset, zeroKeyPos: true);
                Assert.Equal(v.Tag, Hex.String(both));

                byte[] tagOnly = crypto.ComputeTag(v.KeyPos, packet, c.TagOffset, zeroKeyPos: false);
                Assert.NotEqual(v.Tag, Hex.String(tagOnly));
                checkedPackets++;
            }
        }

        Assert.True(checkedPackets > 0, "Fixture congestion section contained no packets.");
    }

    private static Fixture LoadOrSkip()
    {
        Skip.IfNot(File.Exists(FixturePath),
            $"Dirty-room fixture not present ({FixturePath}). Run make_stream_packet_vectors.py to generate it.");
        var json = File.ReadAllText(FixturePath);
        return JsonSerializer.Deserialize<Fixture>(json, JsonOpts)
               ?? throw new InvalidOperationException("Fixture failed to deserialize.");
    }

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    private static string LocateFixture()
    {
        string? env = Environment.GetEnvironmentVariable("RIPCORD_PACKET_FIXTURE");
        if (!string.IsNullOrEmpty(env) && File.Exists(env))
            return env;

        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8 && dir is not null; i++)
        {
            var candidate = Path.Combine(dir, "docs", "protocol", "captures", "stream_packet_vectors.json");
            if (File.Exists(candidate))
                return candidate;
            dir = Directory.GetParent(dir)?.FullName;
        }
        return Path.Combine(AppContext.BaseDirectory, "stream_packet_vectors.json"); // non-existent -> skip
    }

    // ---- fixture schema ----
    private sealed class Fixture
    {
        public int ControlTagOffset { get; set; } = 5;
        public int ControlKeyPosOffset { get; set; } = 9;
        public Dictionary<string, DirectionVectors>? Directions { get; set; }
        public CongestionVectors? Congestion { get; set; }

        public IEnumerable<(string Name, DirectionVectors Vectors)> EnumerateDirections()
        {
            foreach (var kv in Directions ?? [])
            {
                if (kv.Value.Packets is { Count: > 0 })
                    yield return (kv.Key, kv.Value);
            }
        }
    }

    private sealed class CongestionVectors
    {
        public int TagOffset { get; set; } = 7;
        public int KeyPosOffset { get; set; } = 0xB;
        public Dictionary<string, DirectionVectors>? Directions { get; set; }
    }

    private sealed class DirectionVectors
    {
        public string? AesKey { get; set; }
        public string? BaseIv { get; set; }
        public List<PacketVector>? Packets { get; set; }
    }

    private sealed class PacketVector
    {
        public string? Packet { get; set; }
        public ulong KeyPos { get; set; }
        public string? Tag { get; set; }
    }
}
