<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ripcord.Client\Ripcord.Client.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Diagnostics\Ripcord.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Core.Net\Ripcord.Core.Net.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Protocol.Halyard.Common\Ripcord.Protocol.Halyard.Common.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Protocol.Halyard.Takion\Ripcord.Protocol.Halyard.Takion.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Protocol.Halyard\Ripcord.Protocol.Halyard.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Media.Audio\Ripcord.Media.Audio.csproj" />
    <ProjectReference Include="..\..\src\Ripcord.Input.Common\Ripcord.Input.Common.csproj" />
  </ItemGroup>

</Project>
