using System.Buffers.Binary;
using System.Text;
using Ripcord.Protocol.Halyard.Common.Control;

namespace Ripcord.ProtocolLab;

/// <summary>
/// Emits <c>dgram-transport.kat</c>: transcripts of <see cref="HalyardControlAssociation"/> driven through
/// synthetic exchanges, so <c>libripcord/session/halyard_dgram_assoc.c</c> can be checked against the
/// reference byte for byte.
///
/// <para>
/// <b>Why a transcript rather than a table of encodings.</b> The account route's awkward part is <em>who
/// sends what when</em> — which tag pair an answer adopts, which sequence an acknowledgement names, what a
/// retransmission may and may not deliver — and a state machine's bytes depend on everything it has seen.
/// So each scenario records every operation, the datagrams the association emitted in response, the events
/// it raised and the phase it ended in. The C runner replays the operations with the same "random" source
/// and must reproduce all of it.
/// </para>
///
/// <para>
/// <b>Synthetic inputs only.</b> The random source is the same counter
/// <c>HalyardControlAssociationTests</c> uses (bytes counting up from 0x40), the ids count up from 1 and
/// from 101, the peer is a documentation address, and every peer datagram is built here from the codecs
/// under test. Nothing is read from a capture, and nothing emitted identifies a console or an account.
/// </para>
/// </summary>
internal static class LabDatagramVectors
{
    private static readonly byte[] OurId = [.. Enumerable.Range(1, 20).Select(i => (byte)i)];
    private static readonly byte[] PeerId = [.. Enumerable.Range(101, 20).Select(i => (byte)i)];

    /// <summary>RFC 5737 TEST-NET-1, on the account route's port.</summary>
    private static readonly byte[] PeerAddress = [192, 0, 2, 7];
    private const ushort PeerPort = 9303;

    public static int EmitFile(string outPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ripcord account-route datagram transport (UDP 9303) association transcripts");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# from HalyardControlAssociation with a counting random source (bytes from 0x40).");
        sb.AppendLine("# DO NOT EDIT - regenerate.");
        sb.AppendLine("#");
        sb.AppendLine("# assoc <name> <localId> <peerId> <peerAddress> <peerPort>   starts a fresh association");
        sb.AppendLine("# step <op> <arg> <phase> <sends> <events>");
        sb.AppendLine("#   op:     open retry openconn reopen closeconn send recv clear");
        sb.AppendLine("#   arg:    hex for send/recv, the word count for openconn, else '-'");
        sb.AppendLine("#   sends:  comma-separated hex datagrams, or '-'");
        sb.AppendLine("#   events: comma-separated: established opened:<0|1> data:<hex> closed unhandled, or '-'");
        sb.AppendLine("version 1");
        sb.AppendLine();

        int steps = 0;
        steps += Initiator(new Transcript(sb, "initiator"));
        steps += Responder(new Transcript(sb, "responder"));
        steps += Wrap(new Transcript(sb, "wrap"));

        File.WriteAllText(outPath, sb.ToString());
        return steps;
    }

    private sealed class Transcript
    {
        private readonly StringBuilder _sb;
        public HalyardControlAssociation Association { get; }
        public int Steps { get; private set; }

        public Transcript(StringBuilder sb, string name)
        {
            _sb = sb;
            byte next = 0x40;
            Association = new HalyardControlAssociation(
                OurId, PeerId, PeerAddress, PeerPort, count => [.. Enumerable.Range(0, count).Select(_ => next++)]);
            sb.AppendLine($"assoc {name} {Hex(OurId)} {Hex(PeerId)} {Hex(PeerAddress)} {PeerPort}");
        }

        public HalyardControlAction Step(string op, string arg, HalyardControlAction action)
        {
            string sends = action.Send.Count == 0 ? "-" : string.Join(",", action.Send.Select(Hex));
            string events = action.Events.Count == 0 ? "-" : string.Join(",", action.Events.Select(Event));
            _sb.AppendLine($"step {op} {arg} {Phase(Association.Phase)} {sends} {events}");
            Steps++;
            return action;
        }

        public HalyardControlAction Recv(byte[] datagram) => Step("recv", Hex(datagram), Association.OnDatagram(datagram));

        public HalyardControlAction Send(byte[] payload) => Step("send", Hex(payload), Association.Send(payload));

        public void Clear()
        {
            Association.ClearInbound();
            Step("clear", "-", HalyardControlAction.None);
        }

        public void End() => _sb.AppendLine();
    }

    private static int Initiator(Transcript t)
    {
        HalyardControlAssociation a = t.Association;

        byte[] init = t.Step("open", "-", a.Open()).Send[0];
        t.Step("retry", "-", a.Retry());
        Assert(HalyardControlPrelude.TryParse(init, out HalyardControlPrelude ours));

        t.Recv(PeerInit(ours.SwappedTagPair, 0xAABBCCDD));
        t.Recv(PeerEcho(ours.TagPair, ours.Token));

        byte[] hello = t.Step("openconn", "3", a.OpenConnection(HalyardControlAddressing.PortPair)).Send[0];
        t.Step("reopen", "-", a.ReopenConnection());
        ushort helloSeq = BinaryPrimitives.ReadUInt16BigEndian(hello.AsSpan(8));

        t.Recv(HalyardControlChunkCodec.Encode(
            HalyardControlChunkType.Cookie, 0x00, [.. Enumerable.Range(0, 42).Select(i => (byte)(0xE0 + i))]));
        t.Recv(Accept(0xA65E, (ushort)(helloSeq + 1)));

        t.Send(Encoding.ASCII.GetBytes("POST /sie/ps5/rp/sess/rgst HTTP/1.1\r\n\r\n"));
        t.Recv(Data(0xA65F, "HTTP/1.1 200 OK\r\n"));
        t.Recv(Data(0xA660, "Content-Length: 0\r\n\r\n"));
        t.Recv(Retransmit(0xA660, "Content-Length: 0\r\n\r\n"));
        t.Clear();

        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Ack, 0x30, [0x12, 0x34, 0x56, 0x78]));
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.AckExtended, 0x30, [1, 2, 3, 4, 5, 6]));

        // A probe while connected: echoed, and the association is not reopened.
        t.Recv(PeerInit(ours.SwappedTagPair, 0xAABBCD00));

        // An ack and a data chunk concatenated in one datagram.
        t.Recv([.. HalyardControlChunkCodec.Encode(HalyardControlChunkType.Ack, 0x30, [0, 0, 0, 0]),
                .. Data(0xA661, "\u0000\u0000\u0000\u0002\u0001\u0000\u0000\u0000")]);
        t.Send([0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x00, 0x00]);
        t.Clear();

        t.Step("closeconn", "-", a.CloseConnection());
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Close, 0x00, new byte[8]));
        t.Send([1]);

        // A second connection over the same prelude, addressed with no port words this time.
        hello = t.Step("openconn", "1", a.OpenConnection(HalyardControlAddressing.PeerAddressOnly)).Send[0];
        t.Step("reopen", "-", a.ReopenConnection());
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Cookie, 0x00, new byte[42]));

        // The diagnostic cases.
        t.Recv([1, 2, 3, 4]);
        t.Recv(HalyardControlChunkCodec.Encode((HalyardControlChunkType)0x55, 0x30, [9, 9]));
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Cookie, 0x00, [1, 2, 3, 4]));
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Accept, 0x30, [1, 2]));
        t.Recv([.. HalyardControlChunkCodec.Encode(HalyardControlChunkType.Accept, 0x30, Accept12(0x0100, 0x0200)),
                0x00, 0x01, 0x02]);

        t.End();
        return t.Steps;
    }

    private static int Responder(Transcript t)
    {
        HalyardControlAssociation a = t.Association;

        t.Step("retry", "-", a.Retry());
        t.Step("openconn", "3", a.OpenConnection());
        t.Send([1]);
        t.Recv(PeerInit(0x00017777, 0x11223344));
        t.Recv(PeerInit(0x00017777, 0x11229999));
        t.Step("retry", "-", a.Retry());
        t.Recv(PeerEcho(0x00017777, 0));
        t.Step("open", "-", a.Open());

        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Cookie, 0x00, new byte[42]));

        byte[] peerHello = new byte[14];
        BinaryPrimitives.WriteUInt16BigEndian(peerHello, 0x1234);
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.Hello, 0x30, peerHello, wordCount: 1));
        t.Recv(HalyardControlChunkCodec.Encode(HalyardControlChunkType.HelloEcho, 0x30, peerHello, wordCount: 1));

        t.Recv(Data(0x1235, "GET /sie/ps5/rp/sess/init HTTP/1.1\r\n\r\n", wordCount: 1));
        t.Recv(Data(0x1235, "GET /sie/ps5/rp/sess/init HTTP/1.1\r\n\r\n", wordCount: 1));
        t.Recv(Data(0x1234, "stale", wordCount: 1));
        t.Send(Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"));

        // No hello of ours outstanding, so there is no connection tag to close with.
        t.Step("closeconn", "-", a.CloseConnection());

        // The peer opens a fresh association with a different tag pair: adopted, from any phase.
        t.Recv(PeerInit(0x00015555, 0x01020304));
        t.Recv(PeerEcho(0x00015555, 0));

        t.End();
        return t.Steps;
    }

    private static int Wrap(Transcript t)
    {
        HalyardControlAssociation a = t.Association;

        byte[] init = t.Step("open", "-", a.Open()).Send[0];
        Assert(HalyardControlPrelude.TryParse(init, out HalyardControlPrelude ours));
        t.Recv(PeerEcho(ours.TagPair, ours.Token));
        t.Recv(PeerInit(ours.SwappedTagPair, 0x00000001));
        t.Step("openconn", "2", a.OpenConnection(HalyardControlAddressing.SinglePort));
        t.Recv(Accept(0xFFFE, 0x0001));
        t.Recv(Data(0xFFFF, "a"));
        t.Recv(Data(0x0000, "b"));
        t.Recv(Data(0xFFFF, "a"));
        t.Recv(Data(0x0001, "c"));
        t.Send([]);
        t.Recv(Data(0x0001, ""));

        t.End();
        return t.Steps;
    }

    // ---- peer datagrams, built from the codecs under test ----

    private static byte[] PeerInit(uint tagPair, uint token)
        => new HalyardControlPrelude(
            HalyardControlPrelude.Init, PeerId, OurId, tagPair, RequestWord: 0x19, Token: token,
            Tail: ReadOnlyMemory<byte>.Empty).Serialize();

    private static byte[] PeerEcho(uint tagPair, uint token)
        => new HalyardControlPrelude(
            HalyardControlPrelude.CookieEcho, PeerId, OurId, tagPair, RequestWord: 0, Token: token,
            Tail: ReadOnlyMemory<byte>.Empty).Serialize();

    private static byte[] Accept12(ushort sequence, ushort acknowledgement)
    {
        byte[] body = new byte[12];
        BinaryPrimitives.WriteUInt16BigEndian(body, sequence);
        BinaryPrimitives.WriteUInt16BigEndian(body.AsSpan(2), acknowledgement);
        return body;
    }

    private static byte[] Accept(ushort sequence, ushort acknowledgement)
        => HalyardControlChunkCodec.Encode(HalyardControlChunkType.Accept, 0x30, Accept12(sequence, acknowledgement));

    private static byte[] Data(ushort sequence, string text, byte wordCount = 3)
    {
        byte[] body = new byte[2 + text.Length];
        BinaryPrimitives.WriteUInt16BigEndian(body, sequence);
        Encoding.Latin1.GetBytes(text).CopyTo(body, 2);
        return HalyardControlChunkCodec.Encode(HalyardControlChunkType.Data, 0x30, body, wordCount);
    }

    private static byte[] Retransmit(ushort sequence, string text)
    {
        byte[] body = new byte[8 + text.Length];
        BinaryPrimitives.WriteUInt16BigEndian(body, sequence);
        body[2] = 0x8A;
        body[3] = 0x04;
        Encoding.ASCII.GetBytes(text).CopyTo(body, 8);
        return HalyardControlChunkCodec.Encode(HalyardControlChunkType.DataRetransmit, 0x30, body);
    }

    private static string Event(HalyardControlEvent e) => e switch
    {
        HalyardControlEvent.PreludeEstablished => "established",
        HalyardControlEvent.ConnectionOpened o => $"opened:{(o.OpenedByPeer ? 1 : 0)}",
        HalyardControlEvent.DataReceived d => $"data:{Hex(d.Payload)}",
        HalyardControlEvent.PeerClosed => "closed",
        HalyardControlEvent.Unhandled => "unhandled",
        _ => throw new InvalidOperationException($"unknown event {e}"),
    };

    private static string Phase(HalyardControlPhase phase) => phase.ToString().ToLowerInvariant();

    private static string Hex(byte[] value) => value.Length == 0 ? "-" : Convert.ToHexString(value).ToLowerInvariant();

    private static void Assert(bool condition)
    {
        if (!condition)
        {
            throw new InvalidOperationException("the association emitted something the generator could not parse");
        }
    }
}
