using System.Net;
using System.Security.Cryptography;
using System.Text;
using Ripcord.Core.Discovery;
using Ripcord.Core.Sessions;
using Ripcord.Protocol.Halyard.Common.Control;
using Ripcord.Protocol.Halyard.Common.Crypto;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Ripcord.Protocol.Halyard.Session;
using Ripcord.Protocol.Halyard.Transport;

namespace Ripcord.ProtocolLab;

/// <summary>
/// Emits <c>rendezvous-control.kat</c>: the exact <c>/sess/init</c> and <c>/sess/ctrl</c> requests
/// <see cref="HalyardStreamingSession"/> sends on the rendezvous route, so the C core's datagram control
/// session (<c>halyard_control_session_open_with</c> over <c>halyard_dgram_control_pipe</c>) can be checked
/// against them byte for byte.
///
/// <para>
/// <b>Why the session itself, and not a re-assembly.</b> What differs between the routes is spelled inside
/// the session's private request builders — the padded <c>Host</c>, <c>Rp-Version</c> on init,
/// <c>RP-ConPath</c> — and a copy of them here would only prove this file agrees with itself. So the real
/// session is run with <see cref="HalyardConnectionPath.Rendezvous"/> against a control channel that answers
/// <c>/sess/init</c> with a derived nonce, records every request, and closes; the stream transport factory
/// then throws, which ends the connect right where the A/V leg would begin. Nothing is sent anywhere.
/// </para>
///
/// <para>
/// <b>Synthetic inputs only</b>, derived from SHA-256 of a domain string and a counter like the other files:
/// the registration key, companion, device id and nonce identify no console. The one input that is not
/// derived is the OS version, which the session reads from <see cref="Environment.OSVersion"/>; it is
/// written out so the C side encrypts the same <c>RP-OSType</c>.
/// </para>
/// </summary>
internal static class LabRendezvousVectors
{
    private const string Domain = "ripcord-vectors/rendezvous-control/v1";

    /// <summary>RFC 5737 TEST-NET-1: the paired host, which on this route names the Host header.</summary>
    private const string ConsoleHost = "192.0.2.44";

    private const int Bitrate = 15000;

    public static int EmitFile(string outPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ripcord rendezvous-route control-plane requests (/sess/init, /sess/ctrl over UDP 9303)");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# from HalyardStreamingSession.ConnectAsync with ConnectionPath = Rendezvous. DO NOT EDIT - regenerate.");
        sb.AppendLine("#");
        sb.AppendLine("# case <ps5|ps4> <host> <registkeyHex> <companionHex> <deviceIdHex> <nonceHex> <osMajor> <osMinor> <bitrate>");
        sb.AppendLine("# init <hex of the whole request>");
        sb.AppendLine("# ctrl <hex of the whole request>");
        sb.AppendLine("version 1");
        sb.AppendLine();

        var secrets = HalyardInteropConstants.Control();
        if (secrets is null)
        {
            File.WriteAllText(outPath, sb.ToString());
            return 0;
        }

        int cases = 0;
        var stream = new Derived(Domain);
        foreach (HalyardConsolePlatform platform in new[] { HalyardConsolePlatform.Ps5, HalyardConsolePlatform.Ps4 })
        {
            // An 8-character hex registration key, as every real one is (the WakeCredential note).
            byte[] registKey = Encoding.ASCII.GetBytes(Convert.ToHexString(stream.Next(4)).ToLowerInvariant());
            byte[] companion = stream.Next(16);
            byte[] deviceId = stream.Next(16);
            byte[] nonce = stream.Next(16);

            var control = new CapturingControlChannel(nonce);
            var store = new OneRecordStore(new HalyardPairingRecord(registKey, companion, KeyType: 2, platform).Serialize());
            var parameters = new HalyardConnectionParameters(
                ConsoleId: "vectors",
                ControlEndpoint: new IPEndPoint(IPAddress.Parse(ConsoleHost), HalyardDatagramRegistrationTransport.Port),
                StreamEndpoint: new IPEndPoint(IPAddress.Parse(ConsoleHost), HalyardSessionFactory.DefaultStreamPort),
                DeviceId: deviceId,
                ConnectionPath: HalyardConnectionPath.Rendezvous);

            var session = new HalyardStreamingSession(
                parameters, control, new HalyardV1SessionCrypto(secrets), store,
                loginPinProvider: null, controlPlaneDeadline: TimeSpan.FromSeconds(10),
                streamTransportFactory: _ => throw new InvalidOperationException("the vector stops at the A/V leg"));

            var config = new SessionConfig(1280, 720, 60, Bitrate, VideoCodec.H264, LatencyMode.Balanced);
            session.ConnectAsync(config, CancellationToken.None).GetAwaiter().GetResult();
            session.DisposeAsync().AsTask().GetAwaiter().GetResult();

            if (control.Requests.Count < 2)
            {
                throw new InvalidOperationException(
                    $"the rendezvous session sent {control.Requests.Count} request(s); expected /sess/init and /sess/ctrl");
            }

            Version os = Environment.OSVersion.Version;
            sb.AppendLine(
                $"case {(platform == HalyardConsolePlatform.Ps5 ? "ps5" : "ps4")} {ConsoleHost} {Hex(registKey)} "
                + $"{Hex(companion)} {Hex(deviceId)} {Hex(nonce)} {os.Major} {os.Minor} {Bitrate}");
            sb.AppendLine($"init {Hex(control.Requests[0])}");
            sb.AppendLine($"ctrl {Hex(control.Requests[1])}");
            sb.AppendLine();
            cases++;
        }

        File.WriteAllText(outPath, sb.ToString());
        return cases;
    }

    private static string Hex(byte[] bytes) => Convert.ToHexString(bytes).ToLowerInvariant();

    /// <summary>Answers /sess/init with the nonce and anything else with a bare 200; reads nothing but a close.</summary>
    private sealed class CapturingControlChannel(byte[] nonce) : IHalyardControlChannel
    {
        public List<byte[]> Requests { get; } = [];

        public Task ConnectAsync(IPEndPoint endpoint, CancellationToken cancellationToken) => Task.CompletedTask;

        public Task<SessResponse> SendRequestAsync(SessRequest request, CancellationToken cancellationToken)
        {
            Requests.Add(request.Serialize());
            string text = request.Path.EndsWith("/init", StringComparison.Ordinal)
                ? $"HTTP/1.1 200 OK\r\nRP-Nonce: {Convert.ToBase64String(nonce)}\r\nContent-Length: 0\r\n\r\n"
                : "HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n";
            if (!SessResponse.TryParse(Encoding.ASCII.GetBytes(text), out SessResponse? response, out _) || response is null)
            {
                throw new InvalidOperationException("the canned response did not parse");
            }

            return Task.FromResult(response);
        }

        public Task SendCtrlMessageAsync(HalyardCtrlMessage message, CancellationToken cancellationToken) => Task.CompletedTask;

        public Task<HalyardCtrlMessage?> ReadCtrlMessageAsync(CancellationToken cancellationToken)
            => Task.FromResult<HalyardCtrlMessage?>(null);

        public ValueTask DisposeAsync() => ValueTask.CompletedTask;
    }

    private sealed class OneRecordStore(byte[] blob) : IConsoleCredentialStore
    {
        public Task SaveAsync(string consoleId, byte[] registrationKey, CancellationToken cancellationToken) => Task.CompletedTask;

        public Task<byte[]?> LoadAsync(string consoleId, CancellationToken cancellationToken) => Task.FromResult<byte[]?>(blob);

        public Task RemoveAsync(string consoleId, CancellationToken cancellationToken) => Task.CompletedTask;
    }

    /// <summary>SHA-256(domain || counter), as LabVectors derives its inputs.</summary>
    private sealed class Derived(string domain)
    {
        private readonly byte[] _domain = Encoding.ASCII.GetBytes(domain);
        private ulong _counter;

        public byte[] Next(int count)
        {
            var output = new byte[count];
            byte[] message = new byte[_domain.Length + sizeof(ulong)];
            _domain.CopyTo(message, 0);
            int written = 0;
            while (written < count)
            {
                System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(message.AsSpan(_domain.Length), _counter++);
                byte[] block = SHA256.HashData(message);
                int take = Math.Min(32, count - written);
                block.AsSpan(0, take).CopyTo(output.AsSpan(written));
                written += take;
            }

            return output;
        }
    }
}
