using System.Security.Cryptography;
using System.Text;
using Google.Protobuf; // for the ToByteArray() extension on the generated ControlMessage
using Ripcord.Core.Net.Crypto;
using Ripcord.Core.Sessions;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Ripcord.Protocol.Halyard.Session;

namespace Ripcord.ProtocolLab;

/// <summary>
/// Emits known-answer vectors for the v1 control-plane crypto, so a second implementation of this protocol
/// can be checked against this one without a console, a capture, or a .NET runtime.
///
/// <para>
/// This exists for <c>ports/ripcord-3ds</c>, the C client for modded 3DS hardware. That port re-derives the
/// same primitives from the same spec in a different language, which is only a meaningful check on the spec
/// if both sides are provably computing the same numbers. These vectors are that check: this command writes
/// them, the port's host-side <c>vector_runner</c> reads them, and a disagreement is a spec defect rather
/// than a porting detail.
/// </para>
///
/// <para>
/// <b>The constants come from the bundle, deliberately</b> — <see cref="HalyardInteropConstants"/> directly,
/// not <see cref="HalyardControlSecretsLoader"/>. The port generates its constants from the same committed
/// <c>halyard-v1-constants.json</c>, so both sides must key off that one file or the comparison proves
/// nothing. A developer with a local dirty-room fixture is intentionally NOT allowed to influence this
/// output; if the fixture ever disagreed with the bundle, that is a finding about the bundle, and it should
/// not be discovered as a mystery failure in a C test on a handheld.
/// </para>
///
/// <para>
/// <b>Inputs are derived, not random.</b> Every nonce, companion, key and plaintext comes from
/// SHA-256("ripcord-3ds-vectors/v1" || counter), so the file is byte-identical across runs and machines. That
/// keeps it diffable: a change in this file means a change in the crypto, which is exactly the signal
/// wanted. Do not switch this to <see cref="RandomNumberGenerator"/>.
/// </para>
///
/// <para>
/// The output carries no live material. Its inputs are synthetic and its constants are the ones already
/// committed under the <c>NOTICE</c> interoperability-constants exception, so the file is strictly less
/// sensitive than the bundle it derives from. It is still gitignored as a build artifact — regenerating it
/// is one command, and a committed copy would only invite the question of whether it is a second bundle.
/// </para>
/// </summary>
internal static class LabVectors
{
    private const string Domain = "ripcord-3ds-vectors/v1";

    /// <summary>vectors [outPath] — write the control-crypto known-answer vectors.</summary>
    public static int Emit(string[] args)
    {
        string outPath = args.Length > 1
            ? args[1]
            : Path.Combine("ports", "ripcord-3ds", "tests", "vectors", "control-crypto.kat");

        var secrets = HalyardInteropConstants.Control();
        if (secrets is null)
        {
            Console.Error.WriteLine(
                "no bundled interop constants in this build (-p:BundleInteropConstants=false?); cannot emit vectors.");
            return 1;
        }

        var kdf = new HalyardControlKdf(secrets);
        var stream = new DerivedBytes(Domain);
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds v1 control-crypto known-answer vectors");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# inputs are SHA-256(\"" + Domain + "\" || counter); constants are the committed bundle.");
        sb.AppendLine("# DO NOT EDIT - regenerate. A diff here is a change in the crypto.");
        sb.AppendLine("version 1");
        sb.AppendLine($"ps4tables {(secrets.HasPs4Tables ? 1 : 0)}");
        sb.AppendLine();

        int kdfCount = EmitKdf(sb, kdf, secrets, stream);
        int ctxCount = EmitContextKeys(sb, secrets.ContextKeys);
        int ivCount = EmitFieldIv(sb, stream);
        int modeCount = EmitCipherModes(sb, stream);
        int fieldCount = EmitEndToEnd(sb, kdf, secrets.ContextKeys, stream);

        string? dir = Path.GetDirectoryName(Path.GetFullPath(outPath));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);
        File.WriteAllText(outPath, sb.ToString());

        Console.WriteLine($"wrote {outPath}");
        Console.WriteLine(
            $"  kdf={kdfCount} ctxkey={ctxCount} iv={ivCount} mode={modeCount} field={fieldCount}  " +
            $"(ps4 tables {(secrets.HasPs4Tables ? "present" : "absent")})");

        // A separate file, not appended to the control-crypto one above: this is a different cipher
        // entirely (the stream/A-V plane's AES-GCM-derived GMAC, not the control plane's AES-CFB/OFB),
        // checked by a separate host-side runner in the C port.
        string streamOutPath = string.IsNullOrEmpty(dir) ? "stream-crypto.kat" : Path.Combine(dir, "stream-crypto.kat");
        var streamCounts = EmitStreamCryptoFile(streamOutPath);
        Console.WriteLine($"wrote {streamOutPath}");
        Console.WriteLine($"  gmac={streamCounts.Gmac} streamkdf={streamCounts.StreamKdf} " +
            $"packetnonce={streamCounts.PacketNonce} packettag={streamCounts.PacketTag}");

        // A third file, for the same reason the second one is separate: the C port checks these with a
        // runner that links an EC backend (mbedtls), which the other two deliberately do not need.
        string sessionOutPath = string.IsNullOrEmpty(dir) ? "session-crypto.kat" : Path.Combine(dir, "session-crypto.kat");
        var sessionCounts = EmitSessionCryptoFile(sessionOutPath);
        Console.WriteLine($"wrote {sessionOutPath}");
        Console.WriteLine($"  ecdhpub={sessionCounts.EcdhPub} ecdhshared={sessionCounts.EcdhShared} " +
            $"ecdhsig={sessionCounts.EcdhSig} streamkeys={sessionCounts.StreamKeys}");

        string protoOutPath = string.IsNullOrEmpty(dir) ? "control-proto.kat" : Path.Combine(dir, "control-proto.kat");
        var protoCounts = EmitControlProtoFile(protoOutPath);
        Console.WriteLine($"wrote {protoOutPath}");
        Console.WriteLine($"  sessionreq={protoCounts.Request} sessionreply={protoCounts.Reply}");

        return 0;
    }

    // ---- the stream key agreement: ECDH proper, its signature, and the whole chain to per-direction keys ----

    private static (int EcdhPub, int EcdhShared, int EcdhSig, int StreamKeys) EmitSessionCryptoFile(string outPath)
    {
        var stream = new DerivedBytes(Domain + "/session");
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds v1 stream key-agreement known-answer vectors (ECDH -> per-direction keys)");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# inputs are SHA-256(\"" + Domain + "/session\" || counter). DO NOT EDIT - regenerate.");
        sb.AppendLine("#");
        sb.AppendLine("# Curve names are p256/p521. Private scalars are fixed, NOT generated - a known-answer");
        sb.AppendLine("# vector for a key agreement is impossible otherwise, which is why the C side exposes an");
        sb.AppendLine("# explicit rc_ecdh_keypair_from_private() rather than a test-only back door.");
        sb.AppendLine("version 1");
        sb.AppendLine();

        int pubCount = EmitEcdhPublicKeys(sb, stream);
        int sharedCount = EmitEcdhShared(sb, stream);
        int sigCount = EmitEcdhSignatures(sb, stream);
        int keysCount = EmitStreamKeysEndToEnd(sb, stream);

        File.WriteAllText(outPath, sb.ToString());
        return (pubCount, sharedCount, sigCount, keysCount);
    }

    /// <summary>
    /// A fixed keypair on <paramref name="curve"/>, derived reproducibly from the vector stream.
    ///
    /// <para>The scalar is drawn from the same SHA-256 stream as every other input and then imported
    /// private-only, letting the platform recompute Q — .NET is the only side here that can do EC point
    /// arithmetic at all, so it has to be the one that answers "what public key does this scalar give?".
    /// A candidate outside [1, N-1] is rejected by the import and the next one is drawn, which keeps the
    /// output deterministic while staying correct for both curves (P-521's top byte is masked first, since
    /// an unmasked 66-byte draw exceeds the group order almost always rather than almost never).</para>
    /// </summary>
    private static (byte[] D, byte[] PublicKey, ECDiffieHellman Handle) DeriveKeyPair(
        HalyardStreamCurve curve, DerivedBytes stream)
    {
        int coordinateSize = curve == HalyardStreamCurve.NistP521 ? 66 : 32;
        ECCurve ecCurve = curve == HalyardStreamCurve.NistP521
            ? ECCurve.NamedCurves.nistP521
            : ECCurve.NamedCurves.nistP256;

        for (int attempt = 0; attempt < 64; attempt++)
        {
            byte[] d = stream.Next(coordinateSize);
            if (curve == HalyardStreamCurve.NistP521)
                d[0] &= 0x01; // P-521's order is just under 2^521; clear the 7 bits above it.

            try
            {
                var ecdh = ECDiffieHellman.Create(new ECParameters { Curve = ecCurve, D = d });
                ECPoint q = ecdh.PublicKey.ExportParameters().Q;

                var pub = new byte[1 + 2 * coordinateSize];
                pub[0] = 0x04;
                CopyRightAligned(q.X!, pub.AsSpan(1, coordinateSize));
                CopyRightAligned(q.Y!, pub.AsSpan(1 + coordinateSize, coordinateSize));
                return (d, pub, ecdh);
            }
            catch (CryptographicException)
            {
                // Scalar out of range for this curve. Draw the next one; the stream is still deterministic.
            }
        }

        throw new InvalidOperationException($"could not derive a valid {curve} scalar in 64 attempts");
    }

    private static void CopyRightAligned(ReadOnlySpan<byte> element, Span<byte> destination)
    {
        destination.Clear();
        element.CopyTo(destination[(destination.Length - element.Length)..]);
    }

    private static string CurveName(HalyardStreamCurve curve)
        => curve == HalyardStreamCurve.NistP521 ? "p521" : "p256";

    private static readonly HalyardStreamCurve[] Curves =
        [HalyardStreamCurve.NistP256, HalyardStreamCurve.NistP521];

    // ecdhpub <curve> <privHex> <pubHex>
    // Scalar -> public point. This is the one vector that checks the C side's point arithmetic against
    // .NET's directly, with no HMAC downstream to mask a wrong answer.
    private static int EmitEcdhPublicKeys(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# ecdhpub <curve> <privHex> <pubHex>");
        int count = 0;

        foreach (HalyardStreamCurve curve in Curves)
        {
            for (int i = 0; i < 3; i++)
            {
                var (d, pub, handle) = DeriveKeyPair(curve, stream);
                handle.Dispose();
                sb.AppendLine($"ecdhpub {CurveName(curve)} {Hex(d)} {Hex(pub)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // ecdhshared <curve> <localPrivHex> <peerPubHex> <sharedHex>
    // The shared X at full width, leading zeros preserved. That last detail is the whole reason this
    // vector set includes several draws per curve rather than one: an implementation that writes the
    // coordinate at its natural (leading-zero-trimmed) length instead of the curve's agrees with this one
    // on most inputs and then silently derives different keys on the rest.
    //
    // P-521 makes that failure mode near-certain to be caught rather than merely likely, and not by luck:
    // X is at most 521 bits but the field is 66 bytes = 528 bits, so the top seven bits are always zero
    // and byte 0 is always 0x00 or 0x01 - a leading zero byte lands roughly half the time here, against
    // roughly 1-in-256 on P-256.
    private static int EmitEcdhShared(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# ecdhshared <curve> <localPrivHex> <peerPubHex> <sharedHex>");
        int count = 0;

        foreach (HalyardStreamCurve curve in Curves)
        {
            for (int i = 0; i < 4; i++)
            {
                var (localD, _, localHandle) = DeriveKeyPair(curve, stream);
                var (_, peerPub, peerHandle) = DeriveKeyPair(curve, stream);
                using (localHandle)
                using (peerHandle)
                {
                    byte[] shared = HalyardStreamKeySchedule.DeriveSharedSecret(localHandle, peerPub);
                    sb.AppendLine($"ecdhshared {CurveName(curve)} {Hex(localD)} {Hex(peerPub)} {Hex(shared)}");
                    count++;
                }
            }
        }

        sb.AppendLine();
        return count;
    }

    // ecdhsig <handshakeKey16> <pubHex> <sigHex>
    // HMAC-SHA256(handshakeKey, publicKey) - the value that authenticates each side's ECDH public key in
    // the SESSION_REQUEST/REPLY. Needs no EC backend to check, but it belongs with the exchange it
    // protects rather than filed under generic HMAC.
    private static int EmitEcdhSignatures(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# ecdhsig <handshakeKey16> <pubHex> <sigHex>");
        int count = 0;

        foreach (int pubLength in new[] { 65, 133 })
        {
            for (int i = 0; i < 2; i++)
            {
                byte[] handshakeKey = stream.Next(16);
                byte[] pub = stream.Next(pubLength);
                pub[0] = 0x04; // shape-accurate; the signature covers the bytes, not the point's validity
                byte[] signature = HalyardStreamKeySchedule.ComputeEcdhSignature(handshakeKey, pub);
                sb.AppendLine($"ecdhsig {Hex(handshakeKey)} {Hex(pub)} {Hex(signature)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // streamkeys <curve> <localPrivHex> <peerPubHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>
    // The whole chain a real session runs: ECDH -> shared X -> SP800-108 KDF -> one direction's key+IV.
    // The intermediate secret is deliberately NOT in this line - the point is that both implementations
    // arrive at the same final keys, and a vector that hands over the midpoint would let a port that gets
    // ECDH wrong still pass the half it can do.
    private static int EmitStreamKeysEndToEnd(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# streamkeys <curve> <localPrivHex> <peerPubHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>");
        int count = 0;

        foreach (HalyardStreamCurve curve in Curves)
        {
            for (int i = 0; i < 2; i++)
            {
                var (localD, _, localHandle) = DeriveKeyPair(curve, stream);
                var (_, peerPub, peerHandle) = DeriveKeyPair(curve, stream);
                using (localHandle)
                using (peerHandle)
                {
                    byte[] shared = HalyardStreamKeySchedule.DeriveSharedSecret(localHandle, peerPub);
                    byte[] handshakeKey = stream.Next(16);

                    foreach (byte direction in new[] {
                        HalyardStreamKeySchedule.DirectionClientToServer,
                        HalyardStreamKeySchedule.DirectionServerToClient })
                    {
                        var keys = HalyardStreamKeySchedule.DeriveDirection(shared, handshakeKey, direction);
                        sb.AppendLine($"streamkeys {CurveName(curve)} {Hex(localD)} {Hex(peerPub)} " +
                            $"{Hex(handshakeKey)} {direction} {Hex(keys.AesKey)} {Hex(keys.BaseIv)}");
                        count++;
                    }
                }
            }
        }

        sb.AppendLine();
        return count;
    }

    // ---- the control-plane protobuf envelope: SESSION_REQUEST out, SESSION_REPLY in ----

    private static (int Request, int Reply) EmitControlProtoFile(string outPath)
    {
        var stream = new DerivedBytes(Domain + "/proto");
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds control-plane protobuf known-answer vectors (SESSION_REQUEST/SESSION_REPLY)");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# encoded by Google.Protobuf from docs/protocol/stream_control.proto, which is the");
        sb.AppendLine("# authority for every field number here. DO NOT EDIT - regenerate.");
        sb.AppendLine("#");
        sb.AppendLine("# All string fields are hex-encoded, not quoted: a .kat line is whitespace-split, and a");
        sb.AppendLine("# launch spec is base64 that could legally contain anything a quoting scheme would then");
        sb.AppendLine("# have to escape.");
        sb.AppendLine("#");
        sb.AppendLine("# '-' stands in for any field whose hex would be the empty string, because an empty field");
        sb.AppendLine("# is invisible to a whitespace-splitting reader - it shifts every later field left by one");
        sb.AppendLine("# rather than reporting itself, which is the same trap the gmac vectors' zero-length AAD");
        sb.AppendLine("# already documents. On a REQUIRED field (sessionKey, launchSpecJson, encryptedKey) it");
        sb.AppendLine("# therefore means present-but-zero-length; on an OPTIONAL one (ecdhPublicKey,");
        sb.AppendLine("# ecdhSignature, serverVersionString) it means absent. Those are distinguishable by");
        sb.AppendLine("# position alone, and no vector here needs a zero-length optional.");
        sb.AppendLine("version 1");
        sb.AppendLine();

        int requestCount = EmitSessionRequests(sb, stream);
        int replyCount = EmitSessionReplies(sb, stream);
        EmitLaunchSpecs(sb, stream);

        File.WriteAllText(outPath, sb.ToString());
        return (requestCount, replyCount);
    }

    // launchspec <w> <h> <fps> <bitrateKbps> <mtu> <rttMs> <hevc 0|1> <hdr 0|1> <handshakeKey16> <jsonHex>
    //
    // The launch spec is a fixed-order JSON document, and the console's only response to getting it wrong
    // is to accept /sess/ctrl and then never answer SESSION_REQUEST — no error, no log line, nothing to
    // bisect. That silence is why this is worth a byte-for-byte vector rather than an eyeball comparison:
    // the C port builds the same string by hand from the same field list, and a stray comma or a
    // locale-formatted float shows up here instead of on a handheld.
    //
    // The JSON is hex-encoded for the same reason every other string field in this file is — see the
    // header — and here it also sidesteps the document's own quotes and braces entirely.
    private static void EmitLaunchSpecs(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# launchspec <w> <h> <fps> <bitrateKbps> <mtu> <rttMs> <hevc 0|1> <hdr 0|1> " +
            "<handshakeKey16> <jsonHex>");

        // The ladder is the part with real branching, so the cases sweep it: a request below every
        // standard rung (one entry), one in the middle, the top rung, and a non-standard size that is not
        // on the ladder at all. 640x360 is what this hardware will actually ask for.
        (int W, int H, int Fps, int Bitrate, int Mtu, int Rtt, bool Hevc, bool Hdr)[] cases =
        [
            (640, 360, 30, 2000, 1454, 0, false, false),
            (640, 360, 60, 3000, 1400, 12, false, false),
            (1280, 720, 60, 10000, 1454, 0, false, false),
            (1920, 1080, 60, 30000, 1454, 250, true, false),
            (854, 480, 30, 4000, 1200, 7, false, true),
        ];

        foreach (var (w, h, fps, bitrate, mtu, rtt, hevc, hdr) in cases)
        {
            byte[] handshakeKey = stream.Next(16);
            string json = HalyardStreamingSession.BuildLaunchSpecJson(
                handshakeKey, w, h, fps, bitrate,
                hevc ? VideoCodec.Hevc : VideoCodec.H264,
                hdr ? DynamicRange.Hdr : DynamicRange.Sdr,
                declaredMtu: mtu,
                measuredRttMs: rtt);

            sb.AppendLine($"launchspec {w} {h} {fps} {bitrate} {mtu} {rtt} {(hevc ? 1 : 0)} " +
                $"{(hdr ? 1 : 0)} {Hex(handshakeKey)} {Hex(Encoding.UTF8.GetBytes(json))}");
        }

        sb.AppendLine();
    }

    /// <summary>Hex, or "-" when there would be nothing to print. See the file header for both meanings.</summary>
    private static string HexOrDash(byte[]? value)
        => value is null || value.Length == 0 ? "-" : Hex(value);

    private static string HexOrDash(string value)
        => HexOrDash(Encoding.ASCII.GetBytes(value));

    // sessionreq <clientVersion> <sessionKeyHex> <launchSpecHex> <encryptedKeyHex> <pubHex|-> <sigHex|-> <encodedHex>
    private static int EmitSessionRequests(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# sessionreq <clientVersion> <sessionKeyHex> <launchSpecHex> <encryptedKeyHex> <pubHex|-> <sigHex|-> <encodedHex>");
        int count = 0;

        // The shipped shape first (client version 17, the observed "InvalidSessionId" session key, the
        // four zero bytes the vendor sends for the unused encryptedKey, and a P-521 public key), then
        // variations that move each independent axis: the other curve, the optional fields absent, and a
        // launch spec long enough to push the payload's length prefix to two varint bytes.
        (uint Version, string SessionKey, int SpecLength, int PubLength, bool Optionals)[] cases =
        [
            (17, "InvalidSessionId", 220, 133, true),
            (17, "InvalidSessionId", 900, 133, true),
            (9, "InvalidSessionId", 180, 65, true),
            (17, "", 4, 133, true),
            (17, "InvalidSessionId", 200, 0, false),
        ];

        foreach (var (version, sessionKey, specLength, pubLength, optionals) in cases)
        {
            // Base64 of derived bytes: the real launchSpecJson is OFB-encrypted then base64'd, so what
            // this field actually carries on the wire is opaque ASCII, and that is what matters here.
            string launchSpec = Convert.ToBase64String(stream.Next(specLength));
            byte[] encryptedKey = new byte[4]; // unused by the protocol; the vendor sends four zeros
            byte[]? pub = null;
            byte[]? signature = null;
            if (optionals)
            {
                pub = stream.Next(pubLength);
                pub[0] = 0x04;
                signature = HalyardStreamKeySchedule.ComputeEcdhSignature(stream.Next(16), pub);
            }

            var payload = new Avstream.SessionRequestPayload
            {
                ClientVersion = version,
                SessionKey = sessionKey,
                LaunchSpecJson = launchSpec,
                EncryptedKey = Google.Protobuf.ByteString.CopyFrom(encryptedKey),
            };
            if (pub is not null)
                payload.EcdhPublicKey = Google.Protobuf.ByteString.CopyFrom(pub);
            if (signature is not null)
                payload.EcdhSignature = Google.Protobuf.ByteString.CopyFrom(signature);

            var message = new Avstream.ControlMessage
            {
                Type = Avstream.ControlMessage.Types.MessageType.SessionRequest,
                SessionRequestPayload = payload,
            };

            sb.AppendLine($"sessionreq {version} {HexOrDash(sessionKey)} " +
                $"{HexOrDash(launchSpec)} {HexOrDash(encryptedKey)} " +
                $"{HexOrDash(pub)} {HexOrDash(signature)} {Hex(message.ToByteArray())}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // sessionreply <encodedHex> <serverVersion> <token> <encKeyAccepted> <versionAccepted> <sessionKeyHex> <serverVersionStringHex|-> <pubHex|-> <sigHex|->
    private static int EmitSessionReplies(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# sessionreply <encodedHex> <serverVersion> <token> <encKeyAccepted> <versionAccepted> " +
            "<sessionKeyHex> <serverVersionStringHex|-> <pubHex|-> <sigHex|->");
        int count = 0;

        // Field-number coverage matters more than value variety here: the parser has to skip an optional
        // it does not model (extendedInfo, field 6, a nested message) without losing its place, so one
        // case carries one.
        (uint Version, uint Token, bool KeyOk, bool VersionOk, string SessionKey, string? VersionString,
            int PubLength, bool ExtendedInfo)[] cases =
        [
            (17, 0, true, true, "InvalidSessionId", "1.0", 133, false),
            (17, 0xDEADBEEF, true, true, "InvalidSessionId", null, 133, false),
            (9, 1, false, true, "s", "9.60", 65, false),
            (17, 42, true, false, "InvalidSessionId", "1.0", 133, true),
            (17, 7, true, true, "InvalidSessionId", null, 0, false),
        ];

        foreach (var (version, token, keyOk, versionOk, sessionKey, versionString, pubLength, extendedInfo)
                 in cases)
        {
            byte[]? pub = null;
            byte[]? signature = null;
            if (pubLength > 0)
            {
                pub = stream.Next(pubLength);
                pub[0] = 0x04;
                signature = HalyardStreamKeySchedule.ComputeEcdhSignature(stream.Next(16), pub);
            }

            var payload = new Avstream.SessionReplyPayload
            {
                ServerVersion = version,
                Token = token,
                EncryptedKeyAccepted = keyOk,
                VersionAccepted = versionOk,
                SessionKey = sessionKey,
            };
            if (versionString is not null)
                payload.ServerVersionString = versionString;
            if (pub is not null)
                payload.EcdhPublicKey = Google.Protobuf.ByteString.CopyFrom(pub);
            if (signature is not null)
                payload.EcdhSignature = Google.Protobuf.ByteString.CopyFrom(signature);
            if (extendedInfo)
                payload.ExtendedInfo = new Avstream.EventCode { EventCode_ = "0", Name = "ok" };

            var message = new Avstream.ControlMessage
            {
                Type = Avstream.ControlMessage.Types.MessageType.SessionReply,
                SessionReplyPayload = payload,
            };

            sb.AppendLine($"sessionreply {Hex(message.ToByteArray())} {version} {token} " +
                $"{(keyOk ? 1 : 0)} {(versionOk ? 1 : 0)} {HexOrDash(sessionKey)} " +
                $"{(versionString is null ? "-" : HexOrDash(versionString))} " +
                $"{HexOrDash(pub)} {HexOrDash(signature)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // ---- the stream/A-V plane crypto: GMAC (via AES-GCM), the stream KDF, and per-packet nonce/tag ----

    private static (int Gmac, int StreamKdf, int PacketNonce, int PacketTag) EmitStreamCryptoFile(string outPath)
    {
        var stream = new DerivedBytes(Domain + "/stream");
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds v1 stream-plane crypto known-answer vectors");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# inputs are SHA-256(\"" + Domain + "/stream\" || counter). DO NOT EDIT - regenerate.");
        sb.AppendLine("version 1");
        sb.AppendLine();

        int gmacCount = EmitGmac(sb, stream);
        int kdfCount = EmitStreamKdf(sb, stream);
        int nonceCount = EmitPacketNonce(sb, stream);
        int tagCount = EmitPacketTag(sb, stream);

        File.WriteAllText(outPath, sb.ToString());
        return (gmacCount, kdfCount, nonceCount, tagCount);
    }

    // gmac <key16> <iv16> <aad_hex> <tag16>
    // The Halyard packet MAC uses a full 16-byte GCM IV (AesGcmCore's whole reason to exist over the
    // platform AesGcm, which refuses non-96-bit nonces), so every vector here uses a 16-byte IV - the
    // ONLY IV length this port's C implementation ever needs to get right.
    private static int EmitGmac(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# gmac <key16> <iv16> <aad_hex> <tag16>");
        int count = 0;

        // AAD lengths bracketing the GHASH block boundary, plus 0 (a packet whose only "payload" is the
        // zeroed tag/key-position fields still needs empty-vs-nonempty AAD to both work).
        int[] lengths = [0, 1, 15, 16, 17, 31, 32, 33, 100];
        foreach (int length in lengths)
        {
            byte[] key = stream.Next(16);
            byte[] iv = stream.Next(16);
            byte[] aad = stream.Next(length);
            byte[] tag = AesGcmCore.Mac(key, iv, aad);
            // A zero-length AAD would otherwise print as two adjacent spaces, which a whitespace-splitting
            // reader (strtok and friends) silently collapses - shifting every later field by one instead
            // of reporting an empty one. "-" is not valid hex, so a reader must special-case it rather
            // than accidentally parsing it as data.
            string aadField = aad.Length == 0 ? "-" : Hex(aad);
            sb.AppendLine($"gmac {Hex(key)} {Hex(iv)} {aadField} {Hex(tag)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // streamkdf <sharedSecretHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>
    // Shared-secret lengths cover both curves this port must support (32-byte P-256 X, 66-byte P-521 X) -
    // HMAC-SHA256 hashes an over-length key down internally, so a from-scratch HMAC that only handles a
    // <=64-byte key would pass every other vector in this file and fail only here.
    private static int EmitStreamKdf(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# streamkdf <sharedSecretHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>");
        int count = 0;

        foreach (int secretLength in new[] { 32, 66 })
        {
            foreach (byte direction in new byte[] {
                HalyardStreamKeySchedule.DirectionClientToServer, HalyardStreamKeySchedule.DirectionServerToClient })
            {
                byte[] sharedSecret = stream.Next(secretLength);
                byte[] handshakeKey = stream.Next(16);
                var keys = HalyardStreamKeySchedule.DeriveDirection(sharedSecret, handshakeKey, direction);
                sb.AppendLine($"streamkdf {Hex(sharedSecret)} {Hex(handshakeKey)} {direction} " +
                    $"{Hex(keys.AesKey)} {Hex(keys.BaseIv)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // packetnonce <aesKey16> <baseIv16> <keyPos> <gmacNonce16> <ctrNonce16> <gmacKey16>
    // keyPos values bracket the 16-byte block boundary (nonce derivation divides by 16), the rotation
    // window edge (45000, where the GMAC key changes), and the 32-/64-bit edges the same way the
    // control-plane IV vectors already do - a port that adds the key-position delta as a 32-bit value
    // passes every short session and fails only past 2^32.
    private static int EmitPacketNonce(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# packetnonce <aesKey16> <baseIv16> <keyPos> <gmacNonce16> <ctrNonce16> <gmacKey16>");
        int count = 0;

        ulong[] keyPositions = [
            0, 1, 15, 16, 17,
            45000 * 16 - 16, 45000 * 16, 45000 * 16 + 16, // either side of the first rotation boundary
            90000 * 16, // a second rotation window
            0xFFFF_FFFFUL, 0x1_0000_0000UL, ulong.MaxValue - 16,
        ];

        // Hoisted out of the loop: a stackalloc inside a loop body is a stack-overflow risk waiting on
        // enough iterations (CA2014), the same reasoning DerivedBytes.Next already documents below.
        Span<byte> gmacNonce = stackalloc byte[16];
        Span<byte> ctrNonce = stackalloc byte[16];
        Span<byte> gmacKey = stackalloc byte[16];

        foreach (ulong keyPos in keyPositions)
        {
            byte[] aesKey = stream.Next(16);
            byte[] baseIv = stream.Next(16);
            using var crypto = new HalyardPacketCrypto(aesKey, baseIv);

            crypto.GmacNonce(keyPos, gmacNonce);
            crypto.CtrNonce(keyPos, ctrNonce);
            crypto.GmacKey(keyPos, gmacKey);

            sb.AppendLine($"packetnonce {Hex(aesKey)} {Hex(baseIv)} {keyPos} " +
                $"{Hex(gmacNonce.ToArray())} {Hex(ctrNonce.ToArray())} {Hex(gmacKey.ToArray())}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // packettag <aesKey16> <baseIv16> <keyPos> <zeroKeyPos 0|1> <tagOffset> <packet_hex> <tag4>
    // The full per-packet path (nonce+key derivation, AAD zeroing, GMAC, 4-byte truncation) exactly as
    // HalyardPacketCrypto.ComputeTag runs it - both AAD-zeroing conventions (A/V: tag-only; control/
    // congestion: tag+key-position), since that convention is the one place this layer is genuinely
    // protocol-specific rather than "just GCM".
    private static int EmitPacketTag(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# packettag <aesKey16> <baseIv16> <keyPos> <zeroKeyPos> <tagOffset> <packet_hex> <tag4>");
        int count = 0;

        (int tagOffset, bool zeroKeyPos)[] classes = [
            (HalyardPacketCrypto.AvTagOffset, false),      // video/audio
            (HalyardPacketCrypto.FeedbackTagOffset, false), // feedback/input
            (5, true),                                      // control (tag@5, zeroes tag+keypos@9)
            (7, true),                                       // congestion (tag@7, zeroes tag+keypos@0xb)
        ];

        foreach ((int tagOffset, bool zeroKeyPos) in classes)
        {
            foreach (ulong keyPos in new ulong[] { 0, 16, 45000 * 16 + 32 })
            {
                byte[] aesKey = stream.Next(16);
                byte[] baseIv = stream.Next(16);
                byte[] packet = stream.Next(tagOffset + 4 + 20); // header-ish bytes + a bit of "payload"
                using var crypto = new HalyardPacketCrypto(aesKey, baseIv);

                byte[] tag = crypto.ComputeTag(keyPos, packet, tagOffset, zeroKeyPos);
                sb.AppendLine($"packettag {Hex(aesKey)} {Hex(baseIv)} {keyPos} {(zeroKeyPos ? 1 : 0)} " +
                    $"{tagOffset} {Hex(packet)} {Hex(tag)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // ---- kdf <ps4|ps5> <nonce> <companion> => <key> <material> ----

    private static int EmitKdf(StringBuilder sb, HalyardControlKdf kdf, HalyardControlSecrets secrets, DerivedBytes stream)
    {
        sb.AppendLine("# kdf <family> <nonce16> <companion16> <key16> <material16>");
        int count = 0;

        // The table index is nonce[7]>>3 and nonce[0]>>3, so sweep both selector bytes across all 32 entries
        // rather than trusting a handful of samples: an off-by-one in the shift or the entry stride is the
        // most likely porting error and it only shows up at specific indices.
        for (int index = 0; index < 32; index++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            nonce[0] = (byte)((index << 3) | (nonce[0] & 0x07));
            nonce[7] = (byte)((index << 3) | (nonce[7] & 0x07));

            count += Row(sb, kdf, "ps5", nonce, companion, 1);
            if (secrets.HasPs4Tables)
                count += Row(sb, kdf, "ps4", nonce, companion, 0);
        }

        // Plus a handful where the two selector bytes differ, so a port that accidentally uses one index for
        // both tables still fails.
        for (int i = 0; i < 8; i++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            nonce[0] = (byte)(i << 3);
            nonce[7] = (byte)((31 - i) << 3);

            count += Row(sb, kdf, "ps5", nonce, companion, 1);
            if (secrets.HasPs4Tables)
                count += Row(sb, kdf, "ps4", nonce, companion, 0);
        }

        sb.AppendLine();
        return count;

        static int Row(StringBuilder sb, HalyardControlKdf kdf, string family, byte[] nonce, byte[] companion, int selector)
        {
            var (key, material) = kdf.Derive(nonce, companion, selector);
            sb.AppendLine($"kdf {family} {Hex(nonce)} {Hex(companion)} {Hex(key)} {Hex(material)}");
            return 1;
        }
    }

    // ---- ctxkey <codecSelector> <versionSelector> => <key> ----

    private static int EmitContextKeys(StringBuilder sb, HalyardFieldContextKeys keys)
    {
        sb.AppendLine("# ctxkey <codecSelector> <versionSelector> <key16>");
        int count = 0;

        // Cover the high-band codec cases (8, 9) that win regardless of version, the two version selectors,
        // and a value that falls through to the zero fallback.
        foreach (int codec in new[] { 0, 1, 7, 8, 9, 10, 255 })
        {
            foreach (int version in new[] { 0, 1, 2 })
            {
                sb.AppendLine($"ctxkey {codec} {version} {Hex(keys.Select(codec, version).ToArray())}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // ---- iv <contextKey> <material> <counter> => <iv> ----

    private static int EmitFieldIv(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# iv <contextKey16> <material16> <counter> <iv16>");
        int count = 0;

        // The counter is a big-endian uint64 appended to the material. Include values that straddle byte
        // boundaries and the 32-bit edge, because a port that writes it little-endian or as a uint32 passes
        // every small-counter case and then fails on a long session.
        ulong[] counters = [0, 1, 2, 3, 4, 255, 256, 65535, 65536, 0x7FFFFFFF, 0xFFFFFFFF, 0x1_0000_0000, ulong.MaxValue];
        foreach (ulong counter in counters)
        {
            byte[] contextKey = stream.Next(16);
            byte[] material = stream.Next(16);
            byte[] iv = HalyardFieldIv.Derive(contextKey, material, counter);
            sb.AppendLine($"iv {Hex(contextKey)} {Hex(material)} {counter} {Hex(iv)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // ---- cfb/ofb <key> <iv> <input> => <output> ----

    private static int EmitCipherModes(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# cfbenc/cfbdec/ofb <key16> <iv16> <input> <output>");
        int count = 0;

        // Lengths that bracket the block boundary. CFB128's partial final block does NOT feed forward, and
        // that rule is invisible at exact multiples of 16 - which is why 1, 15, 17 and 33 are here.
        int[] lengths = [1, 2, 15, 16, 17, 31, 32, 33, 47, 64, 100];
        foreach (int length in lengths)
        {
            byte[] key = stream.Next(16);
            byte[] iv = stream.Next(16);
            byte[] plaintext = stream.Next(length);

            byte[] ciphertext = Ripcord.Core.Net.Crypto.AesKeystreamModes.Cfb128(key, iv, plaintext, encrypt: true);
            sb.AppendLine($"cfbenc {Hex(key)} {Hex(iv)} {Hex(plaintext)} {Hex(ciphertext)}");

            // Decrypt is a distinct code path (the feedback register takes the input, not the output), so it
            // gets its own vector instead of being assumed to be the inverse.
            byte[] recovered = Ripcord.Core.Net.Crypto.AesKeystreamModes.Cfb128(key, iv, ciphertext, encrypt: false);
            sb.AppendLine($"cfbdec {Hex(key)} {Hex(iv)} {Hex(ciphertext)} {Hex(recovered)}");

            byte[] ofb = Ripcord.Core.Net.Crypto.AesKeystreamModes.Ofb(key, iv, plaintext);
            sb.AppendLine($"ofb {Hex(key)} {Hex(iv)} {Hex(plaintext)} {Hex(ofb)}");
            count += 3;
        }

        sb.AppendLine();
        return count;
    }

    // ---- field: the whole chain, nonce+companion -> header value ----

    private static int EmitEndToEnd(
        StringBuilder sb, HalyardControlKdf kdf, HalyardFieldContextKeys contextKeys, DerivedBytes stream)
    {
        sb.AppendLine("# field <nonce16> <companion16> <codecSel> <verSel> <counter> <plaintext> <ciphertextBase64>");
        sb.AppendLine("# the full chain: kdf -> context-key select -> field iv -> aes-128-cfb -> base64");
        int count = 0;

        // Counters 0..4 are the real field order (RP-Auth, RP-Did, RP-OSType, RP-StartBitrate,
        // RP-StreamingType); the rest of the sweep is there to catch a port that hard-codes the sequence.
        foreach (int codec in new[] { 0, 8 })
        {
            for (ulong counter = 0; counter < 5; counter++)
            {
                byte[] nonce = stream.Next(16);
                byte[] companion = stream.Next(16);
                byte[] plaintext = stream.Next(counter == 3 || counter == 4 ? 4 : 16); // int fields are 4 bytes

                var crypto = HalyardControlFieldCrypto.FromKdf(kdf, contextKeys, nonce, companion, codec, versionSelector: 1);
                string b64 = crypto.EncryptFieldBase64(counter, plaintext);
                sb.AppendLine($"field {Hex(nonce)} {Hex(companion)} {codec} 1 {counter} {Hex(plaintext)} {b64}");
                count++;
            }
        }

        // And the streaminfo/launchSpec path, which shares the IV derivation but uses OFB.
        sb.AppendLine("# streaminfo <nonce16> <companion16> <codecSel> <verSel> <counter> <input> <output>");
        for (int i = 0; i < 4; i++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            byte[] data = stream.Next(48 + i * 7);

            var crypto = HalyardControlFieldCrypto.FromKdf(kdf, contextKeys, nonce, companion, 0, versionSelector: 1);
            byte[] output = crypto.StreaminfoCrypt((ulong)i, data);
            sb.AppendLine($"streaminfo {Hex(nonce)} {Hex(companion)} 0 1 {i} {Hex(data)} {Hex(output)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    private static string Hex(byte[] value) => Convert.ToHexString(value).ToLowerInvariant();

    /// <summary>
    /// A reproducible byte source: SHA-256(domain || counter), concatenated. Not a CSPRNG and not trying to
    /// be one — the requirement is that two people on two machines regenerate an identical file.
    /// </summary>
    private sealed class DerivedBytes(string domain)
    {
        private readonly byte[] _domain = Encoding.ASCII.GetBytes(domain);
        private ulong _counter;

        public byte[] Next(int count)
        {
            var output = new byte[count];

            // Both buffers are hoisted out of the loop: allocating them per iteration is a stack overflow
            // waiting on a large enough request (CA2014), and the domain half never changes anyway.
            Span<byte> message = stackalloc byte[_domain.Length + sizeof(ulong)];
            Span<byte> block = stackalloc byte[32];
            _domain.CopyTo(message);

            int written = 0;
            while (written < count)
            {
                System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(message[_domain.Length..], _counter++);
                SHA256.HashData(message, block);

                int take = Math.Min(32, count - written);
                block[..take].CopyTo(output.AsSpan(written));
                written += take;
            }
            return output;
        }
    }
}
