using System.Security.Cryptography;
using System.Text;
using Ripcord.Core.Net.Crypto;
using Ripcord.Protocol.Halyard.Common.Crypto.V1;
using Ripcord.Protocol.Halyard.Session;

namespace Ripcord.ProtocolLab;

/// <summary>
/// Emits known-answer vectors for the v1 control-plane crypto, so a second implementation of this protocol
/// can be checked against this one without a console, a capture, or a .NET runtime.
///
/// <para>
/// This exists for <c>ports/ripcord-3ds</c>, the C client for modded 3DS hardware. That port re-derives the
/// same primitives from the same spec in a different language, which is only a meaningful check on the spec
/// if both sides are provably computing the same numbers. These vectors are that check: this command writes
/// them, the port's host-side <c>vector_runner</c> reads them, and a disagreement is a spec defect rather
/// than a porting detail.
/// </para>
///
/// <para>
/// <b>The constants come from the bundle, deliberately</b> — <see cref="HalyardInteropConstants"/> directly,
/// not <see cref="HalyardControlSecretsLoader"/>. The port generates its constants from the same committed
/// <c>halyard-v1-constants.json</c>, so both sides must key off that one file or the comparison proves
/// nothing. A developer with a local dirty-room fixture is intentionally NOT allowed to influence this
/// output; if the fixture ever disagreed with the bundle, that is a finding about the bundle, and it should
/// not be discovered as a mystery failure in a C test on a handheld.
/// </para>
///
/// <para>
/// <b>Inputs are derived, not random.</b> Every nonce, companion, key and plaintext comes from
/// SHA-256("ripcord-3ds-vectors/v1" || counter), so the file is byte-identical across runs and machines. That
/// keeps it diffable: a change in this file means a change in the crypto, which is exactly the signal
/// wanted. Do not switch this to <see cref="RandomNumberGenerator"/>.
/// </para>
///
/// <para>
/// The output carries no live material. Its inputs are synthetic and its constants are the ones already
/// committed under the <c>NOTICE</c> interoperability-constants exception, so the file is strictly less
/// sensitive than the bundle it derives from. It is still gitignored as a build artifact — regenerating it
/// is one command, and a committed copy would only invite the question of whether it is a second bundle.
/// </para>
/// </summary>
internal static class LabVectors
{
    private const string Domain = "ripcord-3ds-vectors/v1";

    /// <summary>vectors [outPath] — write the control-crypto known-answer vectors.</summary>
    public static int Emit(string[] args)
    {
        string outPath = args.Length > 1
            ? args[1]
            : Path.Combine("ports", "ripcord-3ds", "tests", "vectors", "control-crypto.kat");

        var secrets = HalyardInteropConstants.Control();
        if (secrets is null)
        {
            Console.Error.WriteLine(
                "no bundled interop constants in this build (-p:BundleInteropConstants=false?); cannot emit vectors.");
            return 1;
        }

        var kdf = new HalyardControlKdf(secrets);
        var stream = new DerivedBytes(Domain);
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds v1 control-crypto known-answer vectors");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# inputs are SHA-256(\"" + Domain + "\" || counter); constants are the committed bundle.");
        sb.AppendLine("# DO NOT EDIT - regenerate. A diff here is a change in the crypto.");
        sb.AppendLine("version 1");
        sb.AppendLine($"ps4tables {(secrets.HasPs4Tables ? 1 : 0)}");
        sb.AppendLine();

        int kdfCount = EmitKdf(sb, kdf, secrets, stream);
        int ctxCount = EmitContextKeys(sb, secrets.ContextKeys);
        int ivCount = EmitFieldIv(sb, stream);
        int modeCount = EmitCipherModes(sb, stream);
        int fieldCount = EmitEndToEnd(sb, kdf, secrets.ContextKeys, stream);

        string? dir = Path.GetDirectoryName(Path.GetFullPath(outPath));
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);
        File.WriteAllText(outPath, sb.ToString());

        Console.WriteLine($"wrote {outPath}");
        Console.WriteLine(
            $"  kdf={kdfCount} ctxkey={ctxCount} iv={ivCount} mode={modeCount} field={fieldCount}  " +
            $"(ps4 tables {(secrets.HasPs4Tables ? "present" : "absent")})");

        // A separate file, not appended to the control-crypto one above: this is a different cipher
        // entirely (the stream/A-V plane's AES-GCM-derived GMAC, not the control plane's AES-CFB/OFB),
        // checked by a separate host-side runner in the C port.
        string streamOutPath = string.IsNullOrEmpty(dir) ? "stream-crypto.kat" : Path.Combine(dir, "stream-crypto.kat");
        var streamCounts = EmitStreamCryptoFile(streamOutPath);
        Console.WriteLine($"wrote {streamOutPath}");
        Console.WriteLine($"  gmac={streamCounts.Gmac} streamkdf={streamCounts.StreamKdf} " +
            $"packetnonce={streamCounts.PacketNonce} packettag={streamCounts.PacketTag}");

        return 0;
    }

    // ---- the stream/A-V plane crypto: GMAC (via AES-GCM), the stream KDF, and per-packet nonce/tag ----

    private static (int Gmac, int StreamKdf, int PacketNonce, int PacketTag) EmitStreamCryptoFile(string outPath)
    {
        var stream = new DerivedBytes(Domain + "/stream");
        var sb = new StringBuilder();

        sb.AppendLine("# ripcord-3ds v1 stream-plane crypto known-answer vectors");
        sb.AppendLine("# generated by: dotnet run --project tools/Ripcord.ProtocolLab -- vectors <path>");
        sb.AppendLine("# inputs are SHA-256(\"" + Domain + "/stream\" || counter). DO NOT EDIT - regenerate.");
        sb.AppendLine("version 1");
        sb.AppendLine();

        int gmacCount = EmitGmac(sb, stream);
        int kdfCount = EmitStreamKdf(sb, stream);
        int nonceCount = EmitPacketNonce(sb, stream);
        int tagCount = EmitPacketTag(sb, stream);

        File.WriteAllText(outPath, sb.ToString());
        return (gmacCount, kdfCount, nonceCount, tagCount);
    }

    // gmac <key16> <iv16> <aad_hex> <tag16>
    // The Halyard packet MAC uses a full 16-byte GCM IV (AesGcmCore's whole reason to exist over the
    // platform AesGcm, which refuses non-96-bit nonces), so every vector here uses a 16-byte IV - the
    // ONLY IV length this port's C implementation ever needs to get right.
    private static int EmitGmac(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# gmac <key16> <iv16> <aad_hex> <tag16>");
        int count = 0;

        // AAD lengths bracketing the GHASH block boundary, plus 0 (a packet whose only "payload" is the
        // zeroed tag/key-position fields still needs empty-vs-nonempty AAD to both work).
        int[] lengths = [0, 1, 15, 16, 17, 31, 32, 33, 100];
        foreach (int length in lengths)
        {
            byte[] key = stream.Next(16);
            byte[] iv = stream.Next(16);
            byte[] aad = stream.Next(length);
            byte[] tag = AesGcmCore.Mac(key, iv, aad);
            // A zero-length AAD would otherwise print as two adjacent spaces, which a whitespace-splitting
            // reader (strtok and friends) silently collapses - shifting every later field by one instead
            // of reporting an empty one. "-" is not valid hex, so a reader must special-case it rather
            // than accidentally parsing it as data.
            string aadField = aad.Length == 0 ? "-" : Hex(aad);
            sb.AppendLine($"gmac {Hex(key)} {Hex(iv)} {aadField} {Hex(tag)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // streamkdf <sharedSecretHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>
    // Shared-secret lengths cover both curves this port must support (32-byte P-256 X, 66-byte P-521 X) -
    // HMAC-SHA256 hashes an over-length key down internally, so a from-scratch HMAC that only handles a
    // <=64-byte key would pass every other vector in this file and fail only here.
    private static int EmitStreamKdf(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# streamkdf <sharedSecretHex> <handshakeKey16> <direction> <aesKey16> <baseIv16>");
        int count = 0;

        foreach (int secretLength in new[] { 32, 66 })
        {
            foreach (byte direction in new byte[] {
                HalyardStreamKeySchedule.DirectionClientToServer, HalyardStreamKeySchedule.DirectionServerToClient })
            {
                byte[] sharedSecret = stream.Next(secretLength);
                byte[] handshakeKey = stream.Next(16);
                var keys = HalyardStreamKeySchedule.DeriveDirection(sharedSecret, handshakeKey, direction);
                sb.AppendLine($"streamkdf {Hex(sharedSecret)} {Hex(handshakeKey)} {direction} " +
                    $"{Hex(keys.AesKey)} {Hex(keys.BaseIv)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // packetnonce <aesKey16> <baseIv16> <keyPos> <gmacNonce16> <ctrNonce16> <gmacKey16>
    // keyPos values bracket the 16-byte block boundary (nonce derivation divides by 16), the rotation
    // window edge (45000, where the GMAC key changes), and the 32-/64-bit edges the same way the
    // control-plane IV vectors already do - a port that adds the key-position delta as a 32-bit value
    // passes every short session and fails only past 2^32.
    private static int EmitPacketNonce(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# packetnonce <aesKey16> <baseIv16> <keyPos> <gmacNonce16> <ctrNonce16> <gmacKey16>");
        int count = 0;

        ulong[] keyPositions = [
            0, 1, 15, 16, 17,
            45000 * 16 - 16, 45000 * 16, 45000 * 16 + 16, // either side of the first rotation boundary
            90000 * 16, // a second rotation window
            0xFFFF_FFFFUL, 0x1_0000_0000UL, ulong.MaxValue - 16,
        ];

        // Hoisted out of the loop: a stackalloc inside a loop body is a stack-overflow risk waiting on
        // enough iterations (CA2014), the same reasoning DerivedBytes.Next already documents below.
        Span<byte> gmacNonce = stackalloc byte[16];
        Span<byte> ctrNonce = stackalloc byte[16];
        Span<byte> gmacKey = stackalloc byte[16];

        foreach (ulong keyPos in keyPositions)
        {
            byte[] aesKey = stream.Next(16);
            byte[] baseIv = stream.Next(16);
            using var crypto = new HalyardPacketCrypto(aesKey, baseIv);

            crypto.GmacNonce(keyPos, gmacNonce);
            crypto.CtrNonce(keyPos, ctrNonce);
            crypto.GmacKey(keyPos, gmacKey);

            sb.AppendLine($"packetnonce {Hex(aesKey)} {Hex(baseIv)} {keyPos} " +
                $"{Hex(gmacNonce.ToArray())} {Hex(ctrNonce.ToArray())} {Hex(gmacKey.ToArray())}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // packettag <aesKey16> <baseIv16> <keyPos> <zeroKeyPos 0|1> <tagOffset> <packet_hex> <tag4>
    // The full per-packet path (nonce+key derivation, AAD zeroing, GMAC, 4-byte truncation) exactly as
    // HalyardPacketCrypto.ComputeTag runs it - both AAD-zeroing conventions (A/V: tag-only; control/
    // congestion: tag+key-position), since that convention is the one place this layer is genuinely
    // protocol-specific rather than "just GCM".
    private static int EmitPacketTag(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# packettag <aesKey16> <baseIv16> <keyPos> <zeroKeyPos> <tagOffset> <packet_hex> <tag4>");
        int count = 0;

        (int tagOffset, bool zeroKeyPos)[] classes = [
            (HalyardPacketCrypto.AvTagOffset, false),      // video/audio
            (HalyardPacketCrypto.FeedbackTagOffset, false), // feedback/input
            (5, true),                                      // control (tag@5, zeroes tag+keypos@9)
            (7, true),                                       // congestion (tag@7, zeroes tag+keypos@0xb)
        ];

        foreach ((int tagOffset, bool zeroKeyPos) in classes)
        {
            foreach (ulong keyPos in new ulong[] { 0, 16, 45000 * 16 + 32 })
            {
                byte[] aesKey = stream.Next(16);
                byte[] baseIv = stream.Next(16);
                byte[] packet = stream.Next(tagOffset + 4 + 20); // header-ish bytes + a bit of "payload"
                using var crypto = new HalyardPacketCrypto(aesKey, baseIv);

                byte[] tag = crypto.ComputeTag(keyPos, packet, tagOffset, zeroKeyPos);
                sb.AppendLine($"packettag {Hex(aesKey)} {Hex(baseIv)} {keyPos} {(zeroKeyPos ? 1 : 0)} " +
                    $"{tagOffset} {Hex(packet)} {Hex(tag)}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // ---- kdf <ps4|ps5> <nonce> <companion> => <key> <material> ----

    private static int EmitKdf(StringBuilder sb, HalyardControlKdf kdf, HalyardControlSecrets secrets, DerivedBytes stream)
    {
        sb.AppendLine("# kdf <family> <nonce16> <companion16> <key16> <material16>");
        int count = 0;

        // The table index is nonce[7]>>3 and nonce[0]>>3, so sweep both selector bytes across all 32 entries
        // rather than trusting a handful of samples: an off-by-one in the shift or the entry stride is the
        // most likely porting error and it only shows up at specific indices.
        for (int index = 0; index < 32; index++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            nonce[0] = (byte)((index << 3) | (nonce[0] & 0x07));
            nonce[7] = (byte)((index << 3) | (nonce[7] & 0x07));

            count += Row(sb, kdf, "ps5", nonce, companion, 1);
            if (secrets.HasPs4Tables)
                count += Row(sb, kdf, "ps4", nonce, companion, 0);
        }

        // Plus a handful where the two selector bytes differ, so a port that accidentally uses one index for
        // both tables still fails.
        for (int i = 0; i < 8; i++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            nonce[0] = (byte)(i << 3);
            nonce[7] = (byte)((31 - i) << 3);

            count += Row(sb, kdf, "ps5", nonce, companion, 1);
            if (secrets.HasPs4Tables)
                count += Row(sb, kdf, "ps4", nonce, companion, 0);
        }

        sb.AppendLine();
        return count;

        static int Row(StringBuilder sb, HalyardControlKdf kdf, string family, byte[] nonce, byte[] companion, int selector)
        {
            var (key, material) = kdf.Derive(nonce, companion, selector);
            sb.AppendLine($"kdf {family} {Hex(nonce)} {Hex(companion)} {Hex(key)} {Hex(material)}");
            return 1;
        }
    }

    // ---- ctxkey <codecSelector> <versionSelector> => <key> ----

    private static int EmitContextKeys(StringBuilder sb, HalyardFieldContextKeys keys)
    {
        sb.AppendLine("# ctxkey <codecSelector> <versionSelector> <key16>");
        int count = 0;

        // Cover the high-band codec cases (8, 9) that win regardless of version, the two version selectors,
        // and a value that falls through to the zero fallback.
        foreach (int codec in new[] { 0, 1, 7, 8, 9, 10, 255 })
        {
            foreach (int version in new[] { 0, 1, 2 })
            {
                sb.AppendLine($"ctxkey {codec} {version} {Hex(keys.Select(codec, version).ToArray())}");
                count++;
            }
        }

        sb.AppendLine();
        return count;
    }

    // ---- iv <contextKey> <material> <counter> => <iv> ----

    private static int EmitFieldIv(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# iv <contextKey16> <material16> <counter> <iv16>");
        int count = 0;

        // The counter is a big-endian uint64 appended to the material. Include values that straddle byte
        // boundaries and the 32-bit edge, because a port that writes it little-endian or as a uint32 passes
        // every small-counter case and then fails on a long session.
        ulong[] counters = [0, 1, 2, 3, 4, 255, 256, 65535, 65536, 0x7FFFFFFF, 0xFFFFFFFF, 0x1_0000_0000, ulong.MaxValue];
        foreach (ulong counter in counters)
        {
            byte[] contextKey = stream.Next(16);
            byte[] material = stream.Next(16);
            byte[] iv = HalyardFieldIv.Derive(contextKey, material, counter);
            sb.AppendLine($"iv {Hex(contextKey)} {Hex(material)} {counter} {Hex(iv)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    // ---- cfb/ofb <key> <iv> <input> => <output> ----

    private static int EmitCipherModes(StringBuilder sb, DerivedBytes stream)
    {
        sb.AppendLine("# cfbenc/cfbdec/ofb <key16> <iv16> <input> <output>");
        int count = 0;

        // Lengths that bracket the block boundary. CFB128's partial final block does NOT feed forward, and
        // that rule is invisible at exact multiples of 16 - which is why 1, 15, 17 and 33 are here.
        int[] lengths = [1, 2, 15, 16, 17, 31, 32, 33, 47, 64, 100];
        foreach (int length in lengths)
        {
            byte[] key = stream.Next(16);
            byte[] iv = stream.Next(16);
            byte[] plaintext = stream.Next(length);

            byte[] ciphertext = Ripcord.Core.Net.Crypto.AesKeystreamModes.Cfb128(key, iv, plaintext, encrypt: true);
            sb.AppendLine($"cfbenc {Hex(key)} {Hex(iv)} {Hex(plaintext)} {Hex(ciphertext)}");

            // Decrypt is a distinct code path (the feedback register takes the input, not the output), so it
            // gets its own vector instead of being assumed to be the inverse.
            byte[] recovered = Ripcord.Core.Net.Crypto.AesKeystreamModes.Cfb128(key, iv, ciphertext, encrypt: false);
            sb.AppendLine($"cfbdec {Hex(key)} {Hex(iv)} {Hex(ciphertext)} {Hex(recovered)}");

            byte[] ofb = Ripcord.Core.Net.Crypto.AesKeystreamModes.Ofb(key, iv, plaintext);
            sb.AppendLine($"ofb {Hex(key)} {Hex(iv)} {Hex(plaintext)} {Hex(ofb)}");
            count += 3;
        }

        sb.AppendLine();
        return count;
    }

    // ---- field: the whole chain, nonce+companion -> header value ----

    private static int EmitEndToEnd(
        StringBuilder sb, HalyardControlKdf kdf, HalyardFieldContextKeys contextKeys, DerivedBytes stream)
    {
        sb.AppendLine("# field <nonce16> <companion16> <codecSel> <verSel> <counter> <plaintext> <ciphertextBase64>");
        sb.AppendLine("# the full chain: kdf -> context-key select -> field iv -> aes-128-cfb -> base64");
        int count = 0;

        // Counters 0..4 are the real field order (RP-Auth, RP-Did, RP-OSType, RP-StartBitrate,
        // RP-StreamingType); the rest of the sweep is there to catch a port that hard-codes the sequence.
        foreach (int codec in new[] { 0, 8 })
        {
            for (ulong counter = 0; counter < 5; counter++)
            {
                byte[] nonce = stream.Next(16);
                byte[] companion = stream.Next(16);
                byte[] plaintext = stream.Next(counter == 3 || counter == 4 ? 4 : 16); // int fields are 4 bytes

                var crypto = HalyardControlFieldCrypto.FromKdf(kdf, contextKeys, nonce, companion, codec, versionSelector: 1);
                string b64 = crypto.EncryptFieldBase64(counter, plaintext);
                sb.AppendLine($"field {Hex(nonce)} {Hex(companion)} {codec} 1 {counter} {Hex(plaintext)} {b64}");
                count++;
            }
        }

        // And the streaminfo/launchSpec path, which shares the IV derivation but uses OFB.
        sb.AppendLine("# streaminfo <nonce16> <companion16> <codecSel> <verSel> <counter> <input> <output>");
        for (int i = 0; i < 4; i++)
        {
            byte[] nonce = stream.Next(16);
            byte[] companion = stream.Next(16);
            byte[] data = stream.Next(48 + i * 7);

            var crypto = HalyardControlFieldCrypto.FromKdf(kdf, contextKeys, nonce, companion, 0, versionSelector: 1);
            byte[] output = crypto.StreaminfoCrypt((ulong)i, data);
            sb.AppendLine($"streaminfo {Hex(nonce)} {Hex(companion)} 0 1 {i} {Hex(data)} {Hex(output)}");
            count++;
        }

        sb.AppendLine();
        return count;
    }

    private static string Hex(byte[] value) => Convert.ToHexString(value).ToLowerInvariant();

    /// <summary>
    /// A reproducible byte source: SHA-256(domain || counter), concatenated. Not a CSPRNG and not trying to
    /// be one — the requirement is that two people on two machines regenerate an identical file.
    /// </summary>
    private sealed class DerivedBytes(string domain)
    {
        private readonly byte[] _domain = Encoding.ASCII.GetBytes(domain);
        private ulong _counter;

        public byte[] Next(int count)
        {
            var output = new byte[count];

            // Both buffers are hoisted out of the loop: allocating them per iteration is a stack overflow
            // waiting on a large enough request (CA2014), and the domain half never changes anyway.
            Span<byte> message = stackalloc byte[_domain.Length + sizeof(ulong)];
            Span<byte> block = stackalloc byte[32];
            _domain.CopyTo(message);

            int written = 0;
            while (written < count)
            {
                System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(message[_domain.Length..], _counter++);
                SHA256.HashData(message, block);

                int take = Math.Min(32, count - written);
                block[..take].CopyTo(output.AsSpan(written));
                written += take;
            }
            return output;
        }
    }
}
